# -*- coding: utf-8 -*-
"""01_eda_general.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1481cWCfAgTIs0G3vZDBiNgm6RojIwtxD

# **Análisis Explortario de Datos Inicial**

## Configuracion
"""

# Commented out IPython magic to ensure Python compatibility.
# # versiones
# %%writefile requirements.txt
# pandas==2.2.2
# matplotlib==3.10.0
# seaborn==0.13.2

# instalar versiones de librerias
!pip install -r requirements.txt

def analizar_nulos(df, columna):
    """
    Analiza la cantidad y porcentaje de valores nulos en una columna.

    Parámetros:
    - df: DataFrame
    - columna: nombre de la columna (str)
    """

    total_registros = len(df)
    cantidad_nulos = df[columna].isnull().sum()
    porcentaje_nulos = (cantidad_nulos / total_registros) * 100

    print("\n" + "="*50)
    print(f" VALORES NULOS - {columna.upper()}")
    print("="*50)
    print(f"Cantidad de valores nulos: {cantidad_nulos:,}")
    print(f"Porcentaje de nulos: {porcentaje_nulos:.2f}%")

def analizar_valores_unicos(df, columna, max_mostrar=20):
    """
    Muestra los valores únicos de una columna y su cantidad.

    Parámetros:
    - df: DataFrame
    - columna: nombre de la columna (str)
    - max_mostrar: número máximo de valores únicos a mostrar
    """

    valores_unicos = df[columna].unique()
    cantidad_unicos = len(valores_unicos)

    print("\n" + "="*50)
    print(f" VALORES ÚNICOS - {columna.upper()}")
    print("="*50)
    print(f"Cantidad de valores únicos: {cantidad_unicos:,}")

    print(f"\nPrimeros {min(max_mostrar, cantidad_unicos)} valores:")
    print(valores_unicos[:max_mostrar])

def eliminar_nulos_por_columna(df, columna, inplace=False):
    """
    Elimina los registros (filas) donde una columna específica tiene valores nulos.

    Parámetros:
    - df: DataFrame
    - columna: nombre de la columna (str)
    - inplace: si True, modifica el DataFrame original

    Retorna:
    - DataFrame limpio (si inplace=False)
    """

    total_antes = len(df)
    nulos = df[columna].isnull().sum()

    print("\n" + "="*50)
    print(f" ELIMINACIÓN DE NULOS - {columna.upper()}")
    print("="*50)
    print(f"Registros antes: {total_antes:,}")
    print(f"Registros con nulos en '{columna}': {nulos:,}")

    if inplace:
        df.dropna(subset=[columna], inplace=True)
        total_despues = len(df)
        print(f"Registros después: {total_despues:,}")
        print(f"Filas eliminadas: {total_antes - total_despues:,}")
    else:
        df_limpio = df.dropna(subset=[columna])
        total_despues = len(df_limpio)
        print(f"Filas eliminadas: {total_antes - total_despues:,}")
        return df_limpio

# Librerias
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from enum import unique
import matplotlib.dates as mdates

"""## Carga del Dataset

### Diccionario de Datos

| Variable            | Tipo de variable | Rango / Valores posibles | Descripción | Ejemplo | Observaciones |
|--------------------|------------------|--------------------------|-------------|---------|--------------|
| FECHA              | datetime         | 2024-08-24 a 2025-08-16 | Fecha de la transacción | 2024-08-24 | Es el índice del DataFrame |
| Bodega             | categórica       | Valores nominales (nombres de bodegas) | Lugar físico desde donde se realiza la venta | BODEGA CRA 16 | Baja cardinalidad |
| IDFactura          | numérica (int)   | Enteros positivos | Identificador único de la factura | 1909959 | Puede repetirse si hay múltiples productos por factura |
| IDProducto         | numérica (int)   | Enteros positivos | Identificador único del producto | 5243 | Relacionable con catálogo de productos |
| VlrUnitario        | numérica (float) | > 0 | Valor unitario del producto | 3666.6666 | Puede tener decimales |
| Producto           | categórica       | Nombres de productos | Descripción del producto vendido | GRIFLEX LAV/LVP 60 CM | Alta cardinalidad |
| ClaseProducto      | categórica       | Ej: Plomeria | Categoría general del producto | Plomeria | Útil para segmentación |
| TipoProducto       | categórica       | Ej: Grif. Accesorios | Subcategoría del producto | Grif. Accesorios | Más granular que clase |
| FlagImportado      | binaria (int)    | 0, 1 | Indica si el producto es importado | 0 | 1 = importado |
| Cliente            | categórica       | Nombres de clientes | Nombre del cliente | LUIS DANIEL RAMIREZ | Alta cardinalidad |
| Municipio          | categórica       | Municipios de Colombia | Municipio del cliente | BOGOTA DC KENNEDY SUR | Puede incluir localidad |
| Departamento       | categórica       | Departamentos de Colombia | Departamento del cliente | BOGOTA D.C. | Estandarizar nombres |
| Vendedor           | categórica       | Nombres de vendedores o canales comerciales | Persona o canal responsable de la venta | FREDY SABOYA | Alta cardinalidad |
| Facturado          | numérica (int)   | >= 0 | Cantidad facturada del producto | 12 | Representa unidades vendidas, no valor monetario |
| BackOrder          | numérica (int)   | >= 0 | Cantidad pendiente por entregar | 0 | Importante para logística |
| ClaseVenta         | categórica       | Ej: NORMAL | Tipo de venta realizada | NORMAL | Puede incluir promociones |
| ProductoObsequio   | categórica       | Valores o NaN | Producto entregado como obsequio | NaN | Puede tener valores nulos |
| CantidadObsequio   | numérica (int)   | >= 0 | Cantidad de producto obsequiado | 0 | Relacionado con promociones |
| DiasImportacion    | numérica (int)   | >= 0 días | Tiempo que tarda un producto en llegar a la bodega desde que se inicia el proceso de abastecimiento | 45 | Corresponde al lead time de reposición para productos nacionales e importados. Variable clave para la gestión de inventarios, el cálculo de stock de seguridad y la definición de puntos de reorden |
"""

# Drive
from google.colab import drive
drive.mount('/content/drive')

# Visualizar dataset
df = pd.read_csv('/content/drive/MyDrive/Trabajo de Grado JuanPablo/Datasets/Data_Set_05132026.csv', sep=';', on_bad_lines='skip')

# Conversión inicial
df['FECHA'] = pd.to_datetime(df['FECHA'], errors='coerce')

df.head(10)

fecha_inicial = df['FECHA'].min()
fecha_final = df['FECHA'].max()

print(f"Fecha inicial del dataset: {fecha_inicial.strftime('%Y-%m-%d')}")
print(f"Fecha final del dataset: {fecha_final.strftime('%Y-%m-%d')}")

# Cantidad de filas y columnas
df.shape

# Transformación de variables
df['FECHA'] = pd.to_datetime(df['FECHA'], errors='coerce')
df['Bodega'] = df['Bodega'].astype('category')
df['Producto'] = df['Producto'].astype('category')
df['ClaseProducto'] = df['ClaseProducto'].astype('category')
df['TipoProducto'] = df['TipoProducto'].astype('category')
df['Cliente'] = df['Cliente'].astype('category')
df['Municipio'] = df['Municipio'].astype('category')
df['Departamento'] = df['Departamento'].astype('category')
df['IDFactura'] = df['IDFactura'].astype('int64')

# Limpieza segura para columnas numéricas que podrían venir como string
for col in ['Facturado', 'BackOrder', 'CantidadObsequio']:
    if df[col].dtype == 'object':
        df[col] = df[col].str.replace(',', '.').astype(float).fillna(0).astype('int64')
    else:
        df[col] = df[col].fillna(0).astype('int64')

df['ClaseVenta'] = df['ClaseVenta'].astype('category')
df['ProductoObsequio'] = df['ProductoObsequio'].astype('category')

# Tipo de variable
df.info()

# Dataset transformado
df.head()

"""# **Análisis Exploratorio por Variable**

### Fecha
"""

fecha_inicial = df['FECHA'].min()
fecha_final = df['FECHA'].max()

print(f"Fecha IniciaL: {fecha_inicial.strftime('%Y-%m-%d')}")
print(f"Fecha final: {fecha_final.strftime('%Y-%m-%d')}")

analizar_nulos(df, 'FECHA')

"""### Bodega"""

analizar_valores_unicos(df, 'Bodega')

ventas_atlantico = df[df['Departamento'] == 'ATLANTICO']

if ventas_atlantico.empty:
    print("No se encontraron ventas en el departamento de Atlántico.")
else:
    bodegas_atlantico = ventas_atlantico['Bodega'].unique()
    print(f"Las ventas en el departamento de Atlántico provienen de las siguientes bodegas: {list(bodegas_atlantico)}")

ventas_zprincipal = df[df['Bodega'] == 'ZPRINCIPAL']

if ventas_zprincipal.empty:
    print("No se encontraron ventas desde la bodega 'ZPRINCIPAL'.")
else:
    departamentos_zprincipal = ventas_zprincipal['Departamento'].unique()
    print(f"Las ventas desde la bodega 'ZPRINCIPAL' se realizan en los siguientes departamentos: {list(departamentos_zprincipal)}")

analizar_nulos(df, 'Bodega')

"""###  ID Factura y Producto"""

analizar_valores_unicos(df, 'IDFactura')

analizar_nulos(df, 'IDFactura')

analizar_valores_unicos(df, 'IDProducto')

analizar_nulos(df, 'IDProducto')

"""###  VlrUnitario

Al tener menos del 0,01% de datos nulos en esta variable es posible eliminarlo sin perder calidad del conjunto de datos
"""

analizar_nulos(df, 'VlrUnitario')

df = eliminar_nulos_por_columna(df, 'VlrUnitario')

# Análisis de VlrUnitario = 0
total_registros = len(df)
cantidad_VlrUnitario_cero = (df['VlrUnitario'] == 0).sum()
porcentaje_VlrUnitario_cero = (cantidad_VlrUnitario_cero / total_registros) * 100

#Mostrar resultados
print("\n" + "="*80)
print("RESGISTROS CVlrUnitario = 0")
print("="*80)
print(f"Total de registros: {total_registros:,}")
print(f"VlrUnitario igual a cero: {cantidad_VlrUnitario_cero:,}")
print(f"Porcentaje: {porcentaje_VlrUnitario_cero:.2f}%")

"""### Producto (Clase y Tipo)"""

analizar_valores_unicos(df, 'ClaseProducto')

analizar_nulos(df, 'ClaseProducto')

"""#### **Listado de categorías**

* NA/ND | Abrasivos | Acabados | Administrativo | Catalogo de Puntos  
* Construccion | Electricos | ExcluidosLista | Fijacion y Amarres | Griferias  
* Herramientas | Hogar Complementario | Licitaciones | Pinturas Y Adhesivo  
* Plomeria | Proteccion Personal | Quimicos | Seguridad | Variedades  

---

Para este proyecto, y en conjunto con el equipo de analítica de datos y la gerencia comercial, se decidió dejar por fuera del análisis las siguientes categorías:

- **Administrativo**
- **Catálogo de Puntos**
- **ExcluidosLista**
- **Licitaciones**

El análisis se enfoca únicamente en el catálogo de productos dirigido a clientes regulares o frecuentes, entendido como aquellos que realizan **al menos dos compras en un periodo de tres meses**.

Las categorías excluidas corresponden principalmente a líneas de negocio que no hacen parte del consumo habitual, ya sea porque:

- Son transacciones ocasionales y predecibles
- No reflejan la demanda recurrente de los clientes  
- Pertenecen a dinámicas comerciales diferentes
"""

analizar_valores_unicos(df, 'TipoProducto')

analizar_nulos(df, 'TipoProducto')

# Validar si un TipoProducto está asociado a varias ClaseProducto
conteo_clases_por_tipo = df.groupby('TipoProducto')['ClaseProducto'].nunique()

# Filtrar quienes tengan más de una clase
tipos_inconsistentes = conteo_clases_por_tipo[conteo_clases_por_tipo > 1]

if not tipos_inconsistentes.empty:
    print("\n" + "=" * 90)
    print("TIPOS DE PRODUCTO ASOCIADOS A MÁS DE UNA CLASE DE PRODUCTO")
    print("=" * 90)

    for tipo, cantidad_clases in tipos_inconsistentes.sort_values(ascending=False).items():
        clases_asociadas = (
            df[df['TipoProducto'] == tipo]['ClaseProducto']
            .dropna()
            .unique()
            .tolist()
        )

        # Convertir lista a texto horizontal
        clases_str = " | ".join(sorted(clases_asociadas))

        print(f"\nTipoProducto: {tipo}")
        print(f"Cantidad de clases: {cantidad_clases}")
        print(f"Clases asociadas: {clases_str}")

else:
    print("\nNo se encontraron tipos de producto que pertenezcan a más de una clase.")

"""### FlagImportado"""

analizar_nulos(df, 'FlagImportado')

# Distribución de Importados

# Calcular cantidades y porcentajes
counts = df['FlagImportado'].value_counts()
percentages = df['FlagImportado'].value_counts(normalize=True) * 100

# Crear gráfico
plt.figure(figsize=(7, 5))

sns.barplot(
    x=percentages.index,
    y=percentages.values,
    palette='viridis'
)

# Etiquetas
plt.title('Distribución de Productos Importados y Nacionales (%)', fontsize=13)
plt.xlabel('Tipo de Producto', fontsize=11)
plt.ylabel('Porcentaje (%)', fontsize=11)
plt.xticks([0, 1], ['No Importado', 'Importado'])

# Valor barra
for i, v in enumerate(percentages.values):
    plt.text(i, v + 0.5, f"{v:.1f}%", ha='center', fontsize=10)

plt.grid(axis='y', linestyle='--', alpha=0.3)
sns.despine()

plt.tight_layout()
plt.show()

"""### Cliente"""

analizar_valores_unicos(df, 'Cliente')

analizar_nulos(df, 'Cliente')

# ==========================================================
# Limpieza de clientes atípicos
# ==========================================================

# 1. Convertir a string, quitar espacios y pasar a mayúsculas
df['Cliente'] = df['Cliente'].astype(str).str.strip().str.upper()

# 2. Definir palabras o patrones atípicos
# Se eliminarán todos los registros cuyo cliente contenga alguno de estos textos,
# incluso si tienen más palabras, por ejemplo:
# 'CONTADOR AR', 'VENTAS CONTADOR GH', 'CLIENTE MOSTRADOR RC ZONA SUR'
patrones_atipicos = [
    'MOSTRADOR',
    'CONTADOR',
    'CONTADO',
    'LOGISTICA FERRETERA BARRANQUILLA'
]

# 3. Construir patrón regex
patron_regex = '|'.join(patrones_atipicos)

# 4. Identificar registros atípicos
mask_atipicos = df['Cliente'].str.contains(patron_regex, case=False, na=False, regex=True)

# 5. Calcular cantidad y porcentaje de registros atípicos
cantidad_atipicos = mask_atipicos.sum()
total_registros = len(df)
porcentaje_atipicos = (cantidad_atipicos / total_registros) * 100

print("\n" + "=" * 80)
print("ANÁLISIS DE CLIENTES ATÍPICOS")
print("=" * 80)
print(f"Cantidad de registros atípicos: {cantidad_atipicos:,}")
print(f"Porcentaje sobre el total: {porcentaje_atipicos:.2f}%")

# 6. Mostrar ejemplos de clientes detectados
clientes_detectados = df.loc[mask_atipicos, 'Cliente'].dropna().unique().tolist()

print("\nClientes detectados para eliminación:")
print(" | ".join(sorted(clientes_detectados[:30])))

if len(clientes_detectados) > 30:
    print(f"... y {len(clientes_detectados) - 30} valores más")

# 7. Eliminar los registros atípicos
df = df.loc[~mask_atipicos].copy()

# 8. Convertir nuevamente a category
df['Cliente'] = df['Cliente'].astype('category')

import pandas as pd

# Identificar clientes que contienen 'LOGISTICA FERRETERA'
# Convertir la columna 'Cliente' a string para asegurar el funcionamiento de .str.contains()
# y limpiar espacios/convertir a mayúsculas para una búsqueda consistente.
df['Cliente'] = df['Cliente'].astype(str).str.strip().str.upper()

clients_to_remove_mask = df['Cliente'].str.contains('LOGISTICA FERRETERA', case=False, na=False)

# Obtener la lista de nombres de clientes únicos a eliminar
clients_to_remove = df.loc[clients_to_remove_mask, 'Cliente'].unique().tolist()

print(f"\n{'='*50}")
print("CLIENTES A ELIMINAR (contienen 'LOGISTICA FERRETERA')")
print(f"{'='*50}")

if clients_to_remove:
    for client in clients_to_remove:
        print(f"- {client}")
else:
    print("No se encontraron clientes que contengan 'LOGISTICA FERRETERA'.")

# Mostrar el número de registros antes de la eliminación
initial_rows = len(df)
print(f"\nRegistros iniciales en el DataFrame: {initial_rows:,}")

# Eliminar los registros de estos clientes del DataFrame
df = df[~clients_to_remove_mask].copy()

# Mostrar el número de registros después de la eliminación
final_rows = len(df)
print(f"Registros después de la eliminación: {final_rows:,}")
print(f"Filas eliminadas: {initial_rows - final_rows:,}")

# Calcular y mostrar el porcentaje de registros eliminados
percentage_removed = ((initial_rows - final_rows) / initial_rows) * 100 if initial_rows > 0 else 0
print(f"Porcentaje de registros eliminados: {percentage_removed:.2f}%")

# Convertir la columna 'Cliente' de nuevo a category si se desea
df['Cliente'] = df['Cliente'].astype('category')

"""### Municipio y Departamento"""

analizar_valores_unicos(df, 'Departamento')

analizar_nulos(df, 'Departamento')

analizar_valores_unicos(df, 'Municipio')

analizar_nulos(df, 'Municipio')

"""### Vendedor"""

analizar_nulos(df, 'Vendedor')

analizar_valores_unicos(df, 'Vendedor')

# Porcentaje de venta por vendedor
if not pd.api.types.is_numeric_dtype(df['VlrUnitario']):
    df['VlrUnitario'] = (
        df['VlrUnitario']
        .astype(str)
        .str.replace(',', '.', regex=False)
        .astype(float)
    )

if not pd.api.types.is_numeric_dtype(df['Facturado']):
    df['Facturado'] = (
        df['Facturado']
        .astype(str)
        .str.replace(',', '.', regex=False)
        .astype(float)
    )

# Crear variable de venta total
df['VentaTotal'] = df['VlrUnitario'] * df['Facturado']

# Calcular valores
ventas_por_vendedor = df.groupby('Vendedor', observed=False)['VentaTotal'].sum()
total_ventas = df['VentaTotal'].sum()
porcentaje_ventas = (ventas_por_vendedor / total_ventas) * 100
porcentaje_ventas = porcentaje_ventas.sort_values(ascending=False)

# 8. Mostrar resultados
print("\n" + "="*80)
print("PORCENTAJE DE VENTAS TOTALES $$$ POR VENDEDOR")
print("="*80)
for vendedor, porcentaje in porcentaje_ventas.items():
    print(f"{vendedor:35} → {porcentaje:6.2f}%")

def eliminar_vendedores_no_validos(df, columna='Vendedor'):
    """
    Elimina registros de vendedores que no representan ventas reales,
    como administrativos, mostrador, marketplace o transferencias.

    Parámetros:
    - df: DataFrame
    - columna: nombre de la columna de vendedores

    Retorna:
    - DataFrame limpio
    """

    # Estandarizar texto
    df[columna] = df[columna].astype(str).str.strip().str.upper()

    # Patrones a eliminar (reglas de negocio)
    patrones_excluir = [
        'MOSTRADOR',
        'MERCADO LIBRE',
        'LICITACIONES',
        'ADMINISTRATIVO',
        'MGIL-NOUSAR',
        'TRANSFERENCIAS'
    ]

    # Crear patrón regex
    patron_regex = '|'.join(patrones_excluir)

    # Identificar registros a eliminar
    mask_excluir = df[columna].str.contains(patron_regex, na=False, regex=True)

    # Métricas antes de eliminar
    total = len(df)
    cantidad_excluir = mask_excluir.sum()
    porcentaje = (cantidad_excluir / total) * 100

    print("\n" + "="*80)
    print("LIMPIEZA DE VENDEDORES NO VÁLIDOS")
    print("="*80)
    print(f"Registros a eliminar: {cantidad_excluir:,}")
    print(f"Porcentaje del total: {porcentaje:.2f}%")

    # Mostrar ejemplos
    vendedores_detectados = df.loc[mask_excluir, columna].unique().tolist()
    print("\nVendedores detectados:")
    print(" | ".join(sorted(vendedores_detectados[:20])))

    if len(vendedores_detectados) > 20:
        print(f"... y {len(vendedores_detectados) - 20} más")

    # Eliminar registros
    df_limpio = df.loc[~mask_excluir].copy()

    print("\nRegistros después de la limpieza:", f"{len(df_limpio):,}")

    return df_limpio

df = eliminar_vendedores_no_validos(df)

"""### Facturado y BackOrder"""

analizar_nulos(df, 'Facturado')

analizar_valores_unicos(df, 'Facturado')

# Análisis de Facturado = 0
total_registros = len(df)
cantidad_facturado_cero = (df['Facturado'] == 0).sum()
porcentaje_facturado_cero = (cantidad_facturado_cero / total_registros) * 100

#Mostrar resultados
print("\n" + "="*80)
print("RESGISTROS CON FACTURADO = 0")
print("="*80)
print(f"Total de registros: {total_registros:,}")
print(f"Facturado igual a cero: {cantidad_facturado_cero:,}")
print(f"Porcentaje: {porcentaje_facturado_cero:.2f}%")

analizar_nulos(df, 'BackOrder')

# Análisis de BackOrder = 0
total_registros = len(df)
cantidad_backorder_cero = (df['BackOrder'] == 0).sum()
porcentaje_backorder_cero = (cantidad_backorder_cero / total_registros) * 100

#Mostrar resultados
print("\n" + "="*80)
print("RESGISTROS CON BACKORDER = 0")
print("="*80)
print(f"Total de registros: {total_registros:,}")
print(f"BackOrder igual a cero: {cantidad_backorder_cero:,}")
print(f"Porcentaje: {porcentaje_backorder_cero:.2f}%")

# ==========================================================
# PORCENTAJE DE DEMANDA NO ATENDIDA (BACKORDER)
# ==========================================================

# 1. Asegurar variables numéricas
for col in ['VlrUnitario', 'Facturado', 'BackOrder']:
    if not pd.api.types.is_numeric_dtype(df[col]):
        df[col] = df[col].astype(str).str.replace(',', '.', regex=False).astype(float)

# 2. Calcular valores monetarios
df['VentaReal'] = df['Facturado'] * df['VlrUnitario']
df['BackOrderValue'] = df['BackOrder'] * df['VlrUnitario']

# 3. Totales
venta_real_total = df['VentaReal'].sum()
backorder_total = df['BackOrderValue'].sum()

# 4. Demanda total (lo que se quiso vender)
demanda_total = venta_real_total + backorder_total

# 5. Porcentaje de backorder
porcentaje_backorder = (backorder_total / demanda_total) * 100 if demanda_total != 0 else 0

# 6. Mostrar resultados
print("\n" + "="*80)
print("ANÁLISIS DE DEMANDA NO ATENDIDA (BACKORDER)")
print("="*80)
print(f"Venta real total: ${venta_real_total:,.2f}")
print(f"BackOrder total: ${backorder_total:,.2f}")
print(f"Demanda total: ${demanda_total:,.2f}")
print(f"\nPorcentaje de BackOrder: {porcentaje_backorder:.2f}%")

"""### ClaseVenta y Cantidad/Producto Obsequio"""

analizar_valores_unicos(df, 'ClaseVenta')

# ==========================================================
# IDENTIFICACIÓN DE INTERVALOS DE FERIA / EVENTO
# ==========================================================

ventas_feria_evento = df[df['ClaseVenta'] == 'FERIA-EVENTO'].copy()

if ventas_feria_evento.empty:
    print("No se encontraron ventas de tipo 'FERIA-EVENTO' en el dataset.")
else:
    # Asegurar formato de fecha
    ventas_feria_evento['FECHA'] = pd.to_datetime(ventas_feria_evento['FECHA'], errors='coerce')

    # Ordenar por fecha
    ventas_feria_evento = ventas_feria_evento.sort_values('FECHA')

    # Eliminar duplicados de fecha (solo interesa la ocurrencia del día)
    fechas_unicas = ventas_feria_evento['FECHA'].drop_duplicates().sort_values()

    # Calcular diferencia entre días consecutivos
    diff_dias = fechas_unicas.diff().dt.days

    # Definir corte de evento (cuando hay más de 1 día de diferencia)
    evento_id = (diff_dias > 1).cumsum()

    # Crear DataFrame auxiliar
    df_eventos = pd.DataFrame({
        'FECHA': fechas_unicas,
        'evento_id': evento_id
    })

    # Agrupar por evento
    intervalos_eventos = df_eventos.groupby('evento_id')['FECHA'].agg(['min', 'max'])

    # Mostrar resultados
    print("\n" + "="*80)
    print("INTERVALOS DE FERIAS / EVENTOS DETECTADOS")
    print("="*80)

    for i, row in intervalos_eventos.iterrows():
        inicio = row['min'].strftime('%d-%m-%Y')
        fin = row['max'].strftime('%d-%m-%Y')
        duracion = (row['max'] - row['min']).days + 1

        print(f"Evento {i+1}: Inicio = {inicio} | Fin = {fin} | Duración = {duracion} días")

analizar_nulos(df, 'ClaseVenta')

# Distribución de ClaseVenta (%)

# Calcular porcentajes
percentages = df['ClaseVenta'].value_counts(normalize=True) * 100

# Gráfico
plt.figure(figsize=(7, 5))
ax = sns.barplot(
    x=percentages.index,
    y=percentages.values,
    palette='viridis'
)

# Títulos
plt.title('Distribución de ClaseVenta (%)')
plt.xlabel('Tipo de Venta')
plt.ylabel('Porcentaje (%)')

# Etiquetas
for barra in ax.patches:
    altura = barra.get_height()
    ax.text(
        barra.get_x() + barra.get_width()/2,
        altura + 0.5,
        f"{altura:.1f}%",
        ha='center'
    )

sns.despine()
plt.tight_layout()
plt.show()

analizar_nulos(df, 'CantidadObsequio')

# Análisis de CantidadObsequio = 0
total_registros = len(df)
cantidad_CantidadObsequio_cero = (df['CantidadObsequio'] == 0).sum()
porcentaje_CantidadObsequio_cero = (cantidad_CantidadObsequio_cero / total_registros) * 100

#Mostrar resultados
print("\n" + "="*80)
print("RESGISTROS CON CantidadObsequio = 0")
print("="*80)
print(f"Total de registros: {total_registros:,}")
print(f"CantidadObsequio igual a cero: {cantidad_CantidadObsequio_cero:,}")
print(f"Porcentaje: {porcentaje_CantidadObsequio_cero:.2f}%")

"""### DiasImportacion


"""

analizar_valores_unicos(df, 'DiasImportacion')

analizar_nulos(df, 'DiasImportacion')

"""# **Guardar Dataset**"""

output_path = '/content/drive/MyDrive/Trabajo de Grado JuanPablo/Datasets/Dataset_cleaned1.csv'
df.to_csv(output_path, index=False, sep=';')
print(f"El dataset limpio ha sido guardado exitosamente en: {output_path}")