# -*- coding: utf-8 -*-
"""02_seleccion_productos_final.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-wAImV6aEn5fkmJrauH9G0RIJwpgEBKM

## Configuracion
"""

# Commented out IPython magic to ensure Python compatibility.
# # versiones
# %%writefile requirements.txt
# pandas==2.2.2
# matplotlib==3.10.0
# seaborn==0.13.2

# instalar versiones de librerias
# !pip install -r requirements.txt

def analizar_nulos(df, columna):
    """
    Analiza la cantidad y porcentaje de valores nulos en una columna.

    Parámetros:
    - df: DataFrame
    - columna: nombre de la columna (str)
    """

    total_registros = len(df)
    cantidad_nulos = df[columna].isnull().sum()
    porcentaje_nulos = (cantidad_nulos / total_registros) * 100

    print("\n" + "="*50)
    print(f" VALORES NULOS - {columna.upper()}")
    print("="*50)
    print(f"Cantidad de valores nulos: {cantidad_nulos:,}")
    print(f"Porcentaje de nulos: {porcentaje_nulos:.2f}%")

def analizar_valores_unicos(df, columna, max_mostrar=20):
    """
    Muestra los valores únicos de una columna y su cantidad.

    Parámetros:
    - df: DataFrame
    - columna: nombre de la columna (str)
    - max_mostrar: número máximo de valores únicos a mostrar
    """

    valores_unicos = df[columna].unique()
    cantidad_unicos = len(valores_unicos)

    print("\n" + "="*50)
    print(f" VALORES ÚNICOS - {columna.upper()}")
    print("="*50)
    print(f"Cantidad de valores únicos: {cantidad_unicos:,}")

    print(f"\nPrimeros {min(max_mostrar, cantidad_unicos)} valores:")
    print(valores_unicos[:max_mostrar])

def eliminar_nulos_por_columna(df, columna, inplace=False):
    """
    Elimina los registros (filas) donde una columna específica tiene valores nulos.

    Parámetros:
    - df: DataFrame
    - columna: nombre de la columna (str)
    - inplace: si True, modifica el DataFrame original

    Retorna:
    - DataFrame limpio (si inplace=False)
    """

    total_antes = len(df)
    nulos = df[columna].isnull().sum()

    print("\n" + "="*50)
    print(f" ELIMINACIÓN DE NULOS - {columna.upper()}")
    print("="*50)
    print(f"Registros antes: {total_antes:,}")
    print(f"Registros con nulos en '{columna}': {nulos:,}")

    if inplace:
        df.dropna(subset=[columna], inplace=True)
        total_despues = len(df)
        print(f"Registros después: {total_despues:,}")
        print(f"Filas eliminadas: {total_antes - total_despues:,}")
    else:
        df_limpio = df.dropna(subset=[columna])
        total_despues = len(df_limpio)
        print(f"Filas eliminadas: {total_antes - total_despues:,}")
        return df_limpio

# Librerias
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from enum import unique
import matplotlib.dates as mdates

"""## Carga del Dataset"""

# Drive
from google.colab import drive
drive.mount('/content/drive')

# Visualizar dataset
df = pd.read_csv('/content/drive/MyDrive/Trabajo de Grado JuanPablo/Datasets/Dataset_cleaned1.csv', sep=';', on_bad_lines='skip')

df['FECHA'] = pd.to_datetime(df['FECHA'])

fecha_inicial = df['FECHA'].min()
fecha_final = df['FECHA'].max()

print(f"Fecha inicial del dataset: {fecha_inicial.strftime('%Y-%m-%d')}")
print(f"Fecha final del dataset: {fecha_final.strftime('%Y-%m-%d')}")

# Cantidad de filas y columnas
df.shape

# Transformación de variables
df['FECHA'] = pd.to_datetime(df['FECHA'], errors='coerce')
df['Bodega'] = df['Bodega'].astype('category')
df['Producto'] = df['Producto'].astype('category')
df['ClaseProducto'] = df['ClaseProducto'].astype('category')
df['TipoProducto'] = df['TipoProducto'].astype('category')
df['Cliente'] = df['Cliente'].astype('category')
df['Municipio'] = df['Municipio'].astype('category')
df['Departamento'] = df['Departamento'].astype('category')
df['IDFactura'] = df['IDFactura'].astype('int64')

# Limpieza segura para columnas numéricas que podrían venir como string
for col in ['Facturado', 'BackOrder', 'CantidadObsequio']:
    if df[col].dtype == 'object':
        df[col] = df[col].str.replace(',', '.').astype(float).fillna(0).astype('int64')
    else:
        df[col] = df[col].fillna(0).astype('int64')

df['ClaseVenta'] = df['ClaseVenta'].astype('category')
df['ProductoObsequio'] = df['ProductoObsequio'].astype('category')

# Tipo de variable
df.info()

# Dataset transformado
df.head()

"""# **Selección de Productos**"""

df_importados = df[df['FlagImportado'] == 1].copy()

print(f"Cantidad de productos importados: {df_importados['IDProducto'].nunique():,}")

# Ventas por producto y porcentaje sobre el total
df_pareto = (
    df_importados.groupby('Producto')['VentaTotal']
    .sum()
    .sort_values(ascending=False)
    .to_frame(name='VentaTotal')
)

# Porcentaje de participación
df_pareto['PorcentajeVentaTotal'] = (
    df_pareto['VentaTotal'] / df_pareto['VentaTotal'].sum() * 100
)

# Porcentaje acumulado
df_pareto['PorcentajeAcumulado'] = (
    df_pareto['PorcentajeVentaTotal'].cumsum()
)

# Productos que generan hasta el 80% de las ventas
productos_pareto = df_pareto[df_pareto['PorcentajeAcumulado'] <= 80].copy()

# Función para formatear números
def formato_miles(valor):
    if valor >= 1_000_000:
        return f"{valor/1_000_000:.1f} M"
    elif valor >= 1_000:
        return f"{valor/1_000:.1f} K"
    return f"{valor:,.0f}"

# Columna visual
productos_pareto['VentaTotal_Formato'] = (
    productos_pareto['VentaTotal'].apply(formato_miles)
)

print(f"Productos que representan el 80% de las ventas: {len(productos_pareto)}")

display(
    productos_pareto[
        ['VentaTotal_Formato', 'PorcentajeVentaTotal', 'PorcentajeAcumulado']
    ]
)

print(
    f"Estos productos representan el "
    f"{productos_pareto['PorcentajeVentaTotal'].sum():.2f}% "
    f"de las ventas totales."
)

import pandas as pd

# El DataFrame 'productos_pareto' ya está disponible de celdas anteriores.
# Está indexado por el nombre del producto.

# Definir las marcas a clasificar (el usuario incluyó 'kauldal', lo corregimos a 'kaudal')
brands_to_analyze = ['CORONEL', 'KAUDAL', 'VIGOR', 'LOGIPAINT']

# Inicializar un diccionario para almacenar los recuentos para cada marca y la categoría 'OTROS'
product_counts = {brand: 0 for brand in brands_to_analyze}
product_counts['OTROS'] = 0

# Total de productos en la lista Pareto para calcular proporciones
total_pareto_products = len(productos_pareto)

print("\n" + "="*80)
print("PROPORCIÓN DE PRODUCTOS POR LÍNEA DE MARCA EN LA LISTA PARETO")
print("="*80)

# Iterar sobre los productos en 'productos_pareto'
for product_name in productos_pareto.index:
    classified = False
    for brand in brands_to_analyze:
        if brand.lower() in product_name.lower():
            product_counts[brand] += 1
            classified = True
            break

    if not classified:
        product_counts['OTROS'] += 1

# Convertir los recuentos a un DataFrame para calcular proporciones
df_proportions = pd.DataFrame(
    list(product_counts.items()),
    columns=['Línea', 'Cantidad de Productos']
)

# Calcular la proporción en porcentaje
df_proportions['Proporción (%)'] = (df_proportions['Cantidad de Productos'] / total_pareto_products) * 100

# Ordenar por proporción descendente
df_proportions = df_proportions.sort_values(by='Proporción (%)', ascending=False).reset_index(drop=True)

# Mostrar los resultados
display(df_proportions)

print(f"\nTotal de productos analizados de la lista Pareto: {total_pareto_products}")
print("="*80)

import pandas as pd
import numpy as np

# Ensure 'Facturado' and 'BackOrder' are numeric in df_importados
# This step ensures df_importados has these columns in numeric format
# as df_importados is a copy of df and df should already have these converted.
# However, for robustness, we re-verify and convert if necessary.
if not pd.api.types.is_numeric_dtype(df_importados['Facturado']):
    df_importados['Facturado'] = pd.to_numeric(df_importados['Facturado'], errors='coerce').fillna(0).astype('int64')
if not pd.api.types.is_numeric_dtype(df_importados['BackOrder']):
    df_importados['BackOrder'] = pd.to_numeric(df_importados['BackOrder'], errors='coerce').fillna(0).astype('int64')

# Generar la nueva variable 'demanda_observada' para df_importados
df_importados['demanda_observada'] = df_importados['Facturado'] + df_importados['BackOrder']

# --- ABC: por VentaTotal--
venta_por_producto = df_importados.groupby('Producto', observed=False)['VentaTotal'].sum().sort_values(ascending=False)
venta_pct = venta_por_producto / venta_por_producto.sum() * 100
venta_acum = venta_pct.cumsum()

def clasif_abc(acum):
   if acum <= 80:
       return 'A'
   elif acum <= 95:
       return 'B'
   else:
       return 'C'

abc = venta_acum.apply(clasif_abc)

# --- XYZ: por variabilidad de la demanda semanal (incluye semanas sin venta = intermitencia) ---
# Asegurarse de que 'FECHA' es datetime en df_importados
if not pd.api.types.is_datetime64_any_dtype(df_importados['FECHA']):
    df_importados['FECHA'] = pd.to_datetime(df_importados['FECHA'], errors='coerce')

# Eliminar filas con fechas nulas que puedan haber surgido de la conversión
df_importados_cleaned_dates = df_importados.dropna(subset=['FECHA']).copy()

full_weeks = pd.date_range(df_importados_cleaned_dates['FECHA'].min(), df_importados_cleaned_dates['FECHA'].max(), freq='W')

weekly = (
   df_importados_cleaned_dates.groupby([pd.Grouper(key='FECHA', freq='W'), 'Producto'], observed=False)['demanda_observada']
   .sum()
   .unstack(fill_value=0)
)
weekly = weekly.reindex(full_weeks, fill_value=0)

mean_w = weekly.mean()
std_w = weekly.std()
cv = (std_w / mean_w).replace([np.inf, -np.inf], np.nan)

def clasif_xyz(c):
   if pd.isna(c):
       return 'Z'
   if c <= 0.5:
       return 'X'
   elif c <= 1.0:
       return 'Y'
   else:
       return 'Z'

xyz = cv.apply(clasif_xyz)

resumen = pd.DataFrame({
   'VentaTotal': venta_por_producto,
   'PctVenta': venta_pct,
   'PctAcum': venta_acum,
   'ABC': abc,
   'DemandaSemanalProm': mean_w,
   'CV': cv,
   'XYZ': xyz,
}).dropna(subset=['ABC'])

resumen['Clase'] = resumen['ABC'] + resumen['XYZ']
resumen = resumen.sort_values('VentaTotal', ascending=False)

# The original path `C:\Users\KEVING\Downloads\clasificacion_abc_xyz.csv` is a local Windows path.
# In Colab, we should save to the current directory or to Google Drive.
# I'll save it to the current directory for now. You can change this path if you need.
resumen.to_csv('clasificacion_abc_xyz.csv', sep=';')

import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd

# Ensure 'resumen' DataFrame is available from previous steps
if 'resumen' not in locals():
    print("Error: El DataFrame 'resumen' no está disponible. Por favor, ejecuta la celda de clasificación ABC-XYZ primero.")
else:
    # Extract ABC and XYZ categories from the 'Clase' column
    resumen['ABC_Clase'] = resumen['Clase'].str[0]
    resumen['XYZ_Clase'] = resumen['Clase'].str[1]

    # Count the occurrences of each combined class
    classification_counts = resumen.groupby(['ABC_Clase', 'XYZ_Clase']).size().unstack(fill_value=0)

    # Define the order for ABC and XYZ classes for better visualization
    abc_order = ['A', 'B', 'C']
    xyz_order = ['X', 'Y', 'Z']

    # Reindex to ensure all categories are present and in desired order
    classification_counts = classification_counts.reindex(index=abc_order, columns=xyz_order, fill_value=0)

    # Create the heatmap
    plt.figure(figsize=(8, 6))
    sns.heatmap(
        classification_counts,
        annot=True,     # Show the numerical values in each cell
        fmt='d',        # Format annotations as integers
        cmap='viridis', # Color map
        linewidths=.5,  # Lines between cells
        linecolor='black'
    )

    plt.title('Distribución de Productos por Clasificación ABC-XYZ', fontsize=16)
    plt.xlabel('Clase XYZ', fontsize=12)
    plt.ylabel('Clase ABC', fontsize=12)
    plt.xticks(rotation=0)
    plt.yticks(rotation=0)
    plt.tight_layout()
    plt.show()

    # Also display the counts in a table for clarity
    print("\nRecuento de productos por clasificación ABC-XYZ:")
    display(classification_counts)

# 1. Filtrar productos clasificados como 'AX' del DataFrame 'resumen'
productos_ax = resumen[resumen['Clase'] == 'AX'].copy()

# 2. Obtener los nombres de los productos que cumplen con el principio de Pareto
# (Estos ya están en el índice de `productos_pareto`)
productos_pareto_names = productos_pareto.index.tolist()

# 3. Filtrar los productos 'AX' que también están en la lista de Pareto
productos_ax_y_pareto = productos_ax[productos_ax.index.isin(productos_pareto_names)]

# 4. Seleccionar los primeros 20 productos de esta lista (ya está ordenada por VentaTotal descendente)
productos_seleccionados = productos_ax_y_pareto.head(20)

# 5. Guardar los productos seleccionados en un archivo CSV
file_name = 'ProductosSeleccionados.csv'
productos_seleccionados.to_csv(file_name, sep=';', index=True)

print(f"Se han seleccionado los primeros 20 productos de la clase 'AX' que coinciden con la ley de Pareto.")
print(f"Estos productos se han guardado en '{file_name}'.")

print("\nPrimeros 5 productos seleccionados:")
display(productos_seleccionados.head())

import pandas as pd

# Ensure 'productos_seleccionados' DataFrame is available
if 'productos_seleccionados' not in locals() or productos_seleccionados.empty:
    print("Error: El DataFrame 'productos_seleccionados' no está disponible o está vacío.")
    print("Por favor, ejecuta la celda anterior que genera este DataFrame.")
else:
    # Define the brands to analyze, using the same set as before
    brands_to_analyze = ['CORONEL', 'KAUDAL', 'VIGOR', 'LOGIPAINT']

    # Initialize a dictionary to store the counts for each brand and 'OTROS'
    selected_product_counts = {brand: 0 for brand in brands_to_analyze}
    selected_product_counts['OTROS'] = 0

    # Total number of products in the 'productos_seleccionados' list
    total_selected_products = len(productos_seleccionados)

    print("\n" + "="*80)
    print("PROPORCIÓN DE PRODUCTOS POR LÍNEA DE MARCA EN LOS TOP 20 'AX' (PARETO)")
    print("="*80)

    # Iterate over the products in 'productos_seleccionados'
    for product_name in productos_seleccionados.index:
        classified = False
        for brand in brands_to_analyze:
            if brand.lower() in product_name.lower():
                selected_product_counts[brand] += 1
                classified = True
                break

        if not classified:
            selected_product_counts['OTROS'] += 1

    # Convert the counts to a DataFrame to calculate proportions
    df_selected_proportions = pd.DataFrame(
        list(selected_product_counts.items()),
        columns=['Línea', 'Cantidad de Productos']
    )

    # Calculate the proportion in percentage
    if total_selected_products > 0:
        df_selected_proportions['Proporción (%)'] = (df_selected_proportions['Cantidad de Productos'] / total_selected_products) * 100
    else:
        df_selected_proportions['Proporción (%)'] = 0.0

    # Sort by proportion descending
    df_selected_proportions = df_selected_proportions.sort_values(by='Proporción (%)', ascending=False).reset_index(drop=True)

    # Display the results
    display(df_selected_proportions)

    print(f"\nTotal de productos analizados en la selección (Top 20 AX + Pareto): {total_selected_products}")
    print("="*80)

import matplotlib.pyplot as plt
import matplotlib.dates as mdates
import pandas as pd

# Asegurarse de que 'Facturado' y 'BackOrder' sean numéricos
# (Esto ya se hizo en celdas anteriores, pero se repite aquí para asegurar la independencia de la ejecución de esta celda)
if not pd.api.types.is_numeric_dtype(df['Facturado']):
    df['Facturado'] = pd.to_numeric(df['Facturado'], errors='coerce').fillna(0).astype('int64')
if not pd.api.types.is_numeric_dtype(df['BackOrder']):
    df['BackOrder'] = pd.to_numeric(df['BackOrder'], errors='coerce').fillna(0).astype('int64')

# Generar la nueva variable 'demanda_observada' (ObservedDemand)
df['demanda_observada'] = df['Facturado'] + df['BackOrder']

# Asegurarse de que 'FECHA' es datetime y 'demanda_observada' es numérica
df['FECHA'] = pd.to_datetime(df['FECHA'], errors='coerce')
# La verificación y conversión de demanda_observada ya no es necesaria aquí si se calcula justo antes.
# if not pd.api.types.is_numeric_dtype(df['demanda_observada']):
#     df['demanda_observada'] = pd.to_numeric(df['demanda_observada'], errors='coerce')

# Eliminar nulos en las columnas clave antes de procesar para evitar errores
df_cleaned = df.dropna(subset=['FECHA', 'demanda_observada', 'Producto']).copy()

# Los 'productos_seleccionados' ya contienen los top 20 'AX' Pareto
# Si no está definido, se cargaría desde el CSV (alternativa en caso de ejecución independiente)
if 'productos_seleccionados' not in locals():
    try:
        productos_seleccionados = pd.read_csv('ProductosSeleccionados.csv', sep=';', index_col='Producto')
    except FileNotFoundError:
        print("Error: 'ProductosSeleccionados.csv' no encontrado. Por favor, asegúrate de haber generado los productos seleccionados primero.")
        exit()

# Nombres de los 20 productos seleccionados
selected_product_names = productos_seleccionados.index.tolist()

# Filtrar el DataFrame principal para incluir solo estos 20 productos
df_top20_ax_pareto = df_cleaned[df_cleaned['Producto'].isin(selected_product_names)].copy()

# Definir las marcas a analizar (reutilizando la lógica anterior)
brands_to_analyze = ['CORONEL', 'KAUDAL', 'VIGOR', 'LOGIPAINT']

# Crear una nueva columna 'Marca_Agrupada' en df_top20_ax_pareto
def assign_brand(product_name):
    for brand in brands_to_analyze:
        if brand.lower() in product_name.lower():
            return brand
    return 'OTROS'

df_top20_ax_pareto['Marca_Agrupada'] = df_top20_ax_pareto['Producto'].apply(assign_brand)

print("Generando gráficos de demanda semanal para los top 20 productos 'AX' Pareto, separados por línea/marca...")

# Agrupar por semana y Marca_Agrupada, sumando la demanda_observada
weekly_demand_by_brand = df_top20_ax_pareto.groupby([pd.Grouper(key='FECHA', freq='W'), 'Marca_Agrupada'], observed=False)['demanda_observada'].sum().unstack(fill_value=0)

# Obtener todas las marcas que tienen datos en este subconjunto
actual_brands = weekly_demand_by_brand.columns.tolist()

# Generar un gráfico para cada marca
for brand_name in actual_brands:
    plt.figure(figsize=(15, 7))
    plt.plot(weekly_demand_by_brand.index, weekly_demand_by_brand[brand_name], marker='o', linestyle='-', markersize=4, label=f'Demanda Semanal - {brand_name}')

    plt.title(f'Demanda Semanal de Productos "AX" Pareto (Top 20) para la Marca: {brand_name}', fontsize=16)
    plt.xlabel('Fecha', fontsize=12)
    plt.ylabel('Demanda Observada (Unidades)', fontsize=12)
    plt.grid(True, linestyle='--', alpha=0.7)
    plt.xticks(rotation=45)
    plt.gca().xaxis.set_major_formatter(mdates.DateFormatter('%Y-%m-%d'))
    plt.tight_layout()
    plt.legend()
    plt.show()

print("Todos los gráficos de demanda semanal para los top 20 productos 'AX' Pareto han sido generados.")

import pandas as pd

# Path to save the file in Google Drive
drive_path = '/content/drive/MyDrive/Trabajo de Grado JuanPablo/Datasets/'
output_filename = 'productoseleccionados.csv'
full_output_path = drive_path + output_filename

# Ensure 'df_cleaned' and 'productos_seleccionados' are available
# (These DataFrames should be available from previous execution steps)
if 'df_cleaned' not in locals():
    print("Error: DataFrame 'df_cleaned' no encontrado. Asegúrate de ejecutar las celdas anteriores.")
    # Optionally, you might add code here to reload or recreate df_cleaned if it's critical
    # For this scenario, we assume it's loaded as per kernel state.
    exit()

if 'productos_seleccionados' not in locals():
    print("Error: DataFrame 'productos_seleccionados' no encontrado. Asegúrate de ejecutar las celdas anteriores.")
    # Attempt to load from the previously saved CSV if not in memory
    try:
        productos_seleccionados = pd.read_csv('ProductosSeleccionados.csv', sep=';', index_col='Producto')
    except FileNotFoundError:
        print("Error: 'ProductosSeleccionados.csv' no encontrado.")
        exit()

# 1. Get the list of selected product names from 'productos_seleccionados'
selected_product_names = productos_seleccionados.index.tolist()

# 2. Filter the original cleaned DataFrame ('df_cleaned') to include only these selected products
df_base_selected = df_cleaned[df_cleaned['Producto'].isin(selected_product_names)].copy()

# 3. Select the classification columns from 'productos_seleccionados' to merge.
#    We exclude 'VentaTotal' as df_cleaned already has a transaction-level 'VentaTotal'.
classification_cols = [
    'PctVenta', 'PctAcum', 'ABC', 'DemandaSemanalProm',
    'CV', 'XYZ', 'Clase', 'ABC_Clase', 'XYZ_Clase'
]
products_classification_info = productos_seleccionados[classification_cols]

# 4. Merge the filtered base DataFrame with the product classification information.
#    'left_on' is used for df_base_selected's 'Producto' column
#    'right_index' is used because productos_seleccionados is indexed by 'Producto'
#    'how=left' ensures all rows from df_base_selected are kept and new columns are added.
df_final_seleccionados = df_base_selected.merge(
    products_classification_info,
    left_on='Producto',
    right_index=True,
    how='left'
)

# 5. Save the new dataset to a CSV file in Google Drive
df_final_seleccionados.to_csv(full_output_path, sep=';', index=False)

print(f"Nuevo dataset 'productoseleccionados.csv' creado y guardado en '{full_output_path}'.")
print(f"Dimensiones del nuevo dataset: {df_final_seleccionados.shape}")
print("\nPrimeras 5 filas del nuevo dataset:")
display(df_final_seleccionados.head())

"""## **Selección de Productos Nacionales**"""

import pandas as pd

# Ensure 'df' is loaded and preprocessed from the original dataset
# This block is re-included for robustness against kernel resets or out-of-order execution

# Path to the dataset (assuming drive is already mounted from previous cells)
dataset_path = '/content/drive/MyDrive/Trabajo de Grado JuanPablo/Datasets/Dataset_cleaned1.csv'
df = pd.read_csv(dataset_path, sep=';', on_bad_lines='skip')

# Apply initial date conversion
df['FECHA'] = pd.to_datetime(df['FECHA'])

# Apply type transformations and numeric cleaning
df['FECHA'] = pd.to_datetime(df['FECHA'], errors='coerce')
df['Bodega'] = df['Bodega'].astype('category')
df['Producto'] = df['Producto'].astype('category')
df['ClaseProducto'] = df['ClaseProducto'].astype('category')
df['TipoProducto'] = df['TipoProducto'].astype('category')
df['Cliente'] = df['Cliente'].astype('category')
df['Municipio'] = df['Municipio'].astype('category')
df['Departamento'] = df['Departamento'].astype('category')
df['IDFactura'] = df['IDFactura'].astype('int64')

for col in ['Facturado', 'BackOrder', 'CantidadObsequio']:
    if df[col].dtype == 'object':
        df[col] = df[col].str.replace(',', '.').astype(float).fillna(0).astype('int64')
    else:
        df[col] = df[col].fillna(0).astype('int64')

df['ClaseVenta'] = df['ClaseVenta'].astype('category')
df['ProductoObsequio'] = df['ProductoObsequio'].astype('category')

# Filter for national products after 'df' is properly set up
df_nacionales = df[df['FlagImportado'] == 0].copy()

print(f"Cantidad de productos nacionales: {df_nacionales['IDProducto'].nunique():,}")

"""### Análisis de Pareto para Productos Nacionales"""

# Ventas por producto y porcentaje sobre el total para productos nacionales
df_pareto_nacionales = (
    df_nacionales.groupby('Producto')['VentaTotal']
    .sum()
    .sort_values(ascending=False)
    .to_frame(name='VentaTotal')
)

# Porcentaje de participación
df_pareto_nacionales['PorcentajeVentaTotal'] = (
    df_pareto_nacionales['VentaTotal'] / df_pareto_nacionales['VentaTotal'].sum() * 100
)

# Porcentaje acumulado
df_pareto_nacionales['PorcentajeAcumulado'] = (
    df_pareto_nacionales['PorcentajeVentaTotal'].cumsum()
)

# Productos que generan hasta el 80% de las ventas
productos_pareto_nacionales = df_pareto_nacionales[df_pareto_nacionales['PorcentajeAcumulado'] <= 80].copy()

# Función para formatear números (ya definida en una celda anterior, pero la incluyo para que esta celda sea autónoma si es necesario)
def formato_miles(valor):
    if valor >= 1_000_000:
        return f"{valor/1_000_000:.1f} M"
    elif valor >= 1_000:
        return f"{valor/1_000:.1f} K"
    return f"{valor:,.0f}"

# Columna visual
productos_pareto_nacionales['VentaTotal_Formato'] = (
    productos_pareto_nacionales['VentaTotal'].apply(formato_miles)
)

print(f"Productos nacionales que representan el 80% de las ventas: {len(productos_pareto_nacionales)}")

display(
    productos_pareto_nacionales[
        ['VentaTotal_Formato', 'PorcentajeVentaTotal', 'PorcentajeAcumulado']
    ]
)

print(
    f"Estos productos nacionales representan el "
    f"{productos_pareto_nacionales['PorcentajeVentaTotal'].sum():.2f}% "
    f"de las ventas totales."
)

"""### Clasificación ABC-XYZ para Productos Nacionales"""

import pandas as pd
import numpy as np

# Generar la nueva variable 'demanda_observada' para df_nacionales
df_nacionales['demanda_observada'] = df_nacionales['Facturado'] + df_nacionales['BackOrder']

# --- ABC: por VentaTotal--
venta_por_producto_nacionales = df_nacionales.groupby('Producto', observed=False)['VentaTotal'].sum().sort_values(ascending=False)
venta_pct_nacionales = venta_por_producto_nacionales / venta_por_producto_nacionales.sum() * 100
venta_acum_nacionales = venta_pct_nacionales.cumsum()

def clasif_abc(acum):
   if acum <= 80:
       return 'A'
   elif acum <= 95:
       return 'B'
   else:
       return 'C'

abc_nacionales = venta_acum_nacionales.apply(clasif_abc)

# --- XYZ: por variabilidad de la demanda semanal (incluye semanas sin venta = intermitencia) ---
# Asegurarse de que 'FECHA' es datetime en df_nacionales
if not pd.api.types.is_datetime64_any_dtype(df_nacionales['FECHA']):
    df_nacionales['FECHA'] = pd.to_datetime(df_nacionales['FECHA'], errors='coerce')

# Eliminar filas con fechas nulas que puedan haber surgido de la conversión
df_nacionales_cleaned_dates = df_nacionales.dropna(subset=['FECHA']).copy()

full_weeks_nacionales = pd.date_range(df_nacionales_cleaned_dates['FECHA'].min(), df_nacionales_cleaned_dates['FECHA'].max(), freq='W')

weekly_nacionales = (
   df_nacionales_cleaned_dates.groupby([pd.Grouper(key='FECHA', freq='W'), 'Producto'], observed=False)['demanda_observada']
   .sum()
   .unstack(fill_value=0)
)
weekly_nacionales = weekly_nacionales.reindex(full_weeks_nacionales, fill_value=0)

mean_w_nacionales = weekly_nacionales.mean()
std_w_nacionales = weekly_nacionales.std()
cv_nacionales = (std_w_nacionales / mean_w_nacionales).replace([np.inf, -np.inf], np.nan)

def clasif_xyz(c):
   if pd.isna(c):
       return 'Z'
   if c <= 0.5:
       return 'X'
   elif c <= 1.0:
       return 'Y'
   else:
       return 'Z'

xyz_nacionales = cv_nacionales.apply(clasif_xyz)

resumen_nacionales = pd.DataFrame({
   'VentaTotal': venta_por_producto_nacionales,
   'PctVenta': venta_pct_nacionales,
   'PctAcum': venta_acum_nacionales,
   'ABC': abc_nacionales,
   'DemandaSemanalProm': mean_w_nacionales,
   'CV': cv_nacionales,
   'XYZ': xyz_nacionales,
}).dropna(subset=['ABC'])

resumen_nacionales['Clase'] = resumen_nacionales['ABC'] + resumen_nacionales['XYZ']
resumen_nacionales = resumen_nacionales.sort_values('VentaTotal', ascending=False)

# Save to a new CSV file
resumen_nacionales.to_csv('clasificacion_abc_xyz_nacionales.csv', sep=';')

print("Clasificación ABC-XYZ para productos nacionales generada y guardada en 'clasificacion_abc_xyz_nacionales.csv'.")
display(resumen_nacionales.head())

"""### Visualización de Clasificación ABC-XYZ para Productos Nacionales"""

import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd

# Ensure 'resumen_nacionales' DataFrame is available
if 'resumen_nacionales' not in locals():
    print("Error: El DataFrame 'resumen_nacionales' no está disponible. Por favor, ejecuta la celda de clasificación ABC-XYZ para productos nacionales primero.")
else:
    # Extract ABC and XYZ categories from the 'Clase' column
    resumen_nacionales['ABC_Clase'] = resumen_nacionales['Clase'].str[0]
    resumen_nacionales['XYZ_Clase'] = resumen_nacionales['Clase'].str[1]

    # Count the occurrences of each combined class
    classification_counts_nacionales = resumen_nacionales.groupby(['ABC_Clase', 'XYZ_Clase']).size().unstack(fill_value=0)

    # Define the order for ABC and XYZ classes for better visualization
    abc_order = ['A', 'B', 'C']
    xyz_order = ['X', 'Y', 'Z']

    # Reindex to ensure all categories are present and in desired order
    classification_counts_nacionales = classification_counts_nacionales.reindex(index=abc_order, columns=xyz_order, fill_value=0)

    # Create the heatmap
    plt.figure(figsize=(8, 6))
    sns.heatmap(
        classification_counts_nacionales,
        annot=True,     # Show the numerical values in each cell
        fmt='d',        # Format annotations as integers
        cmap='viridis', # Color map
        linewidths=.5,  # Lines between cells
        linecolor='black'
    )

    plt.title('Distribución de Productos Nacionales por Clasificación ABC-XYZ', fontsize=16)
    plt.xlabel('Clase XYZ', fontsize=12)
    plt.ylabel('Clase ABC', fontsize=12)
    plt.xticks(rotation=0)
    plt.yticks(rotation=0)
    plt.tight_layout()
    plt.show()

    # Also display the counts in a table for clarity
    print("\nRecuento de productos nacionales por clasificación ABC-XYZ:")
    display(classification_counts_nacionales)

"""### Selección de Top 20 Productos 'AX' Nacionales (Principios de Pareto y ABC-XYZ)"""

# 1. Filtrar productos clasificados como 'AX' del DataFrame 'resumen_nacionales'
productos_ax_nacionales = resumen_nacionales[resumen_nacionales['Clase'] == 'AX'].copy()

# 2. Obtener los nombres de los productos nacionales que cumplen con el principio de Pareto
productos_pareto_nacionales_names = productos_pareto_nacionales.index.tolist()

# 3. Filtrar los productos 'AX' nacionales que también están en la lista de Pareto nacional
productos_ax_y_pareto_nacionales = productos_ax_nacionales[productos_ax_nacionales.index.isin(productos_pareto_nacionales_names)]

# 4. Seleccionar los primeros 20 productos de esta lista (ya está ordenada por VentaTotal descendente)
productos_seleccionados_nacionales = productos_ax_y_pareto_nacionales.head(20)

# 5. Guardar los productos seleccionados en un archivo CSV
file_name_nacionales = 'ProductosSeleccionados_Nacionales.csv'
productos_seleccionados_nacionales.to_csv(file_name_nacionales, sep=';', index=True)

print(f"Se han seleccionado los primeros 20 productos nacionales de la clase 'AX' que coinciden con la ley de Pareto.")
print(f"Estos productos se han guardado en '{file_name_nacionales}'.")

print("\nPrimeros 5 productos nacionales seleccionados:")
display(productos_seleccionados_nacionales.head())

"""### Distribución de Marcas en los Top 20 'AX' Nacionales (Pareto)"""

import pandas as pd

# Ensure 'productos_seleccionados_nacionales' DataFrame is available
if 'productos_seleccionados_nacionales' not in locals() or productos_seleccionados_nacionales.empty:
    print("Error: El DataFrame 'productos_seleccionados_nacionales' no está disponible o está vacío.")
    print("Por favor, ejecuta la celda anterior que genera este DataFrame.")
else:
    # Define the brands to analyze (you might want to adjust these for national products)
    brands_to_analyze_nacionales = ['CORONA', 'GRIVAL', 'PAVCO', 'CIPLAS'] # Example brands for national products

    # Initialize a dictionary to store the counts for each brand and 'OTROS'
    selected_product_counts_nacionales = {brand: 0 for brand in brands_to_analyze_nacionales}
    selected_product_counts_nacionales['OTROS'] = 0

    # Total number of products in the 'productos_seleccionados_nacionales' list
    total_selected_products_nacionales = len(productos_seleccionados_nacionales)

    print("\n" + "="*80)
    print("PROPORCIÓN DE PRODUCTOS POR LÍNEA DE MARCA EN LOS TOP 20 'AX' NACIONALES (PARETO)")
    print("="*80)

    # Iterate over the products in 'productos_seleccionados_nacionales'
    for product_name in productos_seleccionados_nacionales.index:
        classified = False
        for brand in brands_to_analyze_nacionales:
            if brand.lower() in product_name.lower():
                selected_product_counts_nacionales[brand] += 1
                classified = True
                break

        if not classified:
            selected_product_counts_nacionales['OTROS'] += 1

    # Convert the counts to a DataFrame to calculate proportions
    df_selected_proportions_nacionales = pd.DataFrame(
        list(selected_product_counts_nacionales.items()),
        columns=['Línea', 'Cantidad de Productos']
    )

    # Calculate the proportion in percentage
    if total_selected_products_nacionales > 0:
        df_selected_proportions_nacionales['Proporción (%)'] = (df_selected_proportions_nacionales['Cantidad de Productos'] / total_selected_products_nacionales) * 100
    else:
        df_selected_proportions_nacionales['Proporción (%)'] = 0.0

    # Sort by proportion descending
    df_selected_proportions_nacionales = df_selected_proportions_nacionales.sort_values(by='Proporción (%)', ascending=False).reset_index(drop=True)

    # Display the results
    display(df_selected_proportions_nacionales)

    print(f"\nTotal de productos analizados en la selección (Top 20 AX + Pareto Nacional): {total_selected_products_nacionales}")
    print("="*80)

"""### Visualización de Demanda Semanal de Top 20 'AX' Nacionales por Marca"""

import matplotlib.pyplot as plt
import matplotlib.dates as mdates
import pandas as pd

# Asegurarse de que 'df_nacionales' y 'productos_seleccionados_nacionales' estén disponibles
# (Estos DataFrames deberían estar disponibles de pasos de ejecución anteriores)
if 'df_nacionales' not in locals():
    print("Error: DataFrame 'df_nacionales' no encontrado. Asegúrate de ejecutar las celdas anteriores.")
    exit()

if 'productos_seleccionados_nacionales' not in locals():
    print("Error: DataFrame 'productos_seleccionados_nacionales' no encontrado. Asegúrate de ejecutar las celdas anteriores.")
    try:
        productos_seleccionados_nacionales = pd.read_csv('ProductosSeleccionados_Nacionales.csv', sep=';', index_col='Producto')
    except FileNotFoundError:
        print("Error: 'ProductosSeleccionados_Nacionales.csv' no encontrado.")
        exit()

# Nombres de los 20 productos nacionales seleccionados
selected_product_names_nacionales = productos_seleccionados_nacionales.index.tolist()

# Filtrar el DataFrame principal (nacional) para incluir solo estos 20 productos
df_top20_ax_pareto_nacionales = df_nacionales[df_nacionales['Producto'].isin(selected_product_names_nacionales)].copy()

# Definir las marcas a analizar (usar las mismas que en el análisis de proporción anterior)
brands_to_analyze_nacionales = ['CORONA', 'GRIVAL', 'PAVCO', 'CIPLAS']

# Crear una nueva columna 'Marca_Agrupada' en df_top20_ax_pareto_nacionales
def assign_brand_nacionales(product_name):
    for brand in brands_to_analyze_nacionales:
        if brand.lower() in product_name.lower():
            return brand
    return 'OTROS'

df_top20_ax_pareto_nacionales['Marca_Agrupada'] = df_top20_ax_pareto_nacionales['Producto'].apply(assign_brand_nacionales)

print("Generando gráficos de demanda semanal para los top 20 productos 'AX' Nacionales Pareto, separados por línea/marca...")

# Agrupar por semana y Marca_Agrupada, sumando la demanda_observada
weekly_demand_by_brand_nacionales = df_top20_ax_pareto_nacionales.groupby([pd.Grouper(key='FECHA', freq='W'), 'Marca_Agrupada'], observed=False)['demanda_observada'].sum().unstack(fill_value=0)

# Obtener todas las marcas que tienen datos en este subconjunto
actual_brands_nacionales = weekly_demand_by_brand_nacionales.columns.tolist()

# Generar un gráfico para cada marca
for brand_name in actual_brands_nacionales:
    plt.figure(figsize=(15, 7))
    plt.plot(weekly_demand_by_brand_nacionales.index, weekly_demand_by_brand_nacionales[brand_name], marker='o', linestyle='-', markersize=4, label=f'Demanda Semanal - {brand_name}')

    plt.title(f'Demanda Semanal de Productos Nacionales "AX" Pareto (Top 20) para la Marca: {brand_name}', fontsize=16)
    plt.xlabel('Fecha', fontsize=12)
    plt.ylabel('Demanda Observada (Unidades)', fontsize=12)
    plt.grid(True, linestyle='--', alpha=0.7)
    plt.xticks(rotation=45)
    plt.gca().xaxis.set_major_formatter(mdates.DateFormatter('%Y-%m-%d'))
    plt.tight_layout()
    plt.legend()
    plt.show()

print("Todos los gráficos de demanda semanal para los top 20 productos 'AX' Nacionales Pareto han sido generados.")

"""### Creación y Guardado del Dataset Final de Productos Nacionales Seleccionados"""

import pandas as pd

# Path to save the file in Google Drive
drive_path = '/content/drive/MyDrive/Trabajo de Grado JuanPablo/Datasets/'
output_filename_nacionales = 'productoseleccionados_nacionales.csv'
full_output_path_nacionales = drive_path + output_filename_nacionales

# Ensure 'df_nacionales' and 'productos_seleccionados_nacionales' are available
if 'df_nacionales' not in locals():
    print("Error: DataFrame 'df_nacionales' no encontrado. Asegúrate de ejecutar las celdas anteriores.")
    exit()

if 'productos_seleccionados_nacionales' not in locals():
    print("Error: DataFrame 'productos_seleccionados_nacionales' no encontrado. Asegúrate de ejecutar las celdas anteriores.")
    try:
        productos_seleccionados_nacionales = pd.read_csv('ProductosSeleccionados_Nacionales.csv', sep=';', index_col='Producto')
    except FileNotFoundError:
        print("Error: 'ProductosSeleccionados_Nacionales.csv' no encontrado.")
        exit()

# 1. Get the list of selected product names from 'productos_seleccionados_nacionales'
selected_product_names_nacionales = productos_seleccionados_nacionales.index.tolist()

# 2. Filter the original national DataFrame ('df_nacionales') to include only these selected products
df_base_selected_nacionales = df_nacionales[df_nacionales['Producto'].isin(selected_product_names_nacionales)].copy()

# 3. Select the classification columns from 'resumen_nacionales' to merge.
#    We exclude 'VentaTotal' as df_nacionales already has a transaction-level 'VentaTotal'.
classification_cols = [
    'PctVenta', 'PctAcum', 'ABC', 'DemandaSemanalProm',
    'CV', 'XYZ', 'Clase', 'ABC_Clase', 'XYZ_Clase'
]
products_classification_info_nacionales = resumen_nacionales[classification_cols]

# 4. Merge the filtered base DataFrame with the product classification information.
#    'left_on' is used for df_base_selected_nacionales's 'Producto' column
#    'right_index' is used because resumen_nacionales is indexed by 'Producto'
#    'how=left' ensures all rows from df_base_selected_nacionales are kept and new columns are added.
df_final_seleccionados_nacionales = df_base_selected_nacionales.merge(
    products_classification_info_nacionales,
    left_on='Producto',
    right_index=True,
    how='left'
)

# 5. Save the new dataset to a CSV file in Google Drive
df_final_seleccionados_nacionales.to_csv(full_output_path_nacionales, sep=';', index=False)

print(f"Nuevo dataset 'productoseleccionados_nacionales.csv' creado y guardado en '{full_output_path_nacionales}'.")
print(f"Dimensiones del nuevo dataset: {df_final_seleccionados_nacionales.shape}")
print("\nPrimeras 5 filas del nuevo dataset:")
display(df_final_seleccionados_nacionales.head())

if 'df' in locals():
    unique_products = df['Producto'].unique().tolist()
    print(f"Total de productos únicos: {len(unique_products)}")
    for product in unique_products:
        print(f"- {product}")
else:
    print("El DataFrame 'df' no está disponible. Por favor, asegúrate de haber cargado el dataset primero.")