# -*- coding: utf-8 -*-
"""03_preprocesamiento.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Fdk4SvqQNup2S6zjle4ktqhz-RSU56ge

## Configuracion
"""

# Commented out IPython magic to ensure Python compatibility.
# # versiones
# %%writefile requirements.txt
# pandas==2.2.2
# matplotlib==3.10.0
# seaborn==0.13.2

# instalar versiones de librerias
# !pip install -r requirements.txt

# Librerias
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from enum import unique
import matplotlib.dates as mdates

"""## Carga del Dataset"""

# Drive
from google.colab import drive
drive.mount('/content/drive')

# Visualizar dataset
df = pd.read_csv('/content/drive/MyDrive/Trabajo de Grado JuanPablo/Datasets/productoseleccionados.csv', sep=';', on_bad_lines='skip')

df['FECHA'] = pd.to_datetime(df['FECHA'])

fecha_inicial = df['FECHA'].min()
fecha_final = df['FECHA'].max()

print(f"Fecha inicial del dataset: {fecha_inicial.strftime('%Y-%m-%d')}")
print(f"Fecha final del dataset: {fecha_final.strftime('%Y-%m-%d')}")

# Cantidad de filas y columnas
df.shape

"""# **Análisis Exploratorio de los Productos Seleccionados**"""

import matplotlib.pyplot as plt
import matplotlib.dates as mdates
import pandas as pd

# Asegurarse de que 'FECHA' sea datetime y establecerla como índice temporal para el resampling.
# También es importante que 'Facturado' sea numérico.
df['FECHA'] = pd.to_datetime(df['FECHA'], errors='coerce')
# Ensure 'Facturado' is numeric, if not already.
if not pd.api.types.is_numeric_dtype(df['Facturado']):
    df['Facturado'] = pd.to_numeric(df['Facturado'], errors='coerce')

df_filtered_products = df.dropna(subset=['FECHA', 'Facturado'])

# Definir las marcas a analizar, usando las que ya se clasificaron previamente
brands_to_analyze = ['CORONEL', 'KAUDAL', 'VIGOR', 'LOGIPAINT']

# Diccionario para almacenar los productos clasificados por marca y 'OTROS'
products_by_brand = {brand: [] for brand in brands_to_analyze}
products_by_brand['OTROS'] = []

# Volver a clasificar los productos del DataFrame principal en función de las marcas
# para asegurarnos de que cubrimos todos los productos relevantes en df.
# Fix: Filter out NaN values from 'Producto' column before getting unique values
for product_name in df_filtered_products['Producto'].dropna().unique():
    classified = False
    for brand in brands_to_analyze:
        if brand.lower() in product_name.lower(): # product_name is guaranteed to be a string here
            products_by_brand[brand].append(product_name)
            classified = True
            break
    if not classified:
        products_by_brand['OTROS'].append(product_name)


print("Generando gráficos de demanda semanal por línea de producto...")

# Iterar sobre cada línea (marca) para generar su gráfico de demanda semanal
for brand_name, product_list in products_by_brand.items():
    if not product_list:
        print(f"No se encontraron productos para la línea: {brand_name}. Saltando el gráfico.")
        continue

    # Filtrar el DataFrame para los productos de la línea actual
    df_brand_products = df_filtered_products[df_filtered_products['Producto'].isin(product_list)].copy()

    # Agrupar por semana y sumar 'Facturado' para obtener la demanda semanal
    # Usamos 'origin='start'' para asegurar que la semana inicia consistentemente (ej., en domingo o lunes)
    # y 'on='FECHA'' para indicar la columna de tiempo.
    weekly_demand = df_brand_products.resample('W', on='FECHA').agg({
        'Facturado': 'sum'
    }).fillna(0)

    # Crear el gráfico
    plt.figure(figsize=(15, 7))
    plt.plot(weekly_demand.index, weekly_demand['Facturado'], marker='o', linestyle='-', markersize=4, label='Demanda Semanal')
    plt.title(f'Demanda Semanal de la Línea de Productos: {brand_name}', fontsize=16)
    plt.xlabel('Fecha', fontsize=12)
    plt.ylabel('Cantidad Facturada (Unidades)', fontsize=12)
    plt.grid(True, linestyle='--', alpha=0.7)
    plt.xticks(rotation=45)
    plt.gca().xaxis.set_major_formatter(mdates.DateFormatter('%Y-%m-%d'))
    plt.tight_layout()
    plt.legend()
    plt.show()

print("Todos los gráficos de demanda semanal por línea de producto han sido generados.")

import pandas as pd
import numpy as np

# Path to the new CSV provided by the user
file_path = '/content/drive/MyDrive/Trabajo de Grado JuanPablo/Datasets/Rangos Fechas Productos Sin Inventario.csv'
output_file_name = '/content/drive/MyDrive/Trabajo de Grado JuanPablo/Datasets/fechas sin inventario productos AX.csv'

# List of products to analyze (provided by the user)
products_to_analyze = [
    "SIFON ESCUALIZABLE KAUDAL DL-1231",
    "GUANTE NITRILO NEGRO TALLA 8 YES-8",
    "SPRAY COLOR ROJO LOGIPAINT RB23",
    "SPRAY COLOR ORO 18K PREMIUM LOGIPAINT RB ORO",
    "SPRAY COLOR NEGRO BRILLANTE LOGIPAINT RB39",
    "SIFON ESCUALIZABLE AQUAYEF KAUDAL PUSH LAVAMANOS DL-1351",
    "SIFON ESCUALIZABLE DOBLE KAUDAL DL-1455",
    "LLANA LISA MANGO MADERA VIGOR YES-1466",
    "VALVULA TANQUE COBRE 1/2 KAUDAL DL-1432",
    "GUANTE NITRILO NEGRO TALLA 10 YES-10",
    "SPRAY COLOR ALUMINIO LOGIPAINT RB36",
    "GUANTE NITRILO NEGRO TALLA 9 YES-9",
    "CINTA TEFLON PEQUEÑO DL-1608",
    "SPRAY COLOR BLANCO BRILLANTE LOGIPAINT RB40",
    "CINTA FILO METALICA X 30 MTS VIGOR DL-0986",
    "CINTA TEFLON INDUSTRIAL DL-1607",
    "SPRAY COLOR NEGRO MATE LOGIPAINT RB4",
    "SPRAY COLOR BLANCO MATE LOGIPAINT RB1007",
    "SPRAY COLOR CROMADO PREMIUM LOGIPAINT RB318",
    "SPRAY COLOR TRANSPARENTE BRILLANTE LOGIPAINT RB190"
]

try:
    # Load the new dataframe
    df_inventory = pd.read_csv(file_path, sep=';', on_bad_lines='skip')

    # Ensure 'FECHA' is datetime and handle potential errors
    df_inventory['FECHA'] = pd.to_datetime(df_inventory['FECHA'], errors='coerce')
    df_inventory.dropna(subset=['FECHA'], inplace=True)

    # Ensure 'Facturado' and 'BackOrder' are numeric, filling NaNs with 0 before conversion
    # to ensure they can be used for 'demanda_observada'
    if 'Facturado' in df_inventory.columns:
        df_inventory['Facturado'] = pd.to_numeric(df_inventory['Facturado'], errors='coerce').fillna(0)
    else:
        df_inventory['Facturado'] = 0 # Default to 0 if column is missing

    if 'BackOrder' in df_inventory.columns:
        df_inventory['BackOrder'] = pd.to_numeric(df_inventory['BackOrder'], errors='coerce').fillna(0)
    else:
        df_inventory['BackOrder'] = 0 # Default to 0 if column is missing

    # Create 'demanda_observada' column (proxy for inventory/sales activity)
    df_inventory['demanda_observada'] = df_inventory['Facturado'] + df_inventory['BackOrder']

    # Filter for the specified products
    df_filtered_products = df_inventory[df_inventory['Producto'].isin(products_to_analyze)].copy()

    if df_filtered_products.empty:
        print("No data found for the specified products in the provided CSV.")
    else:
        # Prepare a list to store results
        no_inventory_periods = []

        # Process each unique product from the filtered list
        for product_name in df_filtered_products['Producto'].unique():
            product_df = df_filtered_products[df_filtered_products['Producto'] == product_name].sort_values('FECHA')

            # Group by date and sum demand_observada for each day
            daily_demand = product_df.groupby('FECHA')['demanda_observada'].sum()

            # Reindex to fill missing dates with 0 demand to correctly identify continuous periods
            # Use the min and max date from the product's actual data to define the range
            if not daily_demand.empty:
                full_date_range = pd.date_range(start=daily_demand.index.min(), end=daily_demand.index.max())
                daily_demand = daily_demand.reindex(full_date_range, fill_value=0)
            else:
                continue # Skip if no demand data for the product

            # Identify periods of zero demand
            zero_demand_mask = (daily_demand == 0)

            # Find the start and end of consecutive zero-demand periods
            # Logic for grouping consecutive True values (zero demand)
            if not zero_demand_mask.empty:
                # Add a dummy True at the beginning and end to catch edge cases
                padded_mask = pd.Series([False], index=[daily_demand.index.min() - pd.Timedelta(days=1)]).append(zero_demand_mask).append(pd.Series([False], index=[daily_demand.index.max() + pd.Timedelta(days=1)]))

                # Identify where the mask changes from False to True (start of zero demand) or True to False (end)
                changes = padded_mask.astype(int).diff()

                starts = daily_demand.index[changes == 1].tolist()
                ends = daily_demand.index[changes == -1].tolist()

                # Match starts and ends, ensuring valid ranges
                for i in range(len(starts)):
                    start_date = starts[i]
                    end_date = ends[i] - pd.Timedelta(days=1) # The end date is the last day of zero demand

                    if start_date <= end_date: # Ensure the period is valid (start not after end)
                        no_inventory_periods.append({
                            'Producto': product_name,
                            'Fecha_Inicio_Sin_Inventario': start_date.strftime('%Y-%m-%d'),
                            'Fecha_Fin_Sin_Inventario': end_date.strftime('%Y-%m-%d')
                        })

        # Create a DataFrame from the results
        if no_inventory_periods:
            df_no_inventory = pd.DataFrame(no_inventory_periods)
            df_no_inventory.to_csv(output_file_name, index=False)
            print(f"Successfully saved 'no inventory' periods to: {output_file_name}")
            display(df_no_inventory.head())
        else:
            print("No periods of zero observed demand found for the specified products.")

except FileNotFoundError:
    print(f"Error: The file '{file_path}' was not found. Please check the path and try again.")
except Exception as e:
    print(f"An error occurred: {e}")

import matplotlib.pyplot as plt
import matplotlib.dates as mdates
import pandas as pd

# Asegurarse de que 'FECHA' sea datetime y establecerla como índice temporal para el resampling.
# También es importante que 'Facturado' y 'BackOrder' sean numéricos.
df['FECHA'] = pd.to_datetime(df['FECHA'], errors='coerce')

# Ensure 'Facturado' and 'BackOrder' are numeric, if not already.
if not pd.api.types.is_numeric_dtype(df['Facturado']):
    df['Facturado'] = pd.to_numeric(df['Facturado'], errors='coerce')
if not pd.api.types.is_numeric_dtype(df['BackOrder']):
    df['BackOrder'] = pd.to_numeric(df['BackOrder'], errors='coerce')

df_filtered_products = df.dropna(subset=['FECHA', 'Facturado', 'BackOrder']).copy()

# Definir las marcas a analizar, usando las que ya se clasificaron previamente
brands_to_analyze = ['CORONEL', 'KAUDAL', 'VIGOR', 'LOGIPAINT']

# Diccionario para almacenar los productos clasificados por marca y 'OTROS'
products_by_brand = {brand: [] for brand in brands_to_analyze}
products_by_brand['OTROS'] = []

# Volver a clasificar los productos del DataFrame principal en función de las marcas
# para asegurarnos de que cubrimos todos los productos relevantes en df.
for product_name in df_filtered_products['Producto'].dropna().unique():
    classified = False
    for brand in brands_to_analyze:
        if brand.lower() in product_name.lower():
            products_by_brand[brand].append(product_name)
            classified = True
            break
    if not classified:
        products_by_brand['OTROS'].append(product_name)


print("Generando gráficos de demanda semanal (Facturado + BackOrder) por línea de producto...")

# Iterar sobre cada línea (marca) para generar su gráfico de demanda semanal
for brand_name, product_list in products_by_brand.items():
    if not product_list:
        print(f"No se encontraron productos para la línea: {brand_name}. Saltando el gráfico.")
        continue

    # Filtrar el DataFrame para los productos de la línea actual
    df_brand_products = df_filtered_products[df_filtered_products['Producto'].isin(product_list)].copy()

    # Agrupar por semana y sumar 'Facturado' y 'BackOrder'
    weekly_data = df_brand_products.resample('W', on='FECHA').agg({
        'Facturado': 'sum',
        'BackOrder': 'sum'
    }).fillna(0) # Fill weeks with no data with 0

    # Calcular la Demanda Total
    weekly_data['TotalDemand'] = weekly_data['Facturado'] + weekly_data['BackOrder']

    # Crear el gráfico
    plt.figure(figsize=(15, 7))
    plt.plot(weekly_data.index, weekly_data['TotalDemand'], marker='o', linestyle='-', markersize=4, label='Demanda Total Semanal (Facturado + BackOrder)', color='blue')
    plt.plot(weekly_data.index, weekly_data['Facturado'], marker='x', linestyle='--', markersize=4, label='Facturado Semanal', color='skyblue')
    plt.plot(weekly_data.index, weekly_data['BackOrder'], marker='^', linestyle=':', markersize=4, label='BackOrder Semanal', color='orange')

    plt.title(f'Demanda Semanal (Facturado y BackOrder) de la Línea de Productos: {brand_name}', fontsize=16)
    plt.xlabel('Fecha', fontsize=12)
    plt.ylabel('Cantidad (Unidades)', fontsize=12)
    plt.grid(True, linestyle='--', alpha=0.7)
    plt.xticks(rotation=45)
    plt.gca().xaxis.set_major_formatter(mdates.DateFormatter('%Y-%m-%d'))
    plt.tight_layout()
    plt.legend()
    plt.show()

print("Todos los gráficos de demanda semanal (Facturado y BackOrder) por línea de producto han sido generados.")

# Asegurarse de que 'Facturado' y 'BackOrder' sean numéricos
# (Esto ya se hizo en celdas anteriores, pero se repite para mayor seguridad)
if not pd.api.types.is_numeric_dtype(df['Facturado']):
    df['Facturado'] = pd.to_numeric(df['Facturado'], errors='coerce').fillna(0).astype('int64')
if not pd.api.types.is_numeric_dtype(df['BackOrder']):
    df['BackOrder'] = pd.to_numeric(df['BackOrder'], errors='coerce').fillna(0).astype('int64')

# Generar la nueva variable 'demanda observada' (ObservedDemand)
df['demanda_observada'] = df['Facturado'] + df['BackOrder']

print("La columna 'demanda_observada' ha sido creada con éxito.")
print("Primeras 5 filas con la nueva columna:")
display(df[['Facturado', 'BackOrder', 'demanda_observada']].head())

"""### Demanda Observada Promedio por Bodega"""

import matplotlib.pyplot as plt
import seaborn as sns

# Calcular la demanda observada promedio por Bodega
demanda_promedio_bodega = df.groupby('Bodega', observed=False)['demanda_observada'].mean().sort_values(ascending=False)

print("\n" + "="*70)
print("DEMANDA OBSERVADA PROMEDIO POR BODEGA")
print("="*70)
display(demanda_promedio_bodega.to_frame())

# Visualización
plt.figure(figsize=(10, 6))
sns.barplot(x=demanda_promedio_bodega.index, y=demanda_promedio_bodega.values, palette='viridis', hue=demanda_promedio_bodega.index, legend=False)
plt.title('Demanda Observada Promedio por Bodega', fontsize=16)
plt.xlabel('Bodega', fontsize=12)
plt.ylabel('Demanda Observada Promedio (Unidades)', fontsize=12)
plt.xticks(rotation=45, ha='right')
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.tight_layout()
plt.show()

import matplotlib.pyplot as plt
import pandas as pd
import matplotlib.dates as mdates
from datetime import datetime, timedelta
import seaborn as sns

# Calculate productos_pareto here since it was not defined previously
# Assuming 'VentaTotal' is available in df based on previous cell execution (d105ed38)
if 'VentaTotal' not in df.columns:
    # This should ideally not happen if d105ed38 was executed
    # but as a fallback, ensure VentaTotal is calculated
    if not pd.api.types.is_numeric_dtype(df['VlrUnitario']):
        df['VlrUnitario'] = df['VlrUnitario'].astype(str).str.replace(',', '.', regex=False).astype(float)
    if not pd.api.types.is_numeric_dtype(df['Facturado']):
        df['Facturado'] = df['Facturado'].astype(str).str.replace(',', '.', regex=False).astype(float)
    df['VentaTotal'] = df['VlrUnitario'] * df['Facturado']

productos_pareto = df.groupby('Producto')['VentaTotal'].sum().sort_values(ascending=False)

# 1. Definir fechas de eventos especiales
special_events_raw = [
    {'event': 'Vacaciones', 'year': 2025, 'week': 1},
    {'event': 'Semana Santa', 'year': 2024, 'week': 13},
    {'event': 'Semana Santa', 'year': 2025, 'week': 16},
    {'event': 'Rueda de Negocios', 'year': 2025, 'week': 20},
    {'event': 'Feria', 'year': 2024, 'week': 37},
    {'event': 'Feria', 'year': 2025, 'week': 39},
]

special_event_dates = []
for event_info in special_events_raw:
    year = event_info['year']
    week_num = event_info['week']
    # Calcular la fecha del domingo (fin de semana) para la semana dada, asumiendo ISO week
    event_date_monday = pd.to_datetime(f'{year}-W{week_num}-1', format='%Y-W%W-%w')
    event_date_sunday = event_date_monday + timedelta(days=6) # Fin de la semana
    special_event_dates.append({'date': event_date_sunday, 'event': event_info['event']})

event_colors = {
    'Feria': 'purple',
    'Vacaciones': 'orange',
    'Rueda de Negocios': 'green',
    'Semana Santa': 'blue'
}

# 2. Obtener los nombres de los 10 productos principales del Pareto
top_10_products_names = productos_pareto.index[:10].tolist()

print(f"Generando gráficos de demanda observada semanal total por producto (todas las bodegas), incluyendo eventos y semanas sin demanda.")

# Asegurarse de que 'FECHA' sea datetime y 'demanda_observada' sea numérica
df['FECHA'] = pd.to_datetime(df['FECHA'], errors='coerce')
if not pd.api.types.is_numeric_dtype(df['demanda_observada']):
    df['demanda_observada'] = pd.to_numeric(df['demanda_observada'], errors='coerce')

# Eliminar nulos en las columnas clave antes de procesar para evitar errores
df_cleaned = df.dropna(subset=['FECHA', 'demanda_observada', 'Producto']).copy()

# 3. Iterar por cada uno de los 10 productos principales
for product_name in top_10_products_names:
    print(f"\nProcesando producto: {product_name}")

    # a. Filtrar el DataFrame para el producto actual
    product_df = df_cleaned[df_cleaned['Producto'] == product_name].copy()

    if product_df.empty:
        print(f"No hay datos para el producto '{product_name}'. Saltando.")
        continue

    # b. Calcular la demanda total del producto por semana (sumando todas las bodegas)
    total_weekly_product_demand = product_df.groupby(pd.Grouper(key='FECHA', freq='W'))['demanda_observada'].sum().fillna(0)

    if total_weekly_product_demand.empty:
        print(f"No hay demanda semanal para el producto '{product_name}' (todas las bodegas). Saltando.")
        continue

    # Identificar semanas con demanda cero para este producto en general
    zero_demand_weeks = total_weekly_product_demand[total_weekly_product_demand == 0].index.tolist()

    # c. Generar el gráfico
    plt.figure(figsize=(15, 7))

    # Listas para manejar la leyenda personalizada
    all_handles = []
    all_labels = []

    # Graficar la demanda total del producto (sumada de todas las bodegas)
    line, = plt.plot(total_weekly_product_demand.index, total_weekly_product_demand.values,
                     marker='o', linestyle='-', markersize=4, label='Demanda Total (Todas las Bodegas)')
    all_handles.append(line)
    all_labels.append('Demanda Total (Todas las Bodegas)')

    # Resaltar semanas sin demanda observada para el producto
    zero_demand_patch = None
    legend_label_added_zero_demand = False
    for week_start_date in zero_demand_weeks:
        week_end_date = week_start_date + pd.Timedelta(days=6)
        if not legend_label_added_zero_demand:
            zero_demand_patch = plt.axvspan(week_start_date, week_end_date, color='red', alpha=0.1, label='Semanas sin Demanda Observada')
            legend_label_added_zero_demand = True
        else:
            plt.axvspan(week_start_date, week_end_date, color='red', alpha=0.1)

    if zero_demand_patch:
        all_handles.append(plt.Rectangle((0, 0), 1, 1, fc='red', alpha=0.1))
        all_labels.append('Semanas sin Demanda Observada')

    # Añadir líneas verticales para eventos especiales
    events_added_to_legend = set()
    for event_data in special_event_dates:
        event_date = event_data['date']
        event_type = event_data['event']
        color = event_colors.get(event_type, 'gray')

        # Asegurarse de que la fecha del evento esté dentro del rango de las fechas graficadas
        if not total_weekly_product_demand.empty and \
           total_weekly_product_demand.index.min() <= event_date <= total_weekly_product_demand.index.max():

            if event_type not in events_added_to_legend:
                line = plt.axvline(x=event_date, color=color, linestyle='--', linewidth=2, label=f'{event_type}')
                all_handles.append(line)
                all_labels.append(f'{event_type}')
                events_added_to_legend.add(event_type)
            else:
                plt.axvline(x=event_date, color=color, linestyle='--', linewidth=2)

    plt.title(f'Demanda Observada Semanal Total de "{product_name}" (Todas las Bodegas) y Eventos', fontsize=16)
    plt.xlabel('Fecha', fontsize=12)
    plt.ylabel('Demanda Observada (Unidades)', fontsize=12)
    plt.grid(True, linestyle='--', alpha=0.7)
    plt.xticks(rotation=45)
    plt.gca().xaxis.set_major_formatter(mdates.DateFormatter('%Y-%m-%d'))

    # Crear la leyenda con todos los elementos
    plt.legend(all_handles, all_labels, title='Leyenda', loc='upper left', bbox_to_anchor=(1, 1))
    plt.tight_layout(rect=[0, 0, 0.85, 1]) # Ajustar el diseño para que la leyenda no se superponga
    plt.show()

print("\nTodos los gráficos de demanda observada semanal total por producto, con eventos y semanas sin demanda, han sido generados.")

import matplotlib.pyplot as plt
import pandas as pd
import matplotlib.dates as mdates
from datetime import timedelta
import seaborn as sns

# 1. Definir fechas de eventos especiales (reutilizando del análisis anterior)
special_events_raw = [
    {'event': 'Vacaciones', 'year': 2025, 'week': 1},
    {'event': 'Semana Santa', 'year': 2024, 'week': 13},
    {'event': 'Semana Santa', 'year': 2025, 'week': 16},
    {'event': 'Rueda de Negocios', 'year': 2025, 'week': 20},
    {'event': 'Feria', 'year': 2024, 'week': 37},
    {'event': 'Feria', 'year': 2025, 'week': 39},
]

special_event_dates = []
for event_info in special_events_raw:
    year = event_info['year']
    week_num = event_info['week']
    # Calcular la fecha del domingo (fin de semana) para la semana dada, asumiendo ISO week
    event_date_monday = pd.to_datetime(f'{year}-W{week_num}-1', format='%Y-W%W-%w')
    event_date_sunday = event_date_monday + timedelta(days=6) # Fin de la semana
    special_event_dates.append({'date': event_date_sunday, 'event': event_info['event']})

event_colors = {
    'Feria': 'purple',
    'Vacaciones': 'orange',
    'Rueda de Negocios': 'green',
    'Semana Santa': 'blue'
}

# Asegurarse de que 'FECHA' sea datetime y 'demanda_observada' sea numérica
df['FECHA'] = pd.to_datetime(df['FECHA'], errors='coerce')
if not pd.api.types.is_numeric_dtype(df['demanda_observada']):
    df['demanda_observada'] = pd.to_numeric(df['demanda_observada'], errors='coerce')

# Eliminar nulos en las columnas clave antes de procesar para evitar errores
df_cleaned = df.dropna(subset=['FECHA', 'demanda_observada', 'Departamento']).copy()

# 2. Categorizar Departamentos
def categorizar_departamento(departamento):
    if 'BOGOTA' in str(departamento).upper():
        return 'Bogota D.C.'
    elif 'CUNDINAMARCA' in str(departamento).upper():
        return 'CUNDINAMARCA'
    else:
        return 'RESTO DE DEPARTAMENTOS'

df_cleaned['Departamento_Agrupado'] = df_cleaned['Departamento'].apply(categorizar_departamento)

# 3. Calcular la demanda observada semanal por Departamento Agrupado
weekly_general_demand_by_dept = (
    df_cleaned.groupby([pd.Grouper(key='FECHA', freq='W'), 'Departamento_Agrupado'], observed=False)
    ['demanda_observada'].sum().unstack(fill_value=0)
)

# 4. Preparar para el plotting en una sola gráfica
plt.figure(figsize=(15, 7))
ax = plt.gca()

# Listas para manejar la leyenda personalizada
all_handles = []
all_labels = []

# Generar un color map para las líneas de departamento
colors = plt.cm.get_cmap('viridis', len(weekly_general_demand_by_dept.columns))

# Plotting Loop para cada Departamento Agrupado
for i, department_col in enumerate(weekly_general_demand_by_dept.columns):
    # Plot la demanda semanal del departamento
    line, = ax.plot(weekly_general_demand_by_dept.index, weekly_general_demand_by_dept[department_col],
             marker='o', linestyle='-', markersize=4, label=f'Demanda General ({department_col})', color=colors(i))
    all_handles.append(line)
    all_labels.append(f'Demanda General ({department_col})')

# Calcular la demanda total general para identificar semanas con demanda cero global
total_general_weekly_demand = weekly_general_demand_by_dept.sum(axis=1)
zero_total_demand_weeks = total_general_weekly_demand[total_general_weekly_demand == 0].index.tolist()

# Resaltar semanas sin demanda total (para el conjunto de departamentos)
zero_demand_patch = None
legend_label_added_zero_demand = False
for week_start_date in zero_total_demand_weeks:
    week_end_date = week_start_date + pd.Timedelta(days=6)
    if not legend_label_added_zero_demand:
        zero_demand_patch = ax.axvspan(week_start_date, week_end_date, color='red', alpha=0.1, label='Semanas sin Demanda Observada (Total)')
        legend_label_added_zero_demand = True
    else:
        ax.axvspan(week_start_date, week_end_date, color='red', alpha=0.1)

if zero_demand_patch:
    all_handles.append(plt.Rectangle((0, 0), 1, 1, fc='red', alpha=0.1))
    all_labels.append('Semanas sin Demanda Observada (Total)')

# Añadir líneas verticales para eventos especiales
events_added_to_legend = set()
for event_data in special_event_dates:
    event_date = event_data['date']
    event_type = event_data['event']
    color = event_colors.get(event_type, 'gray')

    # Asegurarse de que la fecha del evento esté dentro del rango de las fechas graficadas
    if not weekly_general_demand_by_dept.empty and \
       weekly_general_demand_by_dept.index.min() <= event_date <= weekly_general_demand_by_dept.index.max():

        if event_type not in events_added_to_legend:
            line = ax.axvline(x=event_date, color=color, linestyle='--', linewidth=2, label=f'{event_type}')
            all_handles.append(line)
            all_labels.append(f'{event_type}')
            events_added_to_legend.add(event_type)
        else:
            ax.axvline(x=event_date, color=color, linestyle='--', linewidth=2)

ax.set_title('Demanda Observada Semanal General por Departamento Agrupado y Eventos', fontsize=16)
ax.set_xlabel('Fecha', fontsize=12)
ax.set_ylabel('Demanda Observada (Unidades)', fontsize=12)
ax.grid(True, linestyle='--', alpha=0.7)
plt.xticks(rotation=45)
ax.xaxis.set_major_formatter(mdates.DateFormatter('%Y-%m-%d'))

# Crear la leyenda con todos los elementos
ax.legend(handles=all_handles, labels=all_labels, title='Leyenda', loc='upper left', bbox_to_anchor=(1, 1))
plt.tight_layout(rect=[0, 0, 0.85, 1]) # Ajustar el diseño para que la leyenda no se superponga
plt.show()

print("\nEl gráfico de demanda observada semanal general por departamento y eventos ha sido generado.")

import pandas as pd
from scipy import stats
from datetime import timedelta
import numpy as np
from statsmodels.stats.multicomp import pairwise_tukeyhsd

# Ensure `weekly_general_demand_by_dept` is available from previous execution
# and that `special_event_dates` is defined.

if 'weekly_general_demand_by_dept' not in locals() or weekly_general_demand_by_dept.empty:
    print("Error: La variable 'weekly_general_demand_by_dept' no está disponible o está vacía.\n" \
          "Por favor, ejecuta la celda anterior que genera este DataFrame.")
elif 'special_event_dates' not in locals() or not special_event_dates:
    print("Error: La variable 'special_event_dates' no está definida o está vacía.\n" \
          "Por favor, ejecuta la celda anterior que define los eventos especiales.")
else:
    # Get the unique end-of-week dates for all special events
    event_week_ends = [event_data['date'] for event_data in special_event_dates]
    event_week_ends_unique = sorted(list(set(event_week_ends)))
    event_week_ends_unique_dt = pd.to_datetime(event_week_ends_unique)

    # Filter weekly_general_demand_by_dept for event weeks
    # The index of weekly_general_demand_by_dept is already the end of the week (Sunday)
    event_demand_by_dept = weekly_general_demand_by_dept[weekly_general_demand_by_dept.index.isin(event_week_ends_unique_dt)]

    # Prepare data for ANOVA
    # Ensure these columns exist in the filtered DataFrame
    department_groups = ['Bogota D.C.', 'CUNDINAMARCA', 'RESTO DE DEPARTAMENTOS']
    available_groups = [group for group in department_groups if group in event_demand_by_dept.columns]

    if len(available_groups) < 2:
        print("No hay suficientes grupos de departamentos con datos de eventos para realizar la prueba estadística.")
    else:
        data_for_anova = [event_demand_by_dept[group].values for group in available_groups]

        # Check if there's enough data points for each group for a meaningful test
        min_data_points = min(len(data) for data in data_for_anova)
        if min_data_points < 2: # ANOVA typically needs at least 2 observations per group
            print("No hay suficientes semanas de eventos con demanda observada para realizar la prueba estadística para todos los grupos.")
        else:
            # Perform ANOVA test
            f_statistic, p_value = stats.f_oneway(*data_for_anova)

            print("\n" + "="*80)
            print("PRUEBA ESTADÍSTICA DE MEDIAS DE DEMANDA DURANTE EVENTOS (ANOVA)")
            print("="*80)
            print(f"Número de semanas de eventos analizadas: {len(event_demand_by_dept)}")
            for group in available_groups:
                print(f"Demanda promedio en {group} durante eventos: {event_demand_by_dept[group].mean():,.2f}")

            print(f"\nEstadístico F de ANOVA: {f_statistic:.3f}")
            print(f"Valor p: {p_value:.3f}")

            alpha = 0.05
            if p_value < alpha:
                print(f"\nDado que el valor p ({p_value:.3f}) es menor que el nivel de significancia ({alpha}),")
                print("rechazamos la hipótesis nula. Esto sugiere que existe una diferencia estadísticamente significativa")
                print("en la demanda promedio durante los eventos entre al menos dos de los grupos de departamentos.")

                # If ANOVA is significant, perform post-hoc test (Tukey's HSD) to find out which groups differ
                all_demands = np.concatenate(data_for_anova)
                labels = []
                for group_name, data_series in zip(available_groups, data_for_anova):
                    labels.extend([group_name] * len(data_series))

                tukey_result = pairwise_tukeyhsd(endog=all_demands, groups=labels, alpha=alpha)
                print("\nPrueba Post-Hoc de Tukey HSD:")
                print(tukey_result)
                print("\nInterpretación de Tukey HSD: Si 'reject' es True, la diferencia de medias entre ese par es estadísticamente significativa.")

                # Identify and print groups that are NOT statistically significantly different
                print("\nGrupos de departamentos que NO son estadísticamente diferentes en demanda durante eventos:")
                tukey_df = pd.DataFrame(data=tukey_result._results_table.data[1:], columns=tukey_result._results_table.data[0])
                non_significant_pairs = tukey_df[tukey_df['reject'] == False]

                if not non_significant_pairs.empty:
                    for _, row in non_significant_pairs.iterrows():
                        print(f"- {row['group1']} y {row['group2']} (p-adj: {row['p-adj']:.4f})")
                else:
                    print("No se encontraron pares de grupos que NO fueran estadísticamente diferentes.")

            else:
                print(f"\nDado que el valor p ({p_value:.3f}) es mayor que el nivel de significancia ({alpha}),")
                print("no rechazamos la hipótesis nula. Esto sugiere que no hay una diferencia estadísticamente significativa")
                print("en la demanda promedio durante los eventos entre los grupos de departamentos.")

unique_products = df['Producto'].unique().tolist()
num_unique_products = len(unique_products)

print(f"Total de productos únicos: {num_unique_products}")
print("\nListado de productos:")
for product in unique_products:
    print(f"- {product}")