# -*- coding: utf-8 -*-
"""04_modeladoGeneral.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qpbXXIF-OidOyHZYRlEx-y8MfPUaUnp8

# **Modelado Productos AX**

## Configuracion
"""

# Commented out IPython magic to ensure Python compatibility.
# # versiones
# %%writefile requirements.txt
# pandas==2.2.2
# matplotlib==3.10.0
# seaborn==0.13.2

# instalar versiones de librerias
# !pip install -r requirements.txt

# Librerias
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from enum import unique
import matplotlib.dates as mdates

"""## Carga del Dataset"""

# Drive
from google.colab import drive
drive.mount('/content/drive')

# Visualizar dataset
df_productos = pd.read_csv('/content/drive/MyDrive/Trabajo de Grado JuanPablo/Datasets/Dataset_cleaned1.csv', sep=',', on_bad_lines='skip')
df_productos.head()

# Visualizar dataset
df_quiebres = pd.read_csv('/content/drive/MyDrive/Trabajo de Grado JuanPablo/Datasets/quiebresProductosAX.csv', sep=';', on_bad_lines='skip')
df_quiebres.head()

"""## **Análisis Temporal**

### Demanda Real Solapada X Producto

Permite identificar tendencias, estacionalidad, patrones, etc.
"""

df_productos = pd.read_csv('/content/drive/MyDrive/Trabajo de Grado JuanPablo/Datasets/Dataset_cleaned1.csv', sep=';', on_bad_lines='skip')
df_productos["FECHA"] = pd.to_datetime(df_productos["FECHA"])
df_productos["demanda_real"] = df_productos["BackOrder"] + df_productos["Facturado"]

df_productos["Año"] = df_productos["FECHA"].dt.isocalendar().year
df_productos["Semana"] = df_productos["FECHA"].dt.isocalendar().week

df_semanal = (
    df_productos.groupby(
        ["Producto", "Año", "Semana"],
        as_index=False
    )["demanda_real"]
    .sum()
)

for producto in df_semanal["Producto"].unique():
    datos = df_semanal[df_semanal["Producto"] == producto]

    plt.figure(figsize=(12, 6))

    sns.lineplot(
        data=datos,
        x="Semana",
        y="demanda_real",
        hue="Año",
        marker="o",
        palette="tab10"
    )

    plt.title(f"Comparación anual de la demanda semanal de {producto}")
    plt.xlabel("Semana del año")
    plt.ylabel("Demanda real")
    plt.xticks(range(1, 54, 2))
    plt.grid(True, alpha=0.3)
    plt.legend(title="Año")
    plt.tight_layout()
    plt.show()

"""### Demanda Real con Eventos asociados atipicos"""

# Preparar las fechas
df_productos["FECHA"] = pd.to_datetime(df_productos["FECHA"])
df_quiebres["FechaInicial"] = pd.to_datetime(df_quiebres["FechaInicial"])
df_quiebres["FechaFinal"] = pd.to_datetime(df_quiebres["FechaFinal"])

# Calcular la demanda real
df_productos["demanda_real"] = (
    df_productos["BackOrder"] + df_productos["Facturado"]
)

# Agrupar cronológicamente por producto y semana
df_semanal = (
    df_productos
    .groupby([
        "IDProducto",
        "Producto",
        pd.Grouper(key="FECHA", freq="W-MON")
    ])["demanda_real"]
    .sum()
    .reset_index()
)

# Eventos importantes
eventos = [
    {"año": 2025, "semana": 1,  "nombre": "Vacaciones"},
    {"año": 2024, "semana": 13, "nombre": "Semana Santa"},
    {"año": 2025, "semana": 16, "nombre": "Semana Santa"},
    {"año": 2025, "semana": 20, "nombre": "Rueda de negocios"},
    {"año": 2024, "semana": 37, "nombre": "Feria"},
    {"año": 2025, "semana": 39, "nombre": "Feria"}
]

# Convertir el año y la semana ISO en fecha
for evento in eventos:
    evento["fecha"] = pd.to_datetime(
        f'{evento["año"]}-W{evento["semana"]:02d}-1',
        format="%G-W%V-%u"
    )

# Obtener ID y nombre de cada producto
productos = df_semanal[
    ["IDProducto", "Producto"]
].drop_duplicates()

# Graficar cada producto
for _, fila_producto in productos.iterrows():

    id_producto = fila_producto["IDProducto"]
    nombre_producto = fila_producto["Producto"]

    # Demanda del producto
    datos = (
        df_semanal[
            df_semanal["IDProducto"] == id_producto
        ]
        .sort_values("FECHA")
        .copy()
    )

    # Periodos de quiebre del producto
    quiebres_producto = df_quiebres[
        df_quiebres["IDProductos"] == id_producto
    ]

    # Inicialmente, ninguna semana tiene quiebre
    datos["tiene_quiebre"] = False

    # Marcar las semanas afectadas por algún quiebre
    for _, quiebre in quiebres_producto.iterrows():

        inicio_semana = datos["FECHA"] - pd.Timedelta(days=6)
        final_semana = datos["FECHA"]

        semana_afectada = (
            (final_semana >= quiebre["FechaInicial"]) &
            (inicio_semana <= quiebre["FechaFinal"])
        )

        datos.loc[semana_afectada, "tiene_quiebre"] = True

    # Obtener los puntos correspondientes a semanas con quiebre
    puntos_quiebre = datos[datos["tiene_quiebre"]]

    fig, ax = plt.subplots(figsize=(16, 7))

    # Línea azul de demanda
    sns.lineplot(
        data=datos,
        x="FECHA",
        y="demanda_real",
        color="blue",
        linewidth=2,
        marker="o",
        markersize=4,
        ax=ax,
        label="Demanda real semanal"
    )

    # Puntos rojos para las semanas con quiebre
    ax.scatter(
        puntos_quiebre["FECHA"],
        puntos_quiebre["demanda_real"],
        color="red",
        s=80,
        zorder=5,
        label="Semana con quiebre"
    )

    # Líneas punteadas para los eventos
    for evento in eventos:
        ax.axvline(
            x=evento["fecha"],
            color="gray",
            linestyle="--",
            linewidth=1.2,
            alpha=0.7
        )

        ax.text(
            evento["fecha"],
            ax.get_ylim()[1] * 0.95,
            f'{evento["nombre"]}\n'
            f'Semana {evento["semana"]} - {evento["año"]}',
            rotation=90,
            verticalalignment="top",
            horizontalalignment="right",
            fontsize=9
        )

    ax.set_title(
        f"Demanda real semanal y quiebres: {nombre_producto}"
    )
    ax.set_xlabel("Fecha")
    ax.set_ylabel("Demanda real")
    ax.grid(True, alpha=0.3)
    ax.legend()

    plt.xticks(rotation=45)
    plt.tight_layout()
    plt.show()

"""### Descomposición Clásica (Estacionalidad, Tendencia, Variabilidad)"""

from statsmodels.tsa.seasonal import seasonal_decompose
from statsmodels.graphics.tsaplots import plot_acf, plot_pacf

# Crear la demanda real
df_productos["FECHA"] = pd.to_datetime(df_productos["FECHA"])
df_productos["demanda_real"] = df_productos["BackOrder"] + df_productos["Facturado"]

for producto in df_productos["Producto"].unique():

    # Construir la serie semanal del producto
    serie = (
        df_productos[df_productos["Producto"] == producto]
        .set_index("FECHA")["demanda_real"]
        .resample("W-MON")
        .sum()
        .asfreq("W-MON", fill_value=0)
    )

    # Descomposición clásica con estacionalidad anual de 52 semanas
    descomposicion = seasonal_decompose(
        serie,
        model="additive",
        period=52,
        extrapolate_trend="freq"
    )

    # Graficar serie, tendencia, estacionalidad y residuos
    figura = descomposicion.plot()
    figura.set_size_inches(14, 10)
    figura.suptitle(
        f"Descomposición clásica semanal: {producto}",
        fontsize=16,
        y=1.02
    )
    plt.tight_layout()
    plt.show()

    # Graficar ACF y PACF
    fig, axes = plt.subplots(2, 1, figsize=(14, 9))

    plot_acf(
        serie,
        lags=52,
        ax=axes[0],
        alpha=0.05
    )
    axes[0].set_title(f"ACF de la demanda semanal: {producto}")
    axes[0].set_xlabel("Rezago en semanas")
    axes[0].set_ylabel("Autocorrelación")
    axes[0].grid(True, alpha=0.3)

    plot_pacf(
        serie,
        lags=52,
        ax=axes[1],
        alpha=0.05,
        method="ywm"
    )
    axes[1].set_title(f"PACF de la demanda semanal: {producto}")
    axes[1].set_xlabel("Rezago en semanas")
    axes[1].set_ylabel("Autocorrelación parcial")
    axes[1].grid(True, alpha=0.3)

    plt.tight_layout()
    plt.show()

"""## **SPRAY COLOR NEGRO MATE LOGIPAINT RB4**

Se usa este producto como ejemplo para hacer un primer modelo y evaluarlo

### Demanda solapada
"""

# Producto que se analizará
PRODUCTO_BASE = "SPRAY COLOR NEGRO MATE LOGIPAINT RB4"

# Preparar los datos
df_productos["FECHA"] = pd.to_datetime(df_productos["FECHA"])

df_productos["demanda_real"] = (
    df_productos["BackOrder"] +
    df_productos["Facturado"]
)

# Obtener el ID del producto
id_producto = df_productos.loc[
    df_productos["Producto"].str.strip().str.upper() == PRODUCTO_BASE,
    "IDProducto"
].iloc[0]

# Agrupar semanalmente solamente el producto seleccionado
df_semanal_producto = (
    df_productos[
        df_productos["Producto"].str.strip().str.upper()
        == PRODUCTO_BASE
    ]
    .groupby(
        pd.Grouper(key="FECHA", freq="W-MON")
    )["demanda_real"]
    .sum()
    .reset_index()
    .sort_values("FECHA")
)

# Agregar el año y la semana ISO
df_semanal_producto["Año"] = (
    df_semanal_producto["FECHA"]
    .dt.isocalendar()
    .year
    .astype(int)
)

df_semanal_producto["Semana"] = (
    df_semanal_producto["FECHA"]
    .dt.isocalendar()
    .week
    .astype(int)
)


# Verificar que el producto tenga información
print(f"Producto: {PRODUCTO_BASE}")
print(f"ID: {id_producto}")
print(f"Semanas disponibles: {len(df_semanal_producto)}")

# Graficar los años solapados
plt.figure(figsize=(14, 7))

sns.lineplot(
    data=df_semanal_producto,
    x="Semana",
    y="demanda_real",
    hue="Año",
    marker="o",
    palette="tab10"
)

plt.title(f"Demanda real semanal: {PRODUCTO_BASE}")
plt.xlabel("Semana del año")
plt.ylabel("Demanda real")
plt.xticks(range(1, 54, 2))
plt.xlim(1, 53)
plt.grid(True, alpha=0.3)
plt.legend(title="Año")
plt.tight_layout()
plt.show()

"""#### Observaciones

* Se observa a primera vista un efecto estacional, el promeido parece estar entre
las 500 - 700 semanas.
* Existen picos altos y bajos que corresponden a evento especificos del año, más adelante se detallan.

### Demanda con eventos y quiebres
"""

# Eventos importantes
eventos = [
    {"año": 2025, "semana": 1,  "nombre": "Vacaciones"},
    {"año": 2024, "semana": 13, "nombre": "Semana Santa"},
    {"año": 2025, "semana": 16, "nombre": "Semana Santa"},
    {"año": 2025, "semana": 20, "nombre": "Rueda de negocios"},
    {"año": 2024, "semana": 38, "nombre": "Feria"},
    {"año": 2025, "semana": 39, "nombre": "Feria"}
]

# Convertir cada año y semana ISO en una fecha
for evento in eventos:
    evento["fecha"] = pd.to_datetime(
        f'{evento["año"]}-W{evento["semana"]:02d}-1',
        format="%G-W%V-%u"
    )

# Preparar las fechas de los quiebres
df_quiebres["FechaInicial"] = pd.to_datetime(
    df_quiebres["FechaInicial"]
)

df_quiebres["FechaFinal"] = pd.to_datetime(
    df_quiebres["FechaFinal"]
)

# Seleccionar los quiebres del producto
quiebres_producto = df_quiebres[
    df_quiebres["IDProductos"] == id_producto
]

# Inicialmente ninguna semana tiene quiebre
df_semanal_producto["tiene_quiebre"] = False

# Marcar las semanas afectadas por un quiebre
for _, quiebre in quiebres_producto.iterrows():

    inicio_semana = (
        df_semanal_producto["FECHA"] -
        pd.Timedelta(days=6)
    )

    final_semana = df_semanal_producto["FECHA"]

    semana_afectada = (
        (final_semana >= quiebre["FechaInicial"]) &
        (inicio_semana <= quiebre["FechaFinal"])
    )

    df_semanal_producto.loc[
        semana_afectada,
        "tiene_quiebre"
    ] = True

# Extraer las semanas con quiebre
puntos_quiebre = df_semanal_producto[
    df_semanal_producto["tiene_quiebre"]
]

# Crear la gráfica
fig, ax = plt.subplots(figsize=(16, 7))

# Línea azul de demanda real
ax.plot(
    df_semanal_producto["FECHA"],
    df_semanal_producto["demanda_real"],
    color="blue",
    linewidth=2,
    marker="o",
    markersize=4,
    label="Demanda real semanal"
)

# Puntos rojos para las semanas con quiebre
ax.scatter(
    puntos_quiebre["FECHA"],
    puntos_quiebre["demanda_real"],
    color="red",
    s=90,
    zorder=5,
    label="Semana con quiebre"
)

# Agregar las líneas verticales de los eventos
for evento in eventos:
    ax.axvline(
        x=evento["fecha"],
        color="gray",
        linestyle="--",
        linewidth=1.2,
        alpha=0.7
    )

    ax.text(
        evento["fecha"],
        ax.get_ylim()[1] * 0.95,
        f'{evento["nombre"]}\n'
        f'Semana {evento["semana"]} - {evento["año"]}',
        rotation=90,
        verticalalignment="top",
        horizontalalignment="right",
        fontsize=9
    )

ax.set_title(
    f"Demanda, eventos y quiebres: {PRODUCTO_BASE}"
)
ax.set_xlabel("Fecha")
ax.set_ylabel("Demanda real")
ax.grid(True, alpha=0.3)
ax.legend()

plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

"""#### Observaciones

* Durante la Semana Santa se observa una reducción de la demanda promedio, la cual parece extenderse hasta la semana siguiente. Sin embargo, en este periodo también se presenta un quiebre de inventario. Por esta razón, no es posible atribuir directamente la disminución a la Semana Santa, pues podría estar relacionada total o parcialmente con la falta de disponibilidad del producto.

* En el periodo correspondiente a la feria se evidencia un aumento considerable de la demanda. Este comportamiento sugiere una posible relación entre el evento y el incremento de las ventas. Posteriormente, se estimará el efecto promedio de este y de los demás eventos sobre la demanda del producto.

* La rueda de negocios no parece generar un efecto significativo sobre la demanda de este producto. Tanto durante la semana del evento como en las semanas cercanas, los valores se mantienen alrededor del promedio habitual.

* Durante las vacaciones, particularmente en la primera semana del año, se presenta una reducción drástica de la demanda. Este comportamiento coincide con la tendencia general observada al inicio del año, posiblemente asociada con el cierre de operaciones por las festividades de fin de año y Año Nuevo. No obstante, también se registran quiebres de inventario durante esta semana y la siguiente, por lo que es necesario analizar con mayor profundidad si la disminución corresponde a una menor demanda real, a la falta de disponibilidad del producto o a una combinación de ambos factores.

* Se identifican quiebres de inventario recurrentes, especialmente en periodos cercanos a eventos atípicos que podrían modificar la demanda. Esta coincidencia dificulta la estimación aislada del efecto de cada evento, dado que una reducción en las ventas observadas puede explicarse por una disminución de la demanda o por la imposibilidad de atenderla debido a la falta de inventario.

* También se registra un quiebre de inventario durante la última semana del año. Este resultado debe revisarse, pues podría corresponder a la última venta disponible antes de agotar las existencias. Asimismo, la baja demanda de la primera semana puede responder a la lógica operativa del cierre de año, mientras que el quiebre registrado en la semana posterior podría reflejar un retraso en el reabastecimiento. Por lo tanto, es necesario revisar las fechas, la duración de los quiebres y las reglas utilizadas para registrarlos antes de establecer una conclusión definitiva.

### Descomposición de la demanda
"""

from statsmodels.tsa.seasonal import seasonal_decompose

# Crear una serie temporal semanal
serie_producto = (
    df_semanal_producto
    .set_index("FECHA")["demanda_real"]
    .asfreq("W-MON", fill_value=0)
)

# Verificar que existan al menos dos años de datos
if len(serie_producto) >= 104:

    # Descomposición aditiva con estacionalidad anual
    descomposicion = seasonal_decompose(
        serie_producto,
        model="additive",
        period=52,
        extrapolate_trend="freq"
    )

    # Graficar los componentes
    figura = descomposicion.plot()
    figura.set_size_inches(14, 10)

    # Cambiar los títulos al español
    titulos = [
        "Demanda real observada",
        "Tendencia",
        "Estacionalidad",
        "Residuo"
    ]

    for eje, titulo in zip(figura.axes, titulos):
        eje.set_title(titulo)
        eje.set_ylabel("Demanda")
        eje.grid(True, alpha=0.3)

    figura.suptitle(
        f"Descomposición clásica semanal: {PRODUCTO_BASE}",
        fontsize=16,
        y=1.02
    )

    plt.tight_layout()
    plt.show()

else:
    print("No existen suficientes semanas para la descomposición.")
    print(f"Semanas disponibles: {len(serie_producto)}")
    print("Se requieren al menos 104 semanas para usar un periodo de 52.")

"""#### Observaciones

* La demanda semanal del producto se concentra principalmente entre 500 y 1.000 unidades. Sin embargo, presenta una variabilidad considerable, con semanas de demanda muy baja y otras con incrementos superiores al comportamiento habitual.

* La descomposición muestra una tendencia descendente de la demanda durante el periodo analizado. No obstante, la presencia de múltiples quiebres de inventario dificulta afirmar que esta reducción corresponda a una disminución natural del mercado. Parte de la caída podría deberse a ventas no realizadas o demanda no registrada por falta de disponibilidad del producto.

* Se evidencia un componente estacional potencialmente importante. Algunas semanas presentan efectos positivos superiores a 400 unidades, mientras que otras registran efectos negativos inferiores a −500 unidades. Esto indica que determinadas semanas del año pueden aumentar o reducir de manera considerable la demanda esperada. Sin embargo, algunos de estos efectos coinciden con vacaciones, eventos comerciales o quiebres de inventario, por lo que no deben atribuirse exclusivamente a la estacionalidad.

* El residuo representa la diferencia entre la demanda real observada y la parte explicada por la tendencia y la estacionalidad:

$$
\text{Residuo}
=
\text{Demanda real observada}
-
\text{Tendencia}
-
\text{Estacionalidad}
$$

La mayoría de los residuos se encuentra aproximadamente entre −200 y 200 unidades, aunque se observan valores extremos cercanos a +450 y −420 unidades:

* Un residuo positivo indica que la demanda observada fue mayor de lo esperado.

* Un residuo negativo indica que fue menor de lo esperado.

* Un residuo cercano a cero señala que la tendencia y la estacionalidad explicaron razonablemente el comportamiento de esa semana.

* Los residuos extremos pueden estar asociados con ferias, promociones, vacaciones, quiebres de inventario u omisiones en el registro de la demanda. Por esta razón, deben analizarse junto con los eventos del negocio antes de considerarlos fluctuaciones aleatorias.

#### Conclusión

El principal reto consistirá en modelar adecuadamente la demanda sin distorsionar su comportamiento, teniendo en cuenta tanto los efectos generados por los eventos comerciales y estacionales como las restricciones ocasionadas por los quiebres de inventario. La demanda observada no necesariamente representa toda la demanda del mercado, ya que la falta de existencias puede impedir ventas y generar una omisión parcial de la demanda real.

Si el modelo se entrena únicamente con las ventas observadas, podría aprender artificialmente que las semanas con quiebre presentan una demanda baja. Esto llevaría a generar pronósticos inferiores a las necesidades reales, reducir el inventario recomendado y reproducir nuevamente el mismo problema de desabastecimiento. Por lo tanto, será necesario identificar y tratar explícitamente los periodos de quiebre e incorporar los eventos relevantes como variables explicativas, con el propósito de estimar una demanda menos afectada por las restricciones históricas de inventario.

### Análisis de ACF y PACF
"""

from statsmodels.graphics.tsaplots import plot_acf, plot_pacf

# Crear la serie semanal regular
serie_producto = (
    df_semanal_producto
    .set_index("FECHA")["demanda_real"]
    .asfreq("W-MON", fill_value=0)
)

# Máximo número de rezagos permitido para la PACF
max_lags = min(
    52,
    (len(serie_producto) // 2) - 1
)

# Crear las dos gráficas
fig, axes = plt.subplots(
    2,
    1,
    figsize=(14, 9)
)

# Gráfica ACF
plot_acf(
    serie_producto,
    lags=max_lags,
    alpha=0.05,
    ax=axes[0]
)

axes[0].set_title(
    f"ACF de la demanda semanal: {PRODUCTO_BASE}"
)
axes[0].set_xlabel("Rezago en semanas")
axes[0].set_ylabel("Autocorrelación")
axes[0].grid(True, alpha=0.3)

# Gráfica PACF
plot_pacf(
    serie_producto,
    lags=max_lags,
    alpha=0.05,
    method="ywm",
    ax=axes[1]
)

axes[1].set_title(
    f"PACF de la demanda semanal: {PRODUCTO_BASE}"
)
axes[1].set_xlabel("Rezago en semanas")
axes[1].set_ylabel("Autocorrelación parcial")
axes[1].grid(True, alpha=0.3)

plt.tight_layout()
plt.show()

"""#### Observaciones
* La **ACF** mide la relación entre la demanda actual y sus valores anteriores. Se utiliza principalmente para orientar la selección del componente de **media móvil (MA)**.

* La **PACF** mide la relación directa entre la demanda actual y cada rezago, eliminando el efecto de los rezagos intermedios. Se utiliza principalmente para orientar la selección del componente **autorregresivo (AR)**.

* En ambos gráficos, casi todas las barras permanecen dentro de las bandas de confianza. Esto indica que la demanda semanal presenta poca dependencia lineal respecto a sus valores históricos.

* En el rezago de dos semanas se observa una correlación negativa débil, ligeramente significativa. Esto podría indicar que un aumento de la demanda está asociado con una reducción dos semanas después; sin embargo, el efecto es pequeño y puede estar influenciado por quiebres de inventario o eventos comerciales.

* La ACF no presenta un corte claro después de uno o varios rezagos. Por lo tanto, no existe evidencia suficiente para justificar un componente MA de orden alto. Como punto de partida podrían evaluarse \(q=0\), \(q=1\) o \(q=2\).

* La PACF tampoco muestra un corte claramente definido. En consecuencia, no se identifica una estructura AR fuerte y podrían probarse inicialmente \(p=0\), \(p=1\) o \(p=2\).

* No se observa un pico significativo en el rezago 52, por lo que estos gráficos no proporcionan evidencia estadística fuerte de una dependencia anual. Sin embargo, esta conclusión es limitada porque solo se dispone de aproximadamente dos años de información.

#### Conclusión

Los resultados sugieren que los componentes AR y MA por sí solos tendrían una capacidad limitada para explicar la demanda. Por ello, conviene evaluar modelos ARIMA de órdenes bajos e incorporar variables externas como quiebres de inventario, vacaciones, Semana Santa, ferias y promociones. La selección definitiva de \(p\) y \(q\) debe validarse comparando modelos mediante criterios como AIC y BIC, además de métricas de pronóstico sobre datos no utilizados durante el entrenamiento.

### Análisis Espectral
"""

from scipy.signal import periodogram, detrend

# Crear la serie semanal regular
serie_producto = (
    df_semanal_producto
    .set_index("FECHA")["demanda_real"]
    .asfreq("W-MON", fill_value=0)
)

# Eliminar la tendencia lineal
serie_sin_tendencia = detrend(
    serie_producto.values
)

# Calcular el periodograma
frecuencias, potencia = periodogram(
    serie_sin_tendencia,
    fs=1  # Una observación por semana
)

# Eliminar la frecuencia cero
frecuencias = frecuencias[1:]
potencia = potencia[1:]

# Convertir frecuencia en duración del ciclo
periodos = 1 / frecuencias

# Conservar ciclos entre 2 y 52 semanas
filtro_periodos = (
    (periodos >= 2) &
    (periodos <= 52)
)

periodos_filtrados = periodos[filtro_periodos]
potencia_filtrada = potencia[filtro_periodos]

# Graficar el espectro según la duración del ciclo
plt.figure(figsize=(14, 7))

plt.plot(
    periodos_filtrados,
    potencia_filtrada,
    color="darkblue",
    linewidth=2
)

# Ciclos de referencia
ciclos_referencia = {
    4: "Mensual",
    13: "Trimestral",
    26: "Semestral",
    52: "Anual"
}

for periodo, nombre in ciclos_referencia.items():
    plt.axvline(
        x=periodo,
        color="gray",
        linestyle="--",
        alpha=0.7
    )

    plt.text(
        periodo,
        plt.ylim()[1] * 0.9,
        nombre,
        rotation=90,
        verticalalignment="top",
        horizontalalignment="right"
    )

plt.title(
    f"Análisis espectral de la demanda: {PRODUCTO_BASE}"
)
plt.xlabel("Duración del ciclo en semanas")
plt.ylabel("Potencia espectral")
plt.xlim(2, 52)
plt.grid(True, alpha=0.3)
plt.tight_layout()
plt.show()

resultado_espectral = pd.DataFrame({
    "periodo_semanas": periodos_filtrados,
    "potencia": potencia_filtrada
})

ciclos_dominantes = (
    resultado_espectral
    .sort_values("potencia", ascending=False)
    .head(5)
    .reset_index(drop=True)
)

print("Ciclos dominantes:")
display(ciclos_dominantes.round(2))

"""#### Observaciones

El análisis espectral sugiere que la demanda presenta principalmente fluctuaciones de corto plazo, con ciclos potenciales cercanos a tres, cuatro y siete semanas. No se identifica evidencia fuerte de ciclos semestrales o anuales. No obstante, estos picos pueden estar influenciados por los procesos de reposición, los eventos comerciales y los quiebres de inventario, por lo que no deben considerarse automáticamente como patrones naturales de consumo.

### Modelo ARIMA

#### Preparación de la Serie
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import warnings

from src.lead.forecasting.evaluation import calculate_metrics
from src.lead.forecasting.experiments import (
    run_arima_experiment,
    run_sarima_experiment,
)
from src.lead.forecasting.split import split_last_months

warnings.filterwarnings("ignore")

# Crear la serie semanal regular
serie_producto = (
    df_semanal_producto
    .set_index("FECHA")["demanda_real"]
    .sort_index()
    .asfreq("W-MON", fill_value=0)
    .astype(float)
)

# Fecha de corte: últimos seis meses para prueba
serie_entrenamiento, serie_prueba, fecha_corte = split_last_months(
    serie_producto,
    months=6,
)

print("Inicio del entrenamiento:", serie_entrenamiento.index.min())
print("Final del entrenamiento:", serie_entrenamiento.index.max())
print("Semanas de entrenamiento:", len(serie_entrenamiento))

print("\nInicio de la prueba:", serie_prueba.index.min())
print("Final de la prueba:", serie_prueba.index.max())
print("Semanas de prueba:", len(serie_prueba))

"""#### Definición de Métricas"""

calcular_metricas = lambda real, prediccion: tuple(
    calculate_metrics(real, prediccion).values()
)

"""#### Modelo ARIMA AUTOMATICO"""

experimento_arima = run_arima_experiment(
    serie_entrenamiento,
    serie_prueba,
)
resultados = experimento_arima["results"].to_dict(orient="records")
predicciones = experimento_arima["predictions"]
modelos_arima = experimento_arima["models"]
modelo_automatico = modelos_arima["Auto ARIMA"]
orden_automatico = modelo_automatico.order
prediccion_automatica = predicciones["Auto ARIMA"]

print("Orden seleccionado:", orden_automatico)

"""#### Modelo ARIMA Manual"""

# El ajuste automático y la grilla manual se ejecutan en el módulo reutilizable.

"""#### "Mejor Modelo"
"""

tabla_resultados = (
    pd.DataFrame(resultados)
    .sort_values(
        by=["RMSE", "MAE"],
        ascending=True
    )
    .reset_index(drop=True)
)

tabla_resultados.index = tabla_resultados.index + 1

display(
    tabla_resultados.style.format({
        "MAE": "{:,.2f}",
        "RMSE": "{:,.2f}",
        "WAPE_%": "{:.2f}%",
        "AIC": "{:,.2f}"
    })
)

mejor_resultado = tabla_resultados.iloc[0]

print("Mejor modelo:", mejor_resultado["modelo"])
print("Orden:", mejor_resultado["orden"])
print("MAE:", round(mejor_resultado["MAE"], 2))
print("RMSE:", round(mejor_resultado["RMSE"], 2))
print("WAPE:", round(mejor_resultado["WAPE_%"], 2), "%")

mejor_modelo = tabla_resultados.iloc[0]["modelo"]
mejor_prediccion = predicciones[mejor_modelo]

plt.figure(figsize=(16, 7))

# Datos de entrenamiento
plt.plot(
    serie_entrenamiento.index,
    serie_entrenamiento,
    color="blue",
    linewidth=1.5,
    label="Entrenamiento"
)

# Datos reales de prueba
plt.plot(
    serie_prueba.index,
    serie_prueba,
    color="black",
    linewidth=2,
    marker="o",
    label="Demanda real de prueba"
)

# Pronóstico
plt.plot(
    mejor_prediccion.index,
    mejor_prediccion,
    color="red",
    linestyle="--",
    linewidth=2,
    marker="o",
    label=f"Pronóstico {mejor_modelo}"
)

# División entre entrenamiento y prueba
plt.axvline(
    fecha_corte,
    color="gray",
    linestyle="--",
    label="Inicio de la prueba"
)

plt.title(
    f"Mejor modelo para {PRODUCTO_BASE}\n"
    f"{mejor_modelo}"
)
plt.xlabel("Fecha")
plt.ylabel("Demanda real")
plt.grid(True, alpha=0.3)
plt.legend()
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

"""**Observaciones**

El ARIMA(0,0,1) produce una línea casi constante porque la demanda pasada tiene poca relación con las semanas siguientes. Después del primer pronóstico, el modelo regresa al promedio histórico, cercano a 620 unidades.

Fue el mejor de los ARIMA evaluados, pero solo estima el nivel promedio: no logra anticipar picos ni caídas. Para mejorar, habría que incorporar eventos, quiebres de inventario, vacaciones y otras variables externas mediante un modelo como SARIMAX.
"""

import ast
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from statsmodels.tsa.arima.model import ARIMA
from statsmodels.stats.diagnostic import acorr_ljungbox, het_arch
from statsmodels.stats.stattools import jarque_bera
from statsmodels.graphics.tsaplots import plot_acf
from statsmodels.graphics.gofplots import qqplot

"""#### Modelo SARIMAX (Estacionalidad)"""

"""### Entrenar SARIMA para ciclos de 3, 4 y 7 semanas (Análisis Expectral)"""

# Periodos identificados en el análisis espectral
periodos_estacionales = [3, 4, 7]

experimento_sarima = run_sarima_experiment(
    serie_entrenamiento,
    serie_prueba,
    seasonal_periods=tuple(periodos_estacionales),
)
resultados_sarima = experimento_sarima["results"].to_dict(orient="records")
modelos_sarima = experimento_sarima["models"]
predicciones_sarima = experimento_sarima["predictions"]

tabla_sarima = (
    pd.DataFrame(resultados_sarima)
    .sort_values(
        by=["RMSE", "MAE"],
        ascending=True
    )
    .reset_index(drop=True)
)

tabla_sarima.index = tabla_sarima.index + 1

display(
    tabla_sarima.style.format({
        "MAE": "{:,.2f}",
        "RMSE": "{:,.2f}",
        "WAPE_%": "{:.2f}%",
        "AIC": "{:,.2f}"
    })
)

mejor_nombre_sarima = tabla_sarima.iloc[0]["modelo"]
mejor_prediccion_sarima = predicciones_sarima[
    mejor_nombre_sarima
]

mejor_fila = tabla_sarima.iloc[0]

plt.figure(figsize=(16, 7))

plt.plot(
    serie_entrenamiento.index,
    serie_entrenamiento,
    color="blue",
    linewidth=1.5,
    label="Entrenamiento"
)

plt.plot(
    serie_prueba.index,
    serie_prueba,
    color="black",
    linewidth=2,
    marker="o",
    label="Demanda real de prueba"
)

plt.plot(
    mejor_prediccion_sarima.index,
    mejor_prediccion_sarima,
    color="red",
    linestyle="--",
    linewidth=2,
    marker="o",
    label=mejor_nombre_sarima
)

plt.axvline(
    fecha_corte,
    color="gray",
    linestyle="--",
    label="Inicio de la prueba"
)

plt.title(
    f"Mejor modelo SARIMA: {PRODUCTO_BASE}\n"
    f"{mejor_fila['orden']} × "
    f"{mejor_fila['orden_estacional']}"
)

plt.xlabel("Fecha")
plt.ylabel("Demanda real")
plt.grid(True, alpha=0.3)
plt.legend()
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

"""#### ARIMA VS SARIMA"""

comparacion_final = pd.concat([
    tabla_resultados[[
        "modelo",
        "orden",
        "MAE",
        "RMSE",
        "WAPE_%",
        "AIC"
    ]].head(1),

    tabla_sarima[[
        "modelo",
        "orden",
        "MAE",
        "RMSE",
        "WAPE_%",
        "AIC"
    ]]
])

comparacion_final = (
    comparacion_final
    .sort_values("RMSE")
    .reset_index(drop=True)
)

display(
    comparacion_final.style.format({
        "MAE": "{:,.2f}",
        "RMSE": "{:,.2f}",
        "WAPE_%": "{:.2f}%",
        "AIC": "{:,.2f}"
    })
)

"""**Observaciones**

El modelo ARIMA(0,0,1) obtuvo el mejor desempeño predictivo, con un MAE de 166,76 unidades, un RMSE de 199,69 unidades y un WAPE de 27,79 %. Los modelos SARIMA presentaron errores ligeramente superiores, aunque las diferencias son mínimas y no representan una mejora relevante frente al modelo ARIMA.

Los tres modelos SARIMA produjeron exactamente los mismos resultados y seleccionaron el orden no estacional ARIMA(0,0,2). Esto probablemente indica que el procedimiento automático descartó los componentes estacionales y seleccionó un orden estacional equivalente a ((0,0,0,m)). En consecuencia, los ciclos de 3, 4 y 7 semanas identificados mediante el análisis espectral no aportaron suficiente información para mejorar la predicción fuera de muestra.

Sin embargo, un WAPE cercano al 28 % evidencia que el error sigue siendo considerable. Esto confirma que la demanda histórica por sí sola no permite explicar adecuadamente los cambios semanales y que será necesario incorporar variables externas relacionadas con quiebres de inventario, ferias, vacaciones y otros eventos comerciales.

#### Modelo ARIMAX (Variables Exogenas)

##### Preparación
"""

# Producto analizado
PRODUCTO_BASE = "SPRAY COLOR NEGRO MATE LOGIPAINT RB4"

# Preparar fecha y demanda real
df_productos["FECHA"] = pd.to_datetime(
    df_productos["FECHA"]
)

df_productos["demanda_real"] = (
    df_productos["BackOrder"] +
    df_productos["Facturado"]
)

# Filtrar el producto seleccionado
filtro_producto = (
    df_productos["Producto"]
    .astype(str)
    .str.strip()
    .str.upper()
    .eq(PRODUCTO_BASE)
)

datos_producto = df_productos.loc[filtro_producto]

# Construir la base semanal
df_exogenas_semanal = (
    datos_producto
    .set_index("FECHA")
    .resample("W-MON")
    .agg({
        "demanda_real": "sum",
        "VlrUnitario": "mean",
        "DiasImportacion": "mean",
        "CantidadObsequio": "sum"
    })
)

# Reemplazar valores infinitos
df_exogenas_semanal = df_exogenas_semanal.replace(
    [np.inf, -np.inf],
    np.nan
)

# Completar datos faltantes en las variables exógenas
columnas_exogenas = [
    "VlrUnitario",
    "DiasImportacion",
    "CantidadObsequio"
]

df_exogenas_semanal[columnas_exogenas] = (
    df_exogenas_semanal[columnas_exogenas]
    .interpolate()
    .ffill()
    .bfill()
)

# Las semanas sin registros de demanda se dejan en cero
df_exogenas_semanal["demanda_real"] = (
    df_exogenas_semanal["demanda_real"]
    .fillna(0)
)

# Eliminar variables constantes
columnas_constantes = [
    columna
    for columna in columnas_exogenas
    if df_exogenas_semanal[columna].nunique() <= 1
]

print("Variables constantes eliminadas:")
print(columnas_constantes)

df_exogenas_semanal = df_exogenas_semanal.drop(
    columns=columnas_constantes
)

columnas_exogenas = [
    columna
    for columna in columnas_exogenas
    if columna not in columnas_constantes
]

display(df_exogenas_semanal.head())

"""##### Correlación contemporánea (misma semana)"""

correlaciones = (
    df_exogenas_semanal
    .corr()["demanda_real"]
    .drop("demanda_real")
    .sort_values(
        key=abs,
        ascending=False
    )
)

display(
    correlaciones
    .rename("correlacion")
    .to_frame()
    .style.format("{:.3f}")
)

"""##### Correlación Cruzada"""

resultados_correlacion = []

for variable in columnas_exogenas:
    for rezago in range(13):

        correlacion = (
            df_exogenas_semanal["demanda_real"]
            .corr(
                df_exogenas_semanal[variable]
                .shift(rezago)
            )
        )

        resultados_correlacion.append({
            "variable": variable,
            "rezago_semanas": rezago,
            "correlacion": correlacion
        })

df_correlacion_cruzada = pd.DataFrame(
    resultados_correlacion
)

matriz_correlacion = (
    df_correlacion_cruzada
    .pivot(
        index="variable",
        columns="rezago_semanas",
        values="correlacion"
    )
)

plt.figure(figsize=(14, 5))

sns.heatmap(
    matriz_correlacion,
    cmap="coolwarm",
    center=0,
    vmin=-1,
    vmax=1,
    annot=True,
    fmt=".2f"
)

plt.title(
    f"Correlación cruzada con la demanda: {PRODUCTO_BASE}"
)
plt.xlabel("Rezago de la variable en semanas")
plt.ylabel("Variable numérica")
plt.tight_layout()
plt.show()

mejores_correlaciones = (
    df_correlacion_cruzada
    .dropna()
    .assign(
        correlacion_absoluta=lambda x:
        x["correlacion"].abs()
    )
    .sort_values(
        "correlacion_absoluta",
        ascending=False
    )
    .drop_duplicates("variable")
    .drop(columns="correlacion_absoluta")
    .reset_index(drop=True)
)

display(
    mejores_correlaciones.style.format({
        "correlacion": "{:.3f}"
    })
)

from scipy.stats import pearsonr

# Alinear precio de la semana anterior con demanda actual
datos_correlacion = pd.concat([
    df_exogenas_semanal["demanda_real"],
    df_exogenas_semanal["VlrUnitario"].shift(1)
], axis=1).dropna()

correlacion, valor_p = pearsonr(
    datos_correlacion["demanda_real"],
    datos_correlacion["VlrUnitario"]
)

print("Correlación:", round(correlacion, 3))
print("Valor-p:", round(valor_p, 4))

if valor_p < 0.05:
    print("La correlación es estadísticamente significativa.")
else:
    print("La correlación no es estadísticamente significativa.")

"""El valor unitario presenta una correlación negativa débil, pero estadísticamente significativa, con la demanda de la semana siguiente. Esto sugiere que los incrementos en el precio pueden estar asociados con una reducción posterior de la cantidad demandada. Aunque la magnitud de la relación es limitada, existe evidencia para evaluar VlrUnitario como variable exógena en el modelo SARIMAX."""

from scipy.stats import pearsonr
from statsmodels.stats.multitest import multipletests

resultados_bonferroni = []

# Evaluar los rezagos de 0 a 12 semanas
for rezago in range(13):

    datos_prueba = pd.concat([
        df_exogenas_semanal["demanda_real"],
        df_exogenas_semanal["VlrUnitario"].shift(rezago)
    ], axis=1).dropna()

    datos_prueba.columns = [
        "demanda_real",
        "VlrUnitario"
    ]

    correlacion, valor_p = pearsonr(
        datos_prueba["demanda_real"],
        datos_prueba["VlrUnitario"]
    )

    resultados_bonferroni.append({
        "rezago_semanas": rezago,
        "correlacion": correlacion,
        "valor_p_original": valor_p
    })

# Crear tabla
tabla_bonferroni = pd.DataFrame(
    resultados_bonferroni
)

# Aplicar la corrección de Bonferroni
rechazar_h0, valores_p_ajustados, _, _ = multipletests(
    tabla_bonferroni["valor_p_original"],
    alpha=0.05,
    method="bonferroni"
)

tabla_bonferroni["valor_p_bonferroni"] = (
    valores_p_ajustados
)

tabla_bonferroni["significativo"] = np.where(
    rechazar_h0,
    "Sí",
    "No"
)

rezagos_significativos = tabla_bonferroni[
    tabla_bonferroni["significativo"] == "Sí"
]

display(
    rezagos_significativos.style.format({
        "correlacion": "{:.3f}",
        "valor_p_original": "{:.4f}",
        "valor_p_bonferroni": "{:.4f}"
    })
)

"""**Observación**

El valor unitario rezagado una semana presenta una correlación negativa débil con la demanda (\(r=-0,284\)). Aunque la relación conserva significancia estadística después de aplicar la corrección de Bonferroni, su valor-p ajustado (\(p=0,0474\)) se encuentra muy próximo al límite de 0,05 y la magnitud de la correlación es reducida.

Por tanto, no se considera conveniente incluir inicialmente `VlrUnitario` como variable exógena, pues su capacidad explicativa parece limitada y añadirla aumentaría innecesariamente la complejidad del modelo. No obstante, esta decisión puede confirmarse comparando posteriormente el desempeño fuera de muestra de un SARIMAX con esta variable frente al modelo ARIMA base.

#### Detectar valores atípicos
"""

from statsmodels.tsa.arima.model import ARIMA
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# Serie semanal regular
serie_producto = (
    df_semanal_producto
    .set_index("FECHA")["demanda_real"]
    .sort_index()
    .asfreq("W-MON", fill_value=0)
    .astype(float)
)

# Modelo base
modelo_base = ARIMA(
    serie_producto,
    order=(0, 0, 1),
    trend="c"
).fit()

# Obtener los residuos
residuos_base = modelo_base.resid.dropna()

# Eliminar las primeras observaciones usadas para inicialización
burn = max(1, modelo_base.loglikelihood_burn)
residuos_base = residuos_base.iloc[burn:]

mediana_residuos = residuos_base.median()

mad = np.median(
    np.abs(residuos_base - mediana_residuos)
)

# Z-score robusto
z_robusto = (
    0.6745 *
    (residuos_base - mediana_residuos) /
    mad
)

# Considerar atípicos los valores con |z| >= 3
tabla_atipicos = pd.DataFrame({
    "demanda_real": serie_producto.loc[residuos_base.index],
    "residuo": residuos_base,
    "z_robusto": z_robusto
})

tabla_atipicos["es_atipico"] = (
    tabla_atipicos["z_robusto"].abs() >= 3
)

atipicos = tabla_atipicos[
    tabla_atipicos["es_atipico"]
].copy()

display(
    atipicos.style.format({
        "demanda_real": "{:,.2f}",
        "residuo": "{:,.2f}",
        "z_robusto": "{:.2f}"
    })
)

plt.figure(figsize=(16, 7))

plt.plot(
    serie_producto.index,
    serie_producto,
    color="blue",
    linewidth=2,
    marker="o",
    markersize=3,
    label="Demanda real semanal"
)

plt.scatter(
    atipicos.index,
    atipicos["demanda_real"],
    color="red",
    s=100,
    zorder=5,
    label="Valor atípico"
)

plt.title(
    f"Valores atípicos de la demanda: {PRODUCTO_BASE}"
)
plt.xlabel("Fecha")
plt.ylabel("Demanda real")
plt.grid(True, alpha=0.3)
plt.legend()
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

# Construir el calendario de eventos
eventos = [
    {"año": 2025, "semana": 1,  "nombre": "Vacaciones"},
    {"año": 2024, "semana": 13, "nombre": "Semana Santa"},
    {"año": 2025, "semana": 16, "nombre": "Semana Santa"},
    {"año": 2025, "semana": 20, "nombre": "Rueda de negocios"},
    {"año": 2024, "semana": 38, "nombre": "Feria"},
    {"año": 2025, "semana": 39, "nombre": "Feria"}
]

for evento in eventos:
    evento["fecha"] = pd.to_datetime(
        f'{evento["año"]}-W{evento["semana"]:02d}-1',
        format="%G-W%V-%u"
    )

df_eventos = pd.DataFrame(eventos)

coincidencias = []

for fecha_atipico, fila in atipicos.iterrows():

    evento_mas_cercano = None
    menor_distancia = np.inf

    for _, evento in df_eventos.iterrows():

        distancia_dias = abs(
            (fecha_atipico - evento["fecha"]).days
        )

        if distancia_dias < menor_distancia:
            menor_distancia = distancia_dias
            evento_mas_cercano = evento

    coincide = menor_distancia <= 7

    coincidencias.append({
        "fecha_atipico": fecha_atipico,
        "demanda_real": fila["demanda_real"],
        "residuo": fila["residuo"],
        "z_robusto": fila["z_robusto"],
        "evento_cercano": (
            evento_mas_cercano["nombre"]
            if coincide else "Ninguno"
        ),
        "fecha_evento": (
            evento_mas_cercano["fecha"]
            if coincide else pd.NaT
        ),
        "distancia_semanas": (
            int(
                (fecha_atipico -
                 evento_mas_cercano["fecha"]).days / 7
            )
            if coincide else np.nan
        )
    })

tabla_coincidencias = pd.DataFrame(coincidencias)

display(
    tabla_coincidencias.style.format({
        "demanda_real": "{:,.2f}",
        "residuo": "{:,.2f}",
        "z_robusto": "{:.2f}"
    })
)

df_quiebres["FechaInicial"] = pd.to_datetime(
    df_quiebres["FechaInicial"]
)

df_quiebres["FechaFinal"] = pd.to_datetime(
    df_quiebres["FechaFinal"]
)

quiebres_producto = df_quiebres[
    df_quiebres["IDProductos"] == id_producto
]

tabla_coincidencias["coincide_quiebre"] = False

for indice, fila in tabla_coincidencias.iterrows():

    final_semana = fila["fecha_atipico"]
    inicio_semana = final_semana - pd.Timedelta(days=6)

    existe_quiebre = (
        (
            quiebres_producto["FechaInicial"]
            <= final_semana
        )
        &
        (
            quiebres_producto["FechaFinal"]
            >= inicio_semana
        )
    ).any()

    tabla_coincidencias.loc[
        indice,
        "coincide_quiebre"
    ] = existe_quiebre

display(
    tabla_coincidencias.style.format({
        "demanda_real": "{:,.2f}",
        "residuo": "{:,.2f}",
        "z_robusto": "{:.2f}"
    })
)

df_eventos["demanda_real"] = np.nan
df_eventos["coincide_atipico"] = False

for indice, evento in df_eventos.iterrows():

    fecha_evento = evento["fecha"]

    # Obtener la demanda de la semana del evento
    if fecha_evento in serie_producto.index:

        df_eventos.loc[
            indice,
            "demanda_real"
        ] = serie_producto.loc[fecha_evento]

    # Calcular la distancia a los atípicos y verificar coincidencia por proximidad
    # Asegurarse de que atipicos no esté vacío antes de intentar la resta
    if not atipicos.empty:
        distancia_atipicos = abs(
            (atipicos.index - fecha_evento).days
        )
        df_eventos.loc[
            indice,
            "coincide_atipico"
        ] = (
            len(distancia_atipicos) > 0
            and distancia_atipicos.min() <= 7
        )
    else:
        df_eventos.loc[indice, "coincide_atipico"] = False

eventos_no_atipicos = df_eventos[
    ~df_eventos["coincide_atipico"]
].dropna(subset=["demanda_real"])

eventos_atipicos = df_eventos[
    df_eventos["coincide_atipico"]
].dropna(subset=["demanda_real"])

# Atípicos que no están cerca de ningún evento
atipicos_sin_evento = atipicos.copy()
atipicos_sin_evento["coincide_evento"] = False

for fecha_atipico in atipicos_sin_evento.index:

    distancia_eventos = abs(
        (df_eventos["fecha"] - fecha_atipico).dt.days
    )

    atipicos_sin_evento.loc[
        fecha_atipico,
        "coincide_evento"
    ] = distancia_eventos.min() <= 7

atipicos_sin_evento = atipicos_sin_evento[
    ~atipicos_sin_evento["coincide_evento"]
]

fig, ax = plt.subplots(figsize=(17, 8))

# Demanda semanal
ax.plot(
    serie_producto.index,
    serie_producto,
    color="blue",
    linewidth=2,
    marker="o",
    markersize=3,
    label="Demanda real semanal"
)

# Eventos que no fueron detectados como atípicos
ax.scatter(
    eventos_no_atipicos["fecha"],
    eventos_no_atipicos["demanda_real"],
    color="orange",
    edgecolor="black",
    s=110,
    zorder=5,
    label="Evento conocido"
)

# Eventos que coinciden con atípicos
ax.scatter(
    eventos_atipicos["fecha"],
    eventos_atipicos["demanda_real"],
    color="red",
    edgecolor="black",
    s=140,
    zorder=6,
    label="Evento coincidente con atípico"
)

# Atípicos que no coinciden con eventos
ax.scatter(
    atipicos_sin_evento.index,
    atipicos_sin_evento["demanda_real"],
    color="purple",
    marker="X",
    s=110,
    zorder=6,
    label="Atípico sin evento identificado"
)

# Etiquetas de todos los eventos
for _, evento in df_eventos.dropna(
    subset=["demanda_real"]
).iterrows():

    ax.annotate(
        f'{evento["nombre"]}\n'
        f'Semana {evento["semana"]} - {evento["año"]}',
        xy=(
            evento["fecha"],
            evento["demanda_real"]
        ),
        xytext=(5, 20),
        textcoords="offset points",
        rotation=90,
        fontsize=9,
        horizontalalignment="left",
        arrowprops={
            "arrowstyle": "-",
            "color": "gray",
            "alpha": 0.6
        }
    )

ax.set_title(
    f"Demanda, eventos conocidos y valores atípicos\n"
    f"{PRODUCTO_BASE}"
)
ax.set_xlabel("Fecha")
ax.set_ylabel("Demanda real")
ax.grid(True, alpha=0.3)
ax.legend()

plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

"""##### SARIMAX con Eventos"""

from statsmodels.tsa.statespace.sarimax import SARIMAX
import pandas as pd
import numpy as np

# Matriz inicial para el modelo
df_sarimax = pd.DataFrame(
    index=serie_producto.index
)

df_sarimax["demanda_real"] = serie_producto

# Crear las variables de eventos
df_sarimax["Evento_Vacaciones"] = 0.0
df_sarimax["Evento_SemanaSanta"] = 0.0
df_sarimax["Evento_RuedaNegocios"] = 0.0
df_sarimax["Evento_Feria"] = 0.0

eventos = [
    {"año": 2025, "semana": 1,  "nombre": "Vacaciones"},
    {"año": 2024, "semana": 13, "nombre": "SemanaSanta"},
    {"año": 2025, "semana": 16, "nombre": "SemanaSanta"},
    {"año": 2025, "semana": 20, "nombre": "RuedaNegocios"},
    {"año": 2024, "semana": 38, "nombre": "Feria"},
    {"año": 2025, "semana": 39, "nombre": "Feria"}
]

for evento in eventos:

    fecha_evento = pd.to_datetime(
        f'{evento["año"]}-W{evento["semana"]:02d}-1',
        format="%G-W%V-%u"
    )

    columna_evento = f'Evento_{evento["nombre"]}'

    if fecha_evento in df_sarimax.index:
        df_sarimax.loc[
            fecha_evento,
            columna_evento
        ] = 1

def crear_intervencion(
    indice,
    fecha,
    tipo,
    decaimiento=0.7
):
    intervencion = pd.Series(
        0.0,
        index=indice
    )

    posicion = indice.get_loc(fecha)

    if tipo == "AO":
        # Efecto únicamente en la semana detectada
        intervencion.iloc[posicion] = 1.0

    elif tipo == "LS":
        # Cambio permanente desde la fecha detectada
        intervencion.iloc[posicion:] = 1.0

    elif tipo == "TC":
        # Efecto transitorio con reducción exponencial
        longitud = len(indice) - posicion

        intervencion.iloc[posicion:] = (
            decaimiento **
            np.arange(longitud)
        )

    return intervencion

fechas_eventos = []

for evento in eventos:
    fecha = pd.to_datetime(
        f'{evento["año"]}-W{evento["semana"]:02d}-1',
        format="%G-W%V-%u"
    )

    fechas_eventos.append(fecha)

# Incluir la semana anterior y posterior
fechas_protegidas = set()

for fecha in fechas_eventos:
    fechas_protegidas.add(fecha)
    fechas_protegidas.add(
        fecha - pd.Timedelta(weeks=1)
    )
    fechas_protegidas.add(
        fecha + pd.Timedelta(weeks=1)
    )

# Agregar las intervenciones detectadas
for columna in X_intervenciones.columns:
    df_sarimax[columna] = X_intervenciones[columna]

# Seleccionar solamente las columnas que se utilizarán
columnas_modelo = [
    "demanda_real",
    "Evento_Vacaciones",
    "Evento_SemanaSanta",
    "Evento_RuedaNegocios",
    "Evento_Feria"
]

# Agregar las columnas AO, LS o TC detectadas
columnas_modelo += [
    columna
    for columna in df_sarimax.columns
    if columna.startswith(("AO_", "LS_", "TC_"))
]

df_sarimax = df_sarimax[
    columnas_modelo
]

display(df_sarimax.head())
print(df_sarimax.columns.tolist())

df_sarimax["VlrUnitario_lag1"] = (
    df_exogenas_semanal["VlrUnitario"]
    .reindex(df_sarimax.index)
    .shift(1)
    .interpolate()
    .ffill()
    .bfill()
)

# Variables de eventos e intervenciones
variables_sin_precio = [
    columna
    for columna in df_sarimax.columns
    if columna != "demanda_real"
    and columna != "VlrUnitario_lag1"
]

# Las mismas variables más el precio
variables_con_precio = (
    variables_sin_precio +
    ["VlrUnitario_lag1"]
)

print("Variables sin precio:")
print(variables_sin_precio)

print("\nVariables con precio:")
print(variables_con_precio)

# Crear el precio rezagado una semana si todavía no existe
if "VlrUnitario_lag1" not in df_sarimax.columns:

    df_sarimax["VlrUnitario_lag1"] = (
        df_exogenas_semanal["VlrUnitario"]
        .reindex(df_sarimax.index)
        .shift(1)
    )

# Columnas de los eventos conocidos
columnas_eventos = [
    "Evento_Vacaciones",
    "Evento_SemanaSanta",
    "Evento_RuedaNegocios",
    "Evento_Feria"
]

# Columnas de intervenciones detectadas
columnas_intervenciones = [
    columna
    for columna in df_sarimax.columns
    if columna.startswith(("AO_", "LS_", "TC_"))
]

# Columnas definitivas para el modelado
columnas_modelo = (
    ["demanda_real", "VlrUnitario_lag1"] +
    columnas_eventos +
    columnas_intervenciones
)

# Crear el DataFrame definitivo
df_modelo_demanda = (
    df_sarimax[columnas_modelo]
    .reset_index()
)

# Asegurar que la fecha tenga el nombre correcto
df_modelo_demanda = df_modelo_demanda.rename(
    columns={
        df_modelo_demanda.columns[0]: "FECHA"
    }
)

# Ordenar cronológicamente
df_modelo_demanda["FECHA"] = pd.to_datetime(
    df_modelo_demanda["FECHA"]
)

df_modelo_demanda = (
    df_modelo_demanda
    .sort_values("FECHA")
    .reset_index(drop=True)
)

# Completar con cero las variables dummy
columnas_dummy = (
    columnas_eventos +
    columnas_intervenciones
)

df_modelo_demanda[columnas_dummy] = (
    df_modelo_demanda[columnas_dummy]
    .fillna(0)
    .astype(float)
)

# Completar el primer precio faltante
df_modelo_demanda["VlrUnitario_lag1"] = (
    df_modelo_demanda["VlrUnitario_lag1"]
    .bfill()
    .ffill()
)

# Revisar el resultado
print("Dimensiones:", df_modelo_demanda.shape)
print("Columnas utilizadas:")
print(df_modelo_demanda.columns.tolist())

display(df_modelo_demanda.head())

ruta_modelo = (
    "/content/drive/MyDrive/"
    "Trabajo de Grado JuanPablo/Datasets/"
    "df_modelo_demanda.csv"
)

df_modelo_demanda.to_csv(
    ruta_modelo,
    index=False
)

print(f"Dataset guardado en: {ruta_modelo}")
print(f"Cantidad de registros: {len(df_modelo_demanda)}")

from statsmodels.tsa.statespace.sarimax import SARIMAX
from sklearn.metrics import mean_absolute_error, mean_squared_error

from models.sarimax.model import (
    fit as fit_sarimax,
    forecast as forecast_sarimax,
)
from src.lead.forecasting.evaluation import evaluate_model
from src.lead.preprocessing.stockouts import impute_stockout_demand

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# Preparar el dataset
df_modelo = (
    df_modelo_demanda
    .set_index("FECHA")
    .sort_index()
)

df_modelo.index = pd.to_datetime(df_modelo.index)

# Definir la fecha de corte
fecha_corte = (
    df_modelo.index.max() -
    pd.DateOffset(months=6)
)

print("Fecha de corte:", fecha_corte)

columnas_eventos = [
    "Evento_Vacaciones",
    "Evento_SemanaSanta",
    "Evento_RuedaNegocios",
    "Evento_Feria"
]

columnas_intervenciones = [
    columna
    for columna in df_modelo.columns
    if columna.startswith(("AO_", "LS_", "TC_"))
]

intervenciones_validas = []

for columna in columnas_intervenciones:

    fechas_activas = df_modelo.index[
        df_modelo[columna].abs() > 0
    ]

    if (
        len(fechas_activas) > 0
        and fechas_activas.min() <= fecha_corte
    ):
        intervenciones_validas.append(columna)

    else:
        print(
            f"Excluida por ocurrir en prueba: {columna}"
        )

print("\nIntervenciones utilizadas:")
print(intervenciones_validas)

datos_entrenamiento = df_modelo[
    df_modelo.index <= fecha_corte
]

datos_prueba = df_modelo[
    df_modelo.index > fecha_corte
]

y_train = datos_entrenamiento["demanda_real"]
y_test = datos_prueba["demanda_real"]

print("Inicio entrenamiento:", y_train.index.min())
print("Final entrenamiento:", y_train.index.max())
print("Semanas de entrenamiento:", len(y_train))

print("\nInicio prueba:", y_test.index.min())
print("Final prueba:", y_test.index.max())
print("Semanas de prueba:", len(y_test))

variables_sin_precio = (
    columnas_eventos +
    intervenciones_validas
)

# Eliminar variables constantes durante el entrenamiento
variables_sin_precio = [
    columna
    for columna in variables_sin_precio
    if datos_entrenamiento[columna].nunique() > 1
]

X_train_sin_precio = datos_entrenamiento[
    variables_sin_precio
].astype(float)

X_test_sin_precio = datos_prueba[
    variables_sin_precio
].astype(float)

print("Variables sin precio:")
print(variables_sin_precio)

media_precio = (
    datos_entrenamiento["VlrUnitario_lag1"]
    .mean()
)

desviacion_precio = (
    datos_entrenamiento["VlrUnitario_lag1"]
    .std()
)

if desviacion_precio == 0:
    raise ValueError(
        "El precio no cambia durante el entrenamiento."
    )

df_modelo["Precio_lag1_std"] = (
    df_modelo["VlrUnitario_lag1"] -
    media_precio
) / desviacion_precio

# Volver a separar después de crear el precio estandarizado
datos_entrenamiento = df_modelo[
    df_modelo.index <= fecha_corte
]

datos_prueba = df_modelo[
    df_modelo.index > fecha_corte
]

variables_con_precio = (
    variables_sin_precio +
    ["Precio_lag1_std"]
)

X_train_con_precio = datos_entrenamiento[
    variables_con_precio
].astype(float)

X_test_con_precio = datos_prueba[
    variables_con_precio
].astype(float)

modelo_sin_precio = fit_sarimax(
    y_train,
    exog=X_train_sin_precio,
    order=(0, 0, 1),
    seasonal_order=(0, 0, 0, 0),
    trend="c",
    enforce_stationarity=False,
    enforce_invertibility=False
)

prediccion_sin_precio = forecast_sarimax(
    modelo_sin_precio,
    len(y_test),
    exog=X_test_sin_precio,
    index=y_test.index,
)

modelo_con_precio = fit_sarimax(
    y_train,
    exog=X_train_con_precio,
    order=(0, 0, 1),
    seasonal_order=(0, 0, 0, 0),
    trend="c",
    enforce_stationarity=False,
    enforce_invertibility=False
)

prediccion_con_precio = forecast_sarimax(
    modelo_con_precio,
    len(y_test),
    exog=X_test_con_precio,
    index=y_test.index,
)

def evaluar_sarimax(
    nombre,
    real,
    prediccion,
    modelo
):
    return evaluate_model(nombre, real, prediccion, modelo)

resultados = [
    evaluar_sarimax(
        "SARIMAX sin precio",
        y_test,
        prediccion_sin_precio,
        modelo_sin_precio
    ),
    evaluar_sarimax(
        "SARIMAX con precio",
        y_test,
        prediccion_con_precio,
        modelo_con_precio
    )
]

tabla_comparacion_sarimax = (
    pd.DataFrame(resultados)
    .sort_values(["RMSE", "MAE"])
    .reset_index(drop=True)
)

plt.figure(figsize=(16, 8))

# Entrenamiento
plt.plot(
    y_train.index,
    y_train,
    color="blue",
    linewidth=1.5,
    label="Entrenamiento"
)

# Valores reales de prueba
plt.plot(
    y_test.index,
    y_test,
    color="black",
    linewidth=2,
    marker="o",
    label="Demanda real de prueba"
)

# SARIMAX sin precio
plt.plot(
    prediccion_sin_precio.index,
    prediccion_sin_precio,
    color="orange",
    linestyle="--",
    linewidth=2,
    marker="o",
    label="SARIMAX sin precio"
)

# SARIMAX con precio
plt.plot(
    prediccion_con_precio.index,
    prediccion_con_precio,
    color="red",
    linestyle="--",
    linewidth=2,
    marker="o",
    label="SARIMAX con precio"
)

plt.axvline(
    fecha_corte,
    color="gray",
    linestyle="--",
    label="Inicio de la prueba"
)

plt.title(
    f"Comparación SARIMAX con y sin precio\n"
    f"{PRODUCTO_BASE}"
)
plt.xlabel("Fecha")
plt.ylabel("Demanda real")
plt.grid(True, alpha=0.3)
plt.legend()
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

display(
    tabla_comparacion_sarimax.style.format({
        "MAE": "{:,.2f}",
        "RMSE": "{:,.2f}",
        "WAPE_%": "{:.2f}%",
        "AIC": "{:,.2f}"
    })
)

"""El SARIMAX sin precio es el mejor:

MAE = 162,81: se equivoca, en promedio, en unas 163 unidades semanales.
RMSE = 192,65: existen algunas semanas con errores mayores.
WAPE = 27,13 %: por cada 100 unidades demandadas, acumula aproximadamente 27 unidades de error.

Aunque el modelo con precio tiene menor AIC, obtiene peores métricas en prueba. Por tanto, el precio mejora el ajuste histórico, pero no la predicción. Se recomienda utilizar el SARIMAX sin precio.

# SARIMAX (EVENTOS + QUIEBRES)
"""

# Conservar solamente quiebres anteriores a la semana 52
puntos_quiebre_validos = puntos_quiebre[
    ~puntos_quiebre["Semana"].isin([52, 53])
]

print("Quiebres excluidos de final de año:")

display(
    puntos_quiebre[
        puntos_quiebre["Semana"].isin([52, 53])
    ][
        ["FECHA", "Año", "Semana", "demanda_real"]
    ]
)

print("Quiebres que se conservarán:")

display(
    puntos_quiebre_validos[
        ["FECHA", "Año", "Semana", "demanda_real"]
    ]
)

# Fechas semanales de los quiebres válidos
fechas_quiebres_validos = set(
    puntos_quiebre_validos["FECHA"]
)

# Crear la variable dummy en el dataset de modelado
df_modelo_demanda["Evento_QuiebreInventario"] = (
    df_modelo_demanda["FECHA"]
    .isin(fechas_quiebres_validos)
    .astype(int)
)

columnas_eventos = [
    "Evento_Vacaciones",
    "Evento_SemanaSanta",
    "Evento_RuedaNegocios",
    "Evento_Feria",
    "Evento_QuiebreInventario"
]

columnas_intervenciones = [
    columna
    for columna in df_modelo_demanda.columns
    if columna.startswith(("AO_", "LS_", "TC_"))
]

variables_sin_precio = (
    columnas_eventos +
    columnas_intervenciones
)

variables_con_precio = (
    variables_sin_precio +
    ["VlrUnitario_lag1"]
)

print("Variables sin precio:")
print(variables_sin_precio)

print("\nVariables con precio:")
print(variables_con_precio)

ruta_modelo = (
    "/content/drive/MyDrive/"
    "Trabajo de Grado JuanPablo/Datasets/"
    "df_modelo_demanda.csv"
)

df_modelo_demanda.to_csv(
    ruta_modelo,
    index=False
)

print(f"Dataset actualizado: {ruta_modelo}")

df_modelo = (
    df_modelo_demanda
    .set_index("FECHA")
    .sort_index()
)

df_modelo.index = pd.to_datetime(
    df_modelo.index
)

# Mantener la misma fecha de corte
fecha_corte = (
    df_modelo.index.max() -
    pd.DateOffset(months=6)
)

datos_entrenamiento = df_modelo[
    df_modelo.index <= fecha_corte
]

datos_prueba = df_modelo[
    df_modelo.index > fecha_corte
]

y_train = datos_entrenamiento["demanda_real"]
y_test = datos_prueba["demanda_real"]

eventos_base = [
    "Evento_Vacaciones",
    "Evento_SemanaSanta",
    "Evento_RuedaNegocios",
    "Evento_Feria"
]

# Usar únicamente intervenciones detectadas en entrenamiento
columnas_intervenciones = [
    columna
    for columna in df_modelo.columns
    if columna.startswith(("AO_", "LS_", "TC_"))
]

intervenciones_validas = []

for columna in columnas_intervenciones:

    fechas_activas = df_modelo.index[
        df_modelo[columna].abs() > 0
    ]

    if (
        len(fechas_activas) > 0
        and fechas_activas.min() <= fecha_corte
    ):
        intervenciones_validas.append(columna)

# Variables del nuevo modelo
variables_con_quiebre = (
    eventos_base +
    intervenciones_validas +
    ["Evento_QuiebreInventario"]
)

# Eliminar variables constantes en entrenamiento
variables_con_quiebre = [
    columna
    for columna in variables_con_quiebre
    if datos_entrenamiento[columna].nunique() > 1
]

X_train_con_quiebre = datos_entrenamiento[
    variables_con_quiebre
].astype(float)

X_test_con_quiebre = datos_prueba[
    variables_con_quiebre
].astype(float)

print("Variables utilizadas:")
print(variables_con_quiebre)

modelo_con_quiebre = fit_sarimax(
    y_train,
    exog=X_train_con_quiebre,
    order=(0, 0, 1),
    seasonal_order=(0, 0, 0, 0),
    trend="c",
    enforce_stationarity=False,
    enforce_invertibility=False,
)

prediccion_con_quiebre = forecast_sarimax(
    modelo_con_quiebre,
    len(y_test),
    exog=X_test_con_quiebre,
    index=y_test.index,
)

resultado_con_quiebre = evaluar_sarimax(
    "SARIMAX con quiebres",
    y_test,
    prediccion_con_quiebre,
    modelo_con_quiebre
)

display(
    pd.DataFrame(
        [resultado_con_quiebre]
    ).style.format({
        "MAE": "{:,.2f}",
        "RMSE": "{:,.2f}",
        "WAPE_%": "{:.2f}%",
        "AIC": "{:,.2f}"
    })
)

comparacion_modelos = pd.DataFrame([
    evaluar_sarimax(
        "SARIMAX sin precio",
        y_test,
        prediccion_sin_precio,
        modelo_sin_precio
    ),

    evaluar_sarimax(
        "SARIMAX con precio",
        y_test,
        prediccion_con_precio,
        modelo_con_precio
    ),

    evaluar_sarimax(
        "SARIMAX con quiebres",
        y_test,
        prediccion_con_quiebre,
        modelo_con_quiebre
    )
])

comparacion_modelos = (
    comparacion_modelos
    .sort_values(["RMSE", "MAE"])
    .reset_index(drop=True)
)

display(
    comparacion_modelos.style.format({
        "MAE": "{:,.2f}",
        "RMSE": "{:,.2f}",
        "WAPE_%": "{:.2f}%",
        "AIC": "{:,.2f}"
    })
)

plt.figure(figsize=(17, 8))

plt.plot(
    y_train.index,
    y_train,
    color="blue",
    linewidth=1.3,
    label="Entrenamiento"
)

plt.plot(
    y_test.index,
    y_test,
    color="black",
    linewidth=2,
    marker="o",
    label="Demanda real de prueba"
)

plt.plot(
    prediccion_sin_precio.index,
    prediccion_sin_precio,
    color="orange",
    linestyle="--",
    linewidth=2,
    label="SARIMAX sin precio"
)

plt.plot(
    prediccion_con_precio.index,
    prediccion_con_precio,
    color="red",
    linestyle="--",
    linewidth=2,
    label="SARIMAX con precio"
)

plt.plot(
    prediccion_con_quiebre.index,
    prediccion_con_quiebre,
    color="green",
    linestyle="--",
    linewidth=2,
    marker="o",
    label="SARIMAX con quiebres"
)

# Señalar quiebres del periodo de prueba
quiebres_prueba = datos_prueba[
    datos_prueba["Evento_QuiebreInventario"] == 1
]

plt.scatter(
    quiebres_prueba.index,
    y_test.loc[quiebres_prueba.index],
    color="purple",
    s=100,
    zorder=6,
    label="Quiebre observado"
)

plt.axvline(
    fecha_corte,
    color="gray",
    linestyle="--",
    label="Inicio de la prueba"
)

plt.title(
    f"Comparación de modelos SARIMAX\n"
    f"{PRODUCTO_BASE}"
)
plt.xlabel("Fecha")
plt.ylabel("Demanda real")
plt.grid(True, alpha=0.3)
plt.legend()
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

display(
    comparacion_modelos.style.format({
        "MAE": "{:,.2f}",
        "RMSE": "{:,.2f}",
        "WAPE_%": "{:.2f}%",
        "AIC": "{:,.2f}"
    })
)

"""# Imputacion de demanda con quiebre de inventario"""

# Componentes semanales de la demanda
df_componentes_semanales = (
    datos_producto
    .set_index("FECHA")
    .resample("W-MON")
    .agg({
        "Facturado": "sum",
        "BackOrder": "sum"
    })
)

# Preparar base de imputación
df_imputacion = (
    df_modelo_demanda
    .set_index("FECHA")
    .sort_index()
)

df_imputacion = df_imputacion.join(
    df_componentes_semanales,
    how="left"
)

df_imputacion[
    ["Facturado", "BackOrder"]
] = df_imputacion[
    ["Facturado", "BackOrder"]
].fillna(0)

# Revisar las semanas con quiebre
display(
    df_imputacion[
        df_imputacion["Evento_QuiebreInventario"] == 1
    ][
        [
            "demanda_real",
            "Facturado",
            "BackOrder",
            "Evento_QuiebreInventario"
        ]
    ]
)

columnas_exogenas_imputacion = [
    columna
    for columna in df_imputacion.columns
    if (
        columna.startswith("Evento_")
        and columna != "Evento_QuiebreInventario"
    )
    or columna.startswith(("AO_", "LS_", "TC_"))
]

# Evitar intervenciones detectadas precisamente en un quiebre
intervenciones_validas = []

for columna in columnas_exogenas_imputacion:

    if columna.startswith(("AO_", "LS_", "TC_")):

        fechas_activas = df_imputacion.index[
            df_imputacion[columna].abs() > 0
        ]

        if (
            len(fechas_activas) > 0
            and df_imputacion.loc[
                fechas_activas.min(),
                "Evento_QuiebreInventario"
            ] == 1
        ):
            continue

    intervenciones_validas.append(columna)

columnas_exogenas_imputacion = intervenciones_validas

X_imputacion = df_imputacion[
    columnas_exogenas_imputacion
].astype(float)

print("Variables utilizadas:")
print(columnas_exogenas_imputacion)

from sklearn.metrics import mean_absolute_error, mean_squared_error

rng = np.random.default_rng(123)

y_completa = df_imputacion["demanda_real"].astype(float)

mascara_quiebre = (
    df_imputacion["Evento_QuiebreInventario"] == 1
)

# Semanas normales disponibles para validación
fechas_validacion_posibles = y_completa.index[
    (~mascara_quiebre)
    &
    (y_completa > 0)
][2:-2]

numero_ocultar = min(
    max(5, int(mascara_quiebre.sum())),
    len(fechas_validacion_posibles) // 4
)

resultados_validacion = []

for repeticion in range(10):

    fechas_ocultas = rng.choice(
        fechas_validacion_posibles,
        size=numero_ocultar,
        replace=False
    )

    fechas_ocultas = pd.DatetimeIndex(
        fechas_ocultas
    )

    y_enmascarada = y_completa.copy()
    y_enmascarada.loc[fechas_ocultas] = np.nan

    # Box-Jenkins con observaciones faltantes
    modelo_validacion = SARIMAX(
        y_enmascarada,
        exog=X_imputacion,
        order=(0, 0, 1),
        seasonal_order=(0, 0, 0, 0),
        trend="c",
        enforce_stationarity=False,
        enforce_invertibility=False
    ).fit(disp=False)

    prediccion_validacion = (
        modelo_validacion
        .get_prediction(
            start=0,
            end=len(y_enmascarada) - 1,
            information_set="smoothed"
        )
        .predicted_mean
        .clip(lower=0)
    )

    real = y_completa.loc[fechas_ocultas]
    estimado = prediccion_validacion.loc[
        fechas_ocultas
    ]

    resultados_validacion.append({
        "repeticion": repeticion + 1,
        "MAE": mean_absolute_error(
            real,
            estimado
        ),
        "RMSE": np.sqrt(
            mean_squared_error(
                real,
                estimado
            )
        ),
        "WAPE_%": (
            np.abs(real - estimado).sum()
            / np.abs(real).sum()
        ) * 100
    })

tabla_validacion_imputacion = pd.DataFrame(
    resultados_validacion
)

display(
    tabla_validacion_imputacion.describe().loc[
        ["mean", "std", "min", "max"]
    ].style.format({
        "MAE": "{:,.2f}",
        "RMSE": "{:,.2f}",
        "WAPE_%": "{:.2f}%"
    })
)

# Ocultar todas las semanas con quiebre
y_sin_quiebres = y_completa.copy()

y_sin_quiebres.loc[
    mascara_quiebre
] = np.nan

# Ajustar el modelo ignorando las semanas censuradas y suavizar la estimación.
resultado_imputacion = impute_stockout_demand(
    y_completa,
    mascara_quiebre,
    exog=X_imputacion,
)

modelo_imputacion = resultado_imputacion.model
demanda_contrafactual = resultado_imputacion.counterfactual
limite_inferior = resultado_imputacion.lower_bound
limite_superior = resultado_imputacion.upper_bound

df_imputacion["demanda_observada_original"] = (
    y_completa
)

df_imputacion["demanda_contrafactual"] = (
    demanda_contrafactual
)

df_imputacion["demanda_imputada"] = (
    y_completa
)

# Quiebres con demanda igual a cero
mascara_quiebre_cero = (
    mascara_quiebre
    &
    (y_completa == 0)
)

df_imputacion.loc[
    mascara_quiebre_cero,
    "demanda_imputada"
] = demanda_contrafactual.loc[
    mascara_quiebre_cero
]

# Quiebres con demanda positiva:
# lo observado funciona como límite inferior
mascara_quiebre_positivo = (
    mascara_quiebre
    &
    (y_completa > 0)
)

df_imputacion.loc[
    mascara_quiebre_positivo,
    "demanda_imputada"
] = np.maximum(
    y_completa.loc[
        mascara_quiebre_positivo
    ],
    demanda_contrafactual.loc[
        mascara_quiebre_positivo
    ]
)

# Demanda potencialmente omitida
df_imputacion["demanda_omitida_estimada"] = (
    df_imputacion["demanda_imputada"]
    -
    df_imputacion["demanda_observada_original"]
).clip(lower=0)

# Intervalos de referencia
df_imputacion["limite_inferior"] = limite_inferior
df_imputacion["limite_superior"] = limite_superior

# Método utilizado
df_imputacion["metodo_imputacion"] = "Sin imputación"

df_imputacion.loc[
    mascara_quiebre_cero,
    "metodo_imputacion"
] = "SARIMAX-Kalman: demanda cero"

df_imputacion.loc[
    mascara_quiebre_positivo,
    "metodo_imputacion"
] = "Contrafactual restringido"

columnas_revision = [
    "demanda_observada_original",
    "Facturado",
    "BackOrder",
    "demanda_contrafactual",
    "demanda_imputada",
    "demanda_omitida_estimada",
    "limite_inferior",
    "limite_superior",
    "metodo_imputacion"
]

display(
    df_imputacion.loc[
        mascara_quiebre,
        columnas_revision
    ].style.format({
        "demanda_observada_original": "{:,.2f}",
        "Facturado": "{:,.2f}",
        "BackOrder": "{:,.2f}",
        "demanda_contrafactual": "{:,.2f}",
        "demanda_imputada": "{:,.2f}",
        "demanda_omitida_estimada": "{:,.2f}",
        "limite_inferior": "{:,.2f}",
        "limite_superior": "{:,.2f}"
    })
)

plt.figure(figsize=(17, 8))

plt.plot(
    df_imputacion.index,
    df_imputacion["demanda_observada_original"],
    color="blue",
    linewidth=2,
    marker="o",
    markersize=3,
    label="Demanda observada"
)

plt.scatter(
    df_imputacion.index[mascara_quiebre],
    df_imputacion.loc[
        mascara_quiebre,
        "demanda_imputada"
    ],
    color="red",
    s=110,
    zorder=6,
    label="Demanda imputada en quiebres"
)

# Unir visualmente el valor observado y el imputado
for fecha in df_imputacion.index[
    mascara_quiebre
]:
    plt.plot(
        [
            fecha,
            fecha
        ],
        [
            df_imputacion.loc[
                fecha,
                "demanda_observada_original"
            ],
            df_imputacion.loc[
                fecha,
                "demanda_imputada"
            ]
        ],
        color="red",
        linestyle=":",
        alpha=0.7
    )

plt.title(
    f"Demanda observada e imputada durante quiebres\n"
    f"{PRODUCTO_BASE}"
)
plt.xlabel("Fecha")
plt.ylabel("Demanda real")
plt.grid(True, alpha=0.3)
plt.legend()
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

df_modelo_demanda_imputada = (
    df_imputacion
    .reset_index()
    .rename(
        columns={"index": "FECHA"}
    )
)

# La demanda que se utilizará posteriormente
df_modelo_demanda_imputada["demanda_real"] = (
    df_modelo_demanda_imputada[
        "demanda_imputada"
    ]
)

from statsmodels.tsa.statespace.sarimax import SARIMAX
from sklearn.metrics import mean_absolute_error, mean_squared_error

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

df_modelo_nuevo = (
    df_modelo_demanda_imputada
    .set_index("FECHA")
    .sort_index()
)

df_modelo_nuevo.index = pd.to_datetime(
    df_modelo_nuevo.index
)

# Usar la demanda imputada como objetivo
df_modelo_nuevo["demanda_real"] = (
    df_modelo_nuevo["demanda_imputada"]
)

fecha_corte = (
    df_modelo_nuevo.index.max() -
    pd.DateOffset(months=6)
)

datos_train = df_modelo_nuevo[
    df_modelo_nuevo.index <= fecha_corte
]

datos_test = df_modelo_nuevo[
    df_modelo_nuevo.index > fecha_corte
]

y_train = datos_train["demanda_real"]
y_test = datos_test["demanda_real"]

print("Entrenamiento:")
print(y_train.index.min(), "-", y_train.index.max())
print("Semanas:", len(y_train))

print("\nPrueba:")
print(y_test.index.min(), "-", y_test.index.max())
print("Semanas:", len(y_test))

columnas_eventos_quiebres = [
    "Evento_Vacaciones",
    "Evento_SemanaSanta",
    "Evento_RuedaNegocios",
    "Evento_Feria",
    "Evento_QuiebreInventario"
]

columnas_intervenciones = [
    columna
    for columna in df_modelo_nuevo.columns
    if columna.startswith(("AO_", "LS_", "TC_"))
]

# Evitar intervenciones que empiezan en prueba
intervenciones_validas = []

for columna in columnas_intervenciones:

    fechas_activas = df_modelo_nuevo.index[
        df_modelo_nuevo[columna].abs() > 0
    ]

    if (
        len(fechas_activas) > 0
        and fechas_activas.min() <= fecha_corte
    ):
        intervenciones_validas.append(columna)

variables_base = (
    columnas_eventos_quiebres +
    intervenciones_validas
)

# Eliminar variables constantes en entrenamiento
variables_base = [
    columna
    for columna in variables_base
    if datos_train[columna].nunique() > 1
]

print("Eventos e intervenciones utilizadas:")
print(variables_base)

media_precio = (
    datos_train["VlrUnitario_lag1"].mean()
)

desviacion_precio = (
    datos_train["VlrUnitario_lag1"].std()
)

if desviacion_precio == 0:
    raise ValueError(
        "VlrUnitario_lag1 no presenta variación."
    )

df_modelo_nuevo["Precio_lag1_std"] = (
    df_modelo_nuevo["VlrUnitario_lag1"] -
    media_precio
) / desviacion_precio

# Actualizar entrenamiento y prueba
datos_train = df_modelo_nuevo[
    df_modelo_nuevo.index <= fecha_corte
]

datos_test = df_modelo_nuevo[
    df_modelo_nuevo.index > fecha_corte
]

# Modelo 1: eventos y quiebres
variables_sin_precio = variables_base

X_train_sin_precio = datos_train[
    variables_sin_precio
].astype(float)

X_test_sin_precio = datos_test[
    variables_sin_precio
].astype(float)

# Modelo 2: eventos, quiebres y precio
variables_con_precio = (
    variables_base +
    ["Precio_lag1_std"]
)

X_train_con_precio = datos_train[
    variables_con_precio
].astype(float)

X_test_con_precio = datos_test[
    variables_con_precio
].astype(float)

sarimax_sin_precio = fit_sarimax(
    y_train,
    exog=X_train_sin_precio,
    order=(0, 0, 1),
    seasonal_order=(0, 0, 0, 0),
    trend="c",
    enforce_stationarity=False,
    enforce_invertibility=False,
)

pred_sin_precio = forecast_sarimax(
    sarimax_sin_precio,
    len(y_test),
    exog=X_test_sin_precio,
    index=y_test.index,
)

sarimax_con_precio = fit_sarimax(
    y_train,
    exog=X_train_con_precio,
    order=(0, 0, 1),
    seasonal_order=(0, 0, 0, 0),
    trend="c",
    enforce_stationarity=False,
    enforce_invertibility=False,
)

pred_con_precio = forecast_sarimax(
    sarimax_con_precio,
    len(y_test),
    exog=X_test_con_precio,
    index=y_test.index,
)

def evaluar_modelo(nombre, real, prediccion, modelo):
    return evaluate_model(nombre, real, prediccion, modelo)

tabla_resultados_nuevos = pd.DataFrame([
    evaluar_modelo(
        "SARIMAX eventos y quiebres",
        y_test,
        pred_sin_precio,
        sarimax_sin_precio
    ),
    evaluar_modelo(
        "SARIMAX eventos, quiebres y precio",
        y_test,
        pred_con_precio,
        sarimax_con_precio
    )
])

tabla_resultados_nuevos = (
    tabla_resultados_nuevos
    .sort_values(["RMSE", "MAE"])
    .reset_index(drop=True)
)

display(
    tabla_resultados_nuevos.style.format({
        "MAE": "{:,.2f}",
        "RMSE": "{:,.2f}",
        "WAPE_%": "{:.2f}%",
        "AIC": "{:,.2f}"
    })
)

plt.figure(figsize=(17, 8))

plt.plot(
    y_train.index,
    y_train,
    color="blue",
    linewidth=1.4,
    label="Entrenamiento"
)

plt.plot(
    y_test.index,
    y_test,
    color="black",
    linewidth=2,
    marker="o",
    label="Demanda imputada de prueba"
)

plt.plot(
    pred_sin_precio.index,
    pred_sin_precio,
    color="green",
    linestyle="--",
    linewidth=2,
    marker="o",
    label="SARIMAX eventos y quiebres"
)

plt.plot(
    pred_con_precio.index,
    pred_con_precio,
    color="red",
    linestyle="--",
    linewidth=2,
    marker="o",
    label="SARIMAX eventos, quiebres y precio"
)

plt.axvline(
    fecha_corte,
    color="gray",
    linestyle="--",
    label="Inicio de la prueba"
)

plt.title(
    f"SARIMAX sobre demanda imputada\n{PRODUCTO_BASE}"
)
plt.xlabel("Fecha")
plt.ylabel("Demanda real imputada")
plt.grid(True, alpha=0.3)
plt.legend()
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

display(
    comparacion_modelos.style.format({
        "MAE": "{:,.2f}",
        "RMSE": "{:,.2f}",
        "WAPE_%": "{:.2f}%",
        "AIC": "{:,.2f}"
    })
)

display(
    tabla_resultados_nuevos.style.format({
        "MAE": "{:,.2f}",
        "RMSE": "{:,.2f}",
        "WAPE_%": "{:.2f}%",
        "AIC": "{:,.2f}"
    })
)

# Último modelo: eventos y quiebres, sin precio
resultado = sarimax_sin_precio

parametros = resultado.params
intervalos = resultado.conf_int(alpha=0.05)
valores_p = resultado.pvalues

tabla_parametros = pd.DataFrame({
    "parametro": parametros.index,
    "coeficiente": parametros.values,
    "limite_inferior_95": intervalos.iloc[:, 0].values,
    "limite_superior_95": intervalos.iloc[:, 1].values,
    "valor_p": valores_p.values
})

tabla_parametros["significativo_5pct"] = np.where(
    tabla_parametros["valor_p"] < 0.05,
    "Sí",
    "No"
)

tabla_parametros["efecto"] = np.select(
    [
        tabla_parametros["coeficiente"] > 0,
        tabla_parametros["coeficiente"] < 0
    ],
    [
        "Aumenta la demanda",
        "Disminuye la demanda"
    ],
    default="Sin efecto"
)

display(
    tabla_parametros.style.format({
        "coeficiente": "{:,.2f}",
        "limite_inferior_95": "{:,.2f}",
        "limite_superior_95": "{:,.2f}",
        "valor_p": "{:.4f}"
    })
)

# Parámetros explicativos; excluir varianza residual
mascara_graficar = parametros.index != "sigma2"

parametros_grafico = parametros.loc[mascara_graficar]
intervalos_grafico = intervalos.loc[mascara_graficar]
pvalues_grafico = valores_p.loc[mascara_graficar]

errores_inferiores = (
    parametros_grafico -
    intervalos_grafico.iloc[:, 0]
).clip(lower=0)

errores_superiores = (
    intervalos_grafico.iloc[:, 1] -
    parametros_grafico
).clip(lower=0)

# Verde: significativo; gris: no significativo
colores = [
    "seagreen" if valor_p < 0.05 else "lightgray"
    for valor_p in pvalues_grafico
]

fig, ax = plt.subplots(figsize=(16, 8))

barras = ax.bar(
    parametros_grafico.index,
    parametros_grafico.values,
    color=colores,
    edgecolor="black",
    alpha=0.85
)

ax.errorbar(
    parametros_grafico.index,
    parametros_grafico.values,
    yerr=[
        errores_inferiores.values,
        errores_superiores.values
    ],
    fmt="none",
    ecolor="black",
    elinewidth=1.3,
    capsize=5,
    label="Intervalo de confianza del 95 %"
)

ax.axhline(
    y=0,
    color="red",
    linestyle="--",
    linewidth=1.2
)

# Mostrar coeficiente y valor p
for barra, coeficiente, valor_p in zip(
    barras,
    parametros_grafico.values,
    pvalues_grafico.values
):
    desplazamiento = 5 if coeficiente >= 0 else -18

    ax.annotate(
        f"{coeficiente:,.1f}\np={valor_p:.3f}",
        xy=(
            barra.get_x() + barra.get_width() / 2,
            coeficiente
        ),
        xytext=(0, desplazamiento),
        textcoords="offset points",
        ha="center",
        va="bottom" if coeficiente >= 0 else "top",
        fontsize=9
    )

ax.set_title(
    "Parámetros del SARIMAX con eventos y quiebres\n"
    f"{PRODUCTO_BASE}"
)
ax.set_xlabel("Parámetros")
ax.set_ylabel("Coeficiente estimado")
ax.tick_params(axis="x", rotation=45)
ax.grid(axis="y", alpha=0.3)

from matplotlib.patches import Patch

leyenda = [
    Patch(
        facecolor="seagreen",
        edgecolor="black",
        label="Significativo (p < 0.05)"
    ),
    Patch(
        facecolor="lightgray",
        edgecolor="black",
        label="No significativo (p ≥ 0.05)"
    )
]

ax.legend(
    handles=leyenda,
    title="Significancia estadística"
)

plt.tight_layout()
plt.show()

tabla_eventos_quiebres = tabla_parametros[
    tabla_parametros["parametro"].str.startswith("Evento_")
].copy()

display(
    tabla_eventos_quiebres.style.format({
        "coeficiente": "{:,.2f}",
        "limite_inferior_95": "{:,.2f}",
        "limite_superior_95": "{:,.2f}",
        "valor_p": "{:.4f}"
    })
)

"""# MODELADO EN SERIE"""

import warnings
import numpy as np
import pandas as pd

from statsmodels.tsa.statespace.sarimax import SARIMAX
from sklearn.metrics import mean_absolute_error, mean_squared_error
from tqdm.auto import tqdm

warnings.filterwarnings("ignore")

eventos_globales = [
    {"año": 2025, "semana": 1,  "nombre": "Vacaciones"},
    {"año": 2024, "semana": 13, "nombre": "SemanaSanta"},
    {"año": 2025, "semana": 16, "nombre": "SemanaSanta"},
    {"año": 2025, "semana": 20, "nombre": "RuedaNegocios"},
    {"año": 2024, "semana": 37, "nombre": "Feria"},
    {"año": 2025, "semana": 39, "nombre": "Feria"}
]

for evento in eventos_globales:
    evento["fecha"] = pd.to_datetime(
        f'{evento["año"]}-W{evento["semana"]:02d}-1',
        format="%G-W%V-%u"
    )

df_productos["FECHA"] = pd.to_datetime(
    df_productos["FECHA"]
)

df_quiebres["FechaInicial"] = pd.to_datetime(
    df_quiebres["FechaInicial"],
    errors="coerce"
)

df_quiebres["FechaFinal"] = pd.to_datetime(
    df_quiebres["FechaFinal"],
    errors="coerce"
)

# Misma fecha de corte para todos los productos
fecha_corte_global = (
    df_productos["FECHA"].max() -
    pd.DateOffset(months=6)
)

print("Fecha de corte global:", fecha_corte_global)

def procesar_producto(
    id_producto,
    datos_producto,
    df_quiebres,
    fecha_corte
):
    nombre_producto = (
        datos_producto["Producto"]
        .dropna()
        .iloc[0]
    )

    # Crear serie semanal
    semanal = (
        datos_producto
        .set_index("FECHA")
        .resample("W-MON")
        .agg({
            "Facturado": "sum",
            "BackOrder": "sum",
            "VlrUnitario": "mean"
        })
    )

    semanal["demanda_observada"] = (
        semanal["Facturado"] +
        semanal["BackOrder"]
    )

    # Completar el precio
    semanal["VlrUnitario"] = (
        semanal["VlrUnitario"]
        .interpolate()
        .ffill()
        .bfill()
    )

    # Requerir suficientes semanas
    if len(semanal) < 70:
        raise ValueError(
            f"Solo tiene {len(semanal)} semanas"
        )

    # Crear dummies de eventos
    for nombre in [
        "Vacaciones",
        "SemanaSanta",
        "RuedaNegocios",
        "Feria"
    ]:
        semanal[f"Evento_{nombre}"] = 0.0

    for evento in eventos_globales:

        if evento["fecha"] in semanal.index:
            semanal.loc[
                evento["fecha"],
                f'Evento_{evento["nombre"]}'
            ] = 1.0

    # Crear dummy de quiebre
    semanal["Evento_QuiebreInventario"] = 0.0

    quiebres_producto = df_quiebres[
        df_quiebres["IDProductos"].astype(str)
        == str(id_producto)
    ]

    for fecha_semana in semanal.index:

        año = fecha_semana.isocalendar().year
        numero_semana = fecha_semana.isocalendar().week

        # Excluir semanas finales
        if numero_semana in [52, 53]:
            continue

        inicio_semana = (
            fecha_semana -
            pd.Timedelta(weeks=1)
        )

        existe_quiebre = (
            (
                quiebres_producto["FechaInicial"]
                <= fecha_semana
            )
            &
            (
                quiebres_producto["FechaFinal"]
                > inicio_semana
            )
        ).any()

        if existe_quiebre:
            semanal.loc[
                fecha_semana,
                "Evento_QuiebreInventario"
            ] = 1.0

    columnas_eventos = [
        "Evento_Vacaciones",
        "Evento_SemanaSanta",
        "Evento_RuedaNegocios",
        "Evento_Feria"
    ]

    # --------------------------------------------------
    # Imputación contrafactual de los quiebres
    # --------------------------------------------------

    y_observada = semanal[
        "demanda_observada"
    ].astype(float)

    mascara_quiebre = (
        semanal["Evento_QuiebreInventario"] == 1
    )

    # Eliminar eventos constantes
    eventos_imputacion = [
        columna
        for columna in columnas_eventos
        if semanal[columna].nunique() > 1
    ]

    X_imputacion = (
        semanal[eventos_imputacion].astype(float)
        if eventos_imputacion
        else None
    )

    resultado_imputacion = impute_stockout_demand(
        y_observada,
        mascara_quiebre,
        exog=X_imputacion,
    )
    demanda_contrafactual = resultado_imputacion.counterfactual

    # Mantener al menos la demanda observada
    semanal["demanda_real"] = y_observada

    semanal.loc[
        mascara_quiebre,
        "demanda_real"
    ] = np.maximum(
        y_observada.loc[mascara_quiebre],
        demanda_contrafactual.loc[mascara_quiebre]
    )

    # Precio rezagado
    semanal["Precio_lag1"] = (
        semanal["VlrUnitario"].shift(1)
    )

    semanal = semanal.dropna(
        subset=["Precio_lag1"]
    )

    # --------------------------------------------------
    # Entrenamiento y prueba
    # --------------------------------------------------

    train = semanal[
        semanal.index <= fecha_corte
    ]

    test = semanal[
        semanal.index > fecha_corte
    ]

    if len(train) < 40 or len(test) < 8:
        raise ValueError(
            "No tiene suficientes datos de entrenamiento o prueba"
        )

    y_train = train["demanda_real"]
    y_test = test["demanda_real"]

    variables_base = (
        columnas_eventos +
        ["Evento_QuiebreInventario"]
    )

    # Eliminar variables constantes en entrenamiento
    variables_base = [
        columna
        for columna in variables_base
        if train[columna].nunique() > 1
    ]

    X_train_base = train[
        variables_base
    ].astype(float)

    X_test_base = test[
        variables_base
    ].astype(float)

    # Estandarizar precio con entrenamiento
    media_precio = train["Precio_lag1"].mean()
    desviacion_precio = train["Precio_lag1"].std()

    modelos = []

    # --------------------------------------------------
    # Modelo sin precio
    # --------------------------------------------------

    modelo_sin_precio = fit_sarimax(
        y_train,
        exog=X_train_base,
        order=(0, 0, 1),
        seasonal_order=(0, 0, 0, 0),
        trend="c",
        enforce_stationarity=False,
        enforce_invertibility=False,
    )

    pred_sin_precio = forecast_sarimax(
        modelo_sin_precio,
        len(y_test),
        exog=X_test_base,
        index=y_test.index,
    )

    modelos.append({
        "modelo": "SARIMAX sin precio",
        "prediccion": pred_sin_precio,
        "aic": modelo_sin_precio.aic
    })

    # --------------------------------------------------
    # Modelo con precio
    # --------------------------------------------------

    if (
        pd.notna(desviacion_precio)
        and desviacion_precio > 0
    ):
        semanal["Precio_std"] = (
            semanal["Precio_lag1"] -
            media_precio
        ) / desviacion_precio

        train = semanal[
            semanal.index <= fecha_corte
        ]

        test = semanal[
            semanal.index > fecha_corte
        ]

        variables_precio = (
            variables_base +
            ["Precio_std"]
        )

        X_train_precio = train[
            variables_precio
        ].astype(float)

        X_test_precio = test[
            variables_precio
        ].astype(float)

        modelo_con_precio = fit_sarimax(
            y_train,
            exog=X_train_precio,
            order=(0, 0, 1),
            seasonal_order=(0, 0, 0, 0),
            trend="c",
            enforce_stationarity=False,
            enforce_invertibility=False,
        )

        pred_con_precio = forecast_sarimax(
            modelo_con_precio,
            len(y_test),
            exog=X_test_precio,
            index=y_test.index,
        )

        modelos.append({
            "modelo": "SARIMAX con precio",
            "prediccion": pred_con_precio,
            "aic": modelo_con_precio.aic
        })

    # --------------------------------------------------
    # Guardar predicciones
    # --------------------------------------------------

    resultados = []

    for resultado_modelo in modelos:

        prediccion = resultado_modelo[
            "prediccion"
        ]

        for fecha in y_test.index:
            resultados.append({
                "IDProducto": id_producto,
                "Producto": nombre_producto,
                "FECHA": fecha,
                "modelo": resultado_modelo["modelo"],
                "real": y_test.loc[fecha],
                "prediccion": prediccion.loc[fecha],
                "AIC": resultado_modelo["aic"]
            })

    return resultados

todas_predicciones = []
productos_con_error = []

grupos_productos = df_productos.groupby(
    "IDProducto"
)

for id_producto, datos_producto in tqdm(
    grupos_productos,
    total=df_productos["IDProducto"].nunique()
):
    try:
        resultado = procesar_producto(
            id_producto=id_producto,
            datos_producto=datos_producto,
            df_quiebres=df_quiebres,
            fecha_corte=fecha_corte_global
        )

        todas_predicciones.extend(resultado)

    except Exception as error:
        productos_con_error.append({
            "IDProducto": id_producto,
            "Producto": (
                datos_producto["Producto"].iloc[0]
            ),
            "error": str(error)
        })

df_predicciones_globales = pd.DataFrame(
    todas_predicciones
)

df_productos_excluidos = pd.DataFrame(
    productos_con_error
)

print(
    "Productos procesados:",
    df_predicciones_globales["IDProducto"].nunique()
)

print(
    "Productos excluidos:",
    len(df_productos_excluidos)
)

def metricas_grupo(grupo):

    error = (
        grupo["real"] -
        grupo["prediccion"]
    )

    return pd.Series({
        "MAE": np.abs(error).mean(),
        "RMSE": np.sqrt(
            np.mean(error ** 2)
        ),
        "WAPE_%": (
            np.abs(error).sum()
            / np.abs(grupo["real"]).sum()
        ) * 100,
        "Sesgo": error.mean(),
        "Demanda_total": grupo["real"].sum()
    })

metricas_por_producto = (
    df_predicciones_globales
    .groupby(
        ["IDProducto", "Producto", "modelo"]
    )
    .apply(
        metricas_grupo,
        include_groups=False
    )
    .reset_index()
)

display(
    metricas_por_producto.style.format({
        "MAE": "{:,.2f}",
        "RMSE": "{:,.2f}",
        "WAPE_%": "{:.2f}%",
        "Sesgo": "{:,.2f}",
        "Demanda_total": "{:,.0f}"
    })
)

metricas_globales = (
    df_predicciones_globales
    .groupby("modelo")
    .apply(
        metricas_grupo,
        include_groups=False
    )
    .reset_index()
    .sort_values("RMSE")
)

display(
    metricas_globales.style.format({
        "MAE": "{:,.2f}",
        "RMSE": "{:,.2f}",
        "WAPE_%": "{:.2f}%",
        "Sesgo": "{:,.2f}",
        "Demanda_total": "{:,.0f}"
    })
)

ganadores_por_producto = (
    metricas_por_producto
    .sort_values(
        ["IDProducto", "RMSE"]
    )
    .drop_duplicates("IDProducto")
)

resumen_ganadores = (
    ganadores_por_producto["modelo"]
    .value_counts()
    .rename_axis("modelo")
    .reset_index(name="productos_ganados")
)

display(resumen_ganadores)

mejores_modelos = (
    metricas_por_producto
    .sort_values(
        ["IDProducto", "RMSE"]
    )
    .drop_duplicates("IDProducto")
    [
        [
            "IDProducto",
            "Producto",
            "modelo",
            "MAE",
            "RMSE",
            "WAPE_%"
        ]
    ]
)

display(mejores_modelos)

# Demanda real observada
df_productos["demanda_real"] = (
    df_productos["Facturado"] +
    df_productos["BackOrder"]
)

historial_semanal = (
    df_productos
    .groupby([
        "IDProducto",
        "Producto",
        pd.Grouper(key="FECHA", freq="W-MON")
    ])["demanda_real"]
    .sum()
    .reset_index()
    .sort_values("FECHA")
)

predicciones_ganadoras = (
    df_predicciones_globales
    .merge(
        mejores_modelos[
            ["IDProducto", "modelo"]
        ],
        on=["IDProducto", "modelo"],
        how="inner"
    )
)

# Mostrar las últimas 12 semanas de entrenamiento
fecha_inicio_grafica = (
    fecha_corte_global -
    pd.Timedelta(weeks=12)
)

productos_graficar = (
    mejores_modelos
    .sort_values("Producto")
    .reset_index(drop=True)
)

columnas = 4
filas = 5
productos_por_pagina = columnas * filas

total_paginas = int(
    np.ceil(
        len(productos_graficar)
        / productos_por_pagina
    )
)

for pagina in range(total_paginas):

    inicio = pagina * productos_por_pagina
    final = min(
        inicio + productos_por_pagina,
        len(productos_graficar)
    )

    productos_pagina = (
        productos_graficar.iloc[inicio:final]
    )

    fig, axes = plt.subplots(
        filas,
        columnas,
        figsize=(22, 18),
        squeeze=False
    )

    axes = axes.flatten()

    for posicion, (_, producto) in enumerate(
        productos_pagina.iterrows()
    ):

        ax = axes[posicion]

        id_producto = producto["IDProducto"]
        nombre_producto = producto["Producto"]
        modelo = producto["modelo"]
        mae = producto["MAE"]

        # Historial real
        real_producto = historial_semanal[
            (
                historial_semanal["IDProducto"]
                == id_producto
            )
            &
            (
                historial_semanal["FECHA"]
                >= fecha_inicio_grafica
            )
        ].sort_values("FECHA")

        # Predicción del mejor modelo
        pred_producto = predicciones_ganadoras[
            (
                predicciones_ganadoras["IDProducto"]
                == id_producto
            )
            &
            (
                predicciones_ganadoras["modelo"]
                == modelo
            )
        ].sort_values("FECHA")

        # Reemplazar en prueba por la demanda
        # utilizada realmente en la evaluación
        real_completo = real_producto[
            ["FECHA", "demanda_real"]
        ].rename(
            columns={"demanda_real": "real"}
        )

        real_completo = real_completo[
            real_completo["FECHA"]
            <= fecha_corte_global
        ]

        real_completo = pd.concat([
            real_completo,
            pred_producto[["FECHA", "real"]]
        ]).sort_values("FECHA")

        # Demanda real
        ax.plot(
            real_completo["FECHA"],
            real_completo["real"],
            color="#2F80ED",
            linewidth=2,
            marker="o",
            markersize=3,
            label="Real"
        )

        # Predicción
        ax.plot(
            pred_producto["FECHA"],
            pred_producto["prediccion"],
            color="#F26B38",
            linewidth=2,
            linestyle="--",
            marker="o",
            markersize=3,
            label="Predicción"
        )

        # Sombrear periodo de prueba
        ax.axvspan(
            fecha_corte_global,
            real_completo["FECHA"].max(),
            color="#FCEDE8",
            alpha=0.7
        )

        # Línea de separación
        ax.axvline(
            fecha_corte_global,
            color="gray",
            linestyle="--",
            linewidth=1
        )

        titulo_corto = (
            nombre_producto[:38] + "..."
            if len(nombre_producto) > 38
            else nombre_producto
        )

        ax.set_title(
            f"{titulo_corto}\n"
            f"{modelo} | MAE={mae:,.0f}",
            fontsize=9,
            loc="left"
        )

        ax.grid(True, alpha=0.25)

        ax.xaxis.set_major_locator(
            mdates.MonthLocator()
        )

        ax.xaxis.set_major_formatter(
            mdates.DateFormatter("%b-%y")
        )

        ax.tick_params(
            axis="x",
            rotation=45,
            labelsize=8
        )

        ax.tick_params(
            axis="y",
            labelsize=8
        )

    # Ocultar espacios sin producto
    for posicion in range(
        len(productos_pagina),
        len(axes)
    ):
        axes[posicion].axis("off")

    # Leyenda general
    handles, labels = axes[0].get_legend_handles_labels()

    fig.legend(
        handles,
        labels,
        loc="upper center",
        ncol=2,
        frameon=False
    )

    fig.suptitle(
        f"Validación global: demanda real frente a predicción\n"
        f"Página {pagina + 1} de {total_paginas}",
        fontsize=16,
        y=0.995
    )

    plt.tight_layout(
        rect=[0, 0, 1, 0.965]
    )

    plt.show()